force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenerarFichaClienteController_TEST.cls
@isTest (seeAllData=false)
public class GenerarFichaClienteController_TEST {

    @isTest static void test(){

        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;
        
        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.CNO__c = cnoObj.Id;
        insert ld;
        
        APXTConga4__Conga_Template__c CongaTemp = new APXTConga4__Conga_Template__c();
        CongaTemp.APXTConga4__Name__c = 'FichaCliente';
        insert CongaTemp;
        
        Test.StartTest();
        GenerarFichaClienteController.generarFichaCliente(ld.Id);
        GenerarFichaClienteController.getUrl();  
        GenerarFichaClienteController.getCongaTemplateId();
        Test.StopTest();
    }   
}