force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Leads (Nacionalidad)</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Numero_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_documento__c</fullName>
    <inlineHelpText>Si el candidato es empresa, será el número de documento de la empresa</inlineHelpText>
    <label>Número de documento</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tipo_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_documento__c</fullName>
    <inlineHelpText>Si el candidato es empresa, será el tipo de documento de la empresa</inlineHelpText>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO2__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO2__c</fullName>
    <label>Código ISO 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3_num__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3_num__c</fullName>
    <label>Código ISO 3 num</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_documento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Nº Contribuyente</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <masterLabel>Tipo de documento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestLeadTrigger.cls
@isTest
public class TestLeadTrigger {

    @isTest
    static void testAltaLead() {
        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;

        //Lead con un NIE correcto
        Lead lead = new Lead();
        lead.FirstName='prueba';
        lead.LastName='apellidos';
        lead.Email='correo@correo.es';
        lead.Status='Lead';
        lead.LeadSource='Web corporativa';
         Pais__c pais =new Pais__c();
            pais.Name='España';
            pais.Codigo_ISO2__c='ES';
            pais.Codigo_ISO3__c='ESP';
            pais.Codigo_ISO3_num__c=724;
            insert pais;
        lead.Nacionalidad__c=pais.ID;
        lead.Tipo_de_documento__c='NIE';
        lead.Numero_de_documento__c='X8819773D';
        lead.CNO__c = cnoObj.Id;
        //Lead con datos erroneos
        Lead lead2 = new Lead();
        lead2.FirstName='prueba2';
        lead2.LastName='apellidos2';
        lead2.Email='corre2@correo.es';
        lead2.Status='Lead';
        lead2.LeadSource='Web corporativa';
        lead2.CNO__c = cnoObj.Id;
        lead.Nacionalidad__c=pais.ID;
        lead.Tipo_de_documento__c='NIE';
        lead.Numero_de_documento__c='188197730';

     Test.startTest(); 
      insert lead2;
      insert lead;
     Test.stopTest();


    }

}