force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Altura_de_vivienda_interes__c.field-meta.xml
<CustomField>
    <fullName>Altura_de_vivienda_interes__c</fullName>
    <label>Altura de vivienda interés</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Altura_vivienda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Preferencia_Dormitorios__c.field-meta.xml
<CustomField>
    <fullName>Preferencia_Dormitorios__c</fullName>
    <label>Preferencia Dormitorios</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>Más de 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Uso_de_Inmueble__c.field-meta.xml
<CustomField>
    <fullName>Uso_de_Inmueble__c</fullName>
    <label>Uso de Inmueble</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª Residencia (Primer acceso)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Reposición)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Uso propio)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>Inversión</fullName>
                <isActive>false</isActive>
                <label>Inversión</label>
            </value>
            <value>
                <fullName>Residencial</fullName>
                <isActive>false</isActive>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>Vacacional</fullName>
                <isActive>false</isActive>
                <label>Vacacional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Altura_vivienda.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bajo</fullName>
    </customValue>
    <customValue>
        <fullName>Plantas intermedias</fullName>
    </customValue>
    <customValue>
        <fullName>Ático</fullName>
    </customValue>
    <customValue>
        <fullName>Más3</fullName>
        <isActive>false</isActive>
        <label>Más3</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <isActive>false</isActive>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>+3</fullName>
        <isActive>false</isActive>
        <label>+3</label>
    </customValue>
    <masterLabel>Altura vivienda</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ControllerFichaCliente_TEST.cls
@isTest (seeAllData=false)
public class ControllerFichaCliente_TEST {

    @isTest static void test_1(){
        
        Promocion__c promo = new Promocion__c();
        promo.Name = 'Nombre de la promocion';

        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj; 
 
        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.Promocion__c = promo.Id;
        ld.Preferencia_Dormitorios__c = '2';
        ld.Uso_de_Inmueble__c = '1ª Residencia (Primer acceso)';
        ld.Necesita_Financiacion__c = true;
        ld.Altura_de_vivienda_interes__c = 'Bajo';
        ld.CNO__c = cnoObj.Id;
        insert ld;
            
        Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ld);
        ControllerFichaCliente cas = New ControllerFichaCliente(sc);       
        Test.StopTest();
    }   
    
        @isTest static void test_2(){
        
        Promocion__c promo = new Promocion__c();
        promo.Name = 'Nombre de la promocion';
        
        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;

        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.Promocion__c = promo.Id;
        ld.Preferencia_Dormitorios__c = '3';
        ld.Uso_de_Inmueble__c = '2ª Residencia (Uso propio)';
        ld.Necesita_Financiacion__c = false;
        ld.Altura_de_vivienda_interes__c = 'Plantas intermedias';
        ld.CNO__c = cnoObj.Id;
        insert ld;
            
            Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ld);
        ControllerFichaCliente cas = New ControllerFichaCliente(sc);       
        Test.StopTest();
    } 
    
        @isTest static void test_3(){
        
        Promocion__c promo = new Promocion__c();
        promo.Name = 'Nombre de la promocion';

        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;
        
        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.Promocion__c = promo.Id;
        ld.Preferencia_Dormitorios__c = '4';
        ld.Uso_de_Inmueble__c = '2ª Residencia (Inversión)';
        ld.Necesita_Financiacion__c = true;
        ld.Altura_de_vivienda_interes__c = 'Ático';
        ld.CNO__c = cnoObj.Id;
        insert ld;
            
            Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ld);
        ControllerFichaCliente cas = New ControllerFichaCliente(sc);       
        Test.StopTest();
    } 
    @isTest static void test_4(){
        
        Promocion__c promo = new Promocion__c();
        promo.Name = 'Nombre de la promocion';

        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;
        
        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.Promocion__c = promo.Id;
        ld.Preferencia_Dormitorios__c = '4';
        ld.Uso_de_Inmueble__c = '1ª Residencia (Reposición)';
        ld.Necesita_Financiacion__c = true;
        ld.Altura_de_vivienda_interes__c = 'Ático';
        ld.CNO__c = cnoObj.Id;
        insert ld;
            
            Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ld);
        ControllerFichaCliente cas = New ControllerFichaCliente(sc);       
        Test.StopTest();
    } 
    @isTest static void test_5(){
        
        Promocion__c promo = new Promocion__c();
        promo.Name = 'Nombre de la promocion';

        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;
        
        Lead ld = new Lead();
        ld.LastName = 'Apellido del lead';
        ld.Promocion__c = promo.Id;
        ld.Preferencia_Dormitorios__c = '4';
        ld.Uso_de_Inmueble__c = '1ª Residencia (Inversión)';
        ld.Necesita_Financiacion__c = true;
        ld.Altura_de_vivienda_interes__c = 'Ático';
        ld.CNO__c = cnoObj.Id;
        insert ld;
            
            Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ld);
        ControllerFichaCliente cas = New ControllerFichaCliente(sc);       
        Test.StopTest();
    } 
}