force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel de la categoría</description>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spClientId__c.field-meta.xml
<CustomField>
    <fullName>spClientId__c</fullName>
    <description>El identificador del cliente de la aplicación.</description>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spClientSecret__c.field-meta.xml
<CustomField>
    <fullName>spClientSecret__c</fullName>
    <description>La contraseña</description>
    <label>Client secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spDocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>spDocumentNumber__c</fullName>
    <label>Nº Documentos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spResource__c.field-meta.xml
<CustomField>
    <fullName>spResource__c</fullName>
    <description>Identificador del recurso</description>
    <label>Resource</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TEST_BotonEnviarFacturaControllerApex.cls
@isTest(SeeAllData=false)
public class TEST_BotonEnviarFacturaControllerApex {
    
    @TestSetUp
    public static void setUp() {
        TestUtil.getLineaFactura();

        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        if(spCustomSettings.spClientId__c == null) {
            insert new SharePointConnector__c(
                spClientId__c = 'test',
                spClientSecret__c = 'test',
                spResource__c = 'test',
                spDocumentNumber__c = 1,
                spParentDir__c = 'Promociones',
                spSiteDomain__c = 'http...',
                spSiteUrl__c = 'http..'
            );
        }

        DocumentCategory__c c = new DocumentCategory__c();
        c.Level__c = 1;
        c.Code__c = '01';
        c.Name = 'Facturas';
        c.ParentDirectoryName__c = 'FACTURAS';
        insert c;
    }

    @isTest
    public static  void testGenerarFactura(){
        Factura__c factura = [SELECT Id FROM Factura__c WHERE Name = 'Test Factura' LIMIT 1];
        Id facturaId = factura.Id;
        
        BotonEnviarFacturaControllerApex.getUrl();
       	BotonEnviarFacturaControllerApex.GenerarFactura(facturaId);
        List<ContentDocumentLink> invoices = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :facturaId];
        System.assert(invoices.size() > 0);

        //BotonEnviarFacturaControllerApex.guardarFactura(facturaId);
        BotonEnviarFacturaControllerApex.enviarEmail(facturaId);
        BotonEnviarFacturaControllerApex.generarFacturaAnulacion(facturaId);
    
    }

}