force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Director_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Director_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Director_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Director_Negocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Negocio Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Dirección</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXr6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Director_Promociones__c.field-meta.xml
<CustomField>
    <fullName>Director_Promociones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Promociones Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Director Promociones</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Fin_comercializacion_prevista__c.field-meta.xml
<CustomField>
    <fullName>Fin_comercializacion_prevista__c</fullName>
    <label>Fin comercialización prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Importe_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>Importe_de_ventas__c</fullName>
    <label>Importe de ventas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Inicio_comercializacion_prevista__c.field-meta.xml
<CustomField>
    <fullName>Inicio_comercializacion_prevista__c</fullName>
    <label>Inicio de comercialización prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Marketing__c.field-meta.xml
<CustomField>
    <fullName>Marketing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Marketing</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/N_Unidades_iniciales_ritmo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>N_Unidades_iniciales_ritmo_de_ventas__c</fullName>
    <inlineHelpText>Indica el Número de Unidades a vender la primera semana.</inlineHelpText>
    <label>Nº Unidades iniciales ritmo de ventas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Ritmo_de_ventas__c.field-meta.xml
<CustomField>
    <fullName>Ritmo_de_ventas__c</fullName>
    <inlineHelpText>Indica el Número de Unidades a vender por semana.</inlineHelpText>
    <label>Ritmo de ventas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Tecnico__c.field-meta.xml
<CustomField>
    <fullName>Tecnico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Técnico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Departamento Técnico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Tecnico_Aprobador__c.field-meta.xml
<CustomField>
    <fullName>Tecnico_Aprobador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Departamento Técnico</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXrG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/Ritmo_ventas__c.object-meta.xml
<CustomObject>
    <label>Ritmo de ventas</label>
    <nameField>
        <label>Nombre de Ritmo de ventas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ritmos de ventas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ritmo_ventas__c/fields/Fecha_fin_periodo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_fin_periodo__c</fullName>
    <label>Fecha fin periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/fields/Fecha_inicio_periodo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_inicio_periodo__c</fullName>
    <label>Fecha inicio periodo</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/fields/Importe_viviendas_previstas_venta__c.field-meta.xml
<CustomField>
    <fullName>Importe_viviendas_previstas_venta__c</fullName>
    <label>Importe viviendas previstas venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/fields/N_semana__c.field-meta.xml
<CustomField>
    <fullName>N_semana__c</fullName>
    <label>Nº semana del año</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/fields/N_Viviendas_previstas_venta__c.field-meta.xml
<CustomField>
    <fullName>N_Viviendas_previstas_venta__c</fullName>
    <label>Nº Viviendas previstas venta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ritmo_ventas__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Ritmos de ventas</relationshipLabel>
    <relationshipName>Ritmos_de_ventas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spModifyPromotionTrigger__c.field-meta.xml
<CustomField>
    <fullName>spModifyPromotionTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si es true al modificar una promoción se crea la estructura de carpetas en Sharepoint</inlineHelpText>
    <label>Trigger en modificación de promoción</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/HL_Promocion.cls
public class HL_Promocion {

    public static void AfterInsert(Map<id, Promocion__c> newMap, List<Promocion__c> newVar){
        CrearRitmoVentas(newMap);
        createSharePointDirsAfterInsertContext(newVar);
    }
    
    public static void AfterUpdate(Map<id, Promocion__c> newMap, Map<id, Promocion__c> oldMap, List<Promocion__c> newVar){
        ModificarRitmoVentas(newMap, oldMap);
        createSharePointDirsAfterModifyContext(newVar);
        updateContentDocumentMarketing(Trigger.new, Trigger.old);
        
    }

/********************* Métodos auxiliares *****************/  
    
    private static void CrearRitmoVentas(Map<id, Promocion__c> newMap){
        
		map<integer, Ritmo_ventas__c> MapRitmoVentas = new map<integer, Ritmo_ventas__c>();
        
        Integer semanaInicio;
        Integer semanaFin;

        Integer NumSemanas;
        
        for(Id pro : newMap.keyset()){
            

            semanaInicio = getNumeroSemana(newMap.get(pro).Inicio_comercializacion_prevista__c);
            /*system.debug('FECHA INICIO '+newMap.get(pro).Inicio_comercializacion_prevista__c);
            system.debug('SEMANA INICIO '+semanaInicio);*/
            
            semanaFin = getNumeroSemana(newMap.get(pro).fin_comercializacion_prevista__c);
            /*system.debug('FECHA FIN '+newMap.get(pro).fin_comercializacion_prevista__c);
            system.debug('SEMANA FIN '+semanaFin);*/
            
            NumSemanas = (newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek().daysBetween(newMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek()))/7; 
            
			integer contador = 0;
            Date fechaInicioSemana = newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek();
            
            
            for(integer i = 0; i <= NumSemanas; i++){
                

                Ritmo_ventas__c ritmoVentas = new Ritmo_ventas__c();
                ritmoVentas.promocion__c = pro;
                
                //Primera semana
                if(contador == 0){
                    
                    ritmoVentas.Fecha_inicio_periodo__c = newMap.get(pro).Inicio_comercializacion_prevista__c;
                    
                    //Si es la misma semana
                    if(newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek() == newMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek()){
                        
                        ritmoVentas.Fecha_fin_periodo__c = newMap.get(pro).fin_comercializacion_prevista__c;
                    }
                    else{
                        
                        ritmoVentas.Fecha_fin_periodo__c = fechaInicioSemana.addDays(6);
                    }
                    
                    ritmoVentas.N_semana__c = getNumeroSemana(newMap.get(pro).Inicio_comercializacion_prevista__c);
                    ritmoVentas.N_Viviendas_previstas_venta__c = newMap.get(pro).N_Unidades_iniciales_ritmo_de_ventas__c;
                    ritmoVentas.Importe_viviendas_previstas_venta__c = newMap.get(pro).Importe_de_ventas__c;
 
                }
                else{

                    ritmoVentas.N_semana__c = getNumeroSemana(newMap.get(pro).Inicio_comercializacion_prevista__c.addDays(7*contador));
                    
                    ritmoVentas.Fecha_inicio_periodo__c = fechaInicioSemana.addDays(7*contador);
                    ritmoVentas.N_Viviendas_previstas_venta__c = newMap.get(pro).ritmo_de_ventas__c;
                    ritmoVentas.Importe_viviendas_previstas_venta__c = newMap.get(pro).Importe_de_ventas__c;
                    
                    
                    if(fechaInicioSemana.addDays((7*contador)+6)< newMap.get(pro).fin_comercializacion_prevista__c){
                        
                        ritmoVentas.Fecha_fin_periodo__c = fechaInicioSemana.addDays((7*contador)+6);
                        
                    }
                    else{

                    	ritmoVentas.Fecha_fin_periodo__c = newMap.get(pro).fin_comercializacion_prevista__c;
                    }   
                }
             	//Limita el tamaño del nombre de la promoción para no exceder el límite de 80 caracteres en el campo name.
                ritmoVentas.name =  ritmoVentas.N_semana__c + ' '+ ritmoVentas.Fecha_inicio_periodo__c.year();
                MapRitmoVentas.put(contador,ritmoVentas);
                contador += 1;
            }   
        }
        insert MapRitmoVentas.values();
    }
    
    
    private static void ModificarRitmoVentas(Map<id, Promocion__c> newMap, Map<id, Promocion__c> oldMap){
        
        
        set<id> setPromociones = new Set<id>();
        set<id> setRitmosABorrar = new Set<id>();
        
        List<ritmo_ventas__c> ListRitmosABorrar = new  List<ritmo_ventas__c>();
        List<ritmo_ventas__c> ListRitmosACrear = new  List<ritmo_ventas__c>();
        
        
        //Se almacenan los IDs de las promociones modificadas en un conjunto
        for(id pro : newMap.keyset()){
            
            setPromociones.add(pro);
        }
        
        //Se obtienen los ritmos de ventas de las promociones modificadas
        map<id, Ritmo_ventas__c> MapRitmoVentas = new map<id, Ritmo_ventas__c>(
            [SELECT id, name,Fecha_inicio_periodo__c, Fecha_fin_periodo__c, N_semana__c, promocion__c 
             FROM Ritmo_ventas__c WHERE promocion__c IN : setPromociones]);
        

        Integer contador = 0;
        Integer NumSemanas;
        
        
        for(Id pro : newMap.keyset()){
            
            Date fechaInicioSemana = newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek();
            
            NumSemanas = (newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek().daysBetween(newMap.get(pro).fin_comercializacion_prevista__c))/7;
            
            
            //Si cambia la fecha de inicio de comercialización prevista 
            if(newMap.get(pro).Inicio_comercializacion_prevista__c != oldMap.get(pro).Inicio_comercializacion_prevista__c ){
                
                //Si se atrasa (+ tiempo)
                if(newMap.get(pro).Inicio_comercializacion_prevista__c > oldMap.get(pro).Inicio_comercializacion_prevista__c){
                    						System.debug('SE ATRASA LA FECHA DE INICIO DE COMERCIALZIACION');
                    
           
                    for(id rit : MapRitmoVentas.keyset()){
                        
                        if(MapRitmoVentas.get(rit).promocion__c == pro){
                            
                            if(MapRitmoVentas.get(rit).Fecha_inicio_periodo__c.toStartOfWeek() < newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek()){
                                
                                setRitmosABorrar.add(rit);
                            }    
                            //Si es la misma semana
                            else if(MapRitmoVentas.get(rit).Fecha_inicio_periodo__c.toStartOfWeek() == newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek()){
                                					System.debug('SE ADELANTA DENTRO DE LA MISMA SEMANA');
                               MapRitmoVentas.get(rit).Fecha_inicio_periodo__c = newMap.get(pro).Inicio_comercializacion_prevista__c;
                                
                            }
                        }
                	}//Fin for ritmoVentas
                }
                //Si se adelanta
                else{
                    									System.debug('SE ADELANTA LA FECHA DE INICIO DE COMERCIALIZACION');
                    for(id rit : MapRitmoVentas.keyset()){
                        
                        if(MapRitmoVentas.get(rit).promocion__c == pro){
                            
                            //Si se atrasa en la misma semana
                            if(MapRitmoVentas.get(rit).Fecha_inicio_periodo__c.toStartOfWeek() == newMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek()){
                                					System.debug('SE adelanta DENTRO DE LA MISMA SEMANA');
                               MapRitmoVentas.get(rit).Fecha_inicio_periodo__c = newMap.get(pro).Inicio_comercializacion_prevista__c;
                            }
                            
                            //El registro que tenía la primera semana debe cambiar su fecha de inicio de periodo al lunes anterior
                            else if(MapRitmoVentas.get(rit).Fecha_inicio_periodo__c.toStartOfWeek() == oldMap.get(pro).Inicio_comercializacion_prevista__c.toStartOfWeek()){
                                
                                MapRitmoVentas.get(rit).Fecha_inicio_periodo__c = MapRitmoVentas.get(rit).fecha_Inicio_Periodo__c.toStartofWeek();
                                
                            }
                        }
                	}//Fin for ritmoVentas
                    
                   Integer SemanasAtraso = newMap.get(pro).Inicio_comercializacion_prevista__c.daysbetween(oldMap.get(pro).Inicio_comercializacion_prevista__c)/7;
         
                    
                    //Se crean los ritmos de ventas nuevos
                            for(integer i = 0; i < SemanasAtraso; i++){
                                system.debug('semana atraso '+i);
                                Ritmo_ventas__c ritmoVentas = new Ritmo_ventas__c();
                                ritmoVentas.promocion__c = pro;
                                
                                if(contador == 0){
                                    
                                    ritmoVentas.Fecha_inicio_periodo__c = newMap.get(pro).Inicio_comercializacion_prevista__c;
                                    ritmoVentas.Fecha_fin_periodo__c = fechaInicioSemana.addDays(6);
                                    ritmoVentas.N_semana__c = getNumeroSemana(newMap.get(pro).Inicio_comercializacion_prevista__c);
                                    ritmoVentas.N_Viviendas_previstas_venta__c = newMap.get(pro).N_Unidades_iniciales_ritmo_de_ventas__c;
                                }
                                else{
                                    
                                    ritmoVentas.Fecha_inicio_periodo__c = fechaInicioSemana.addDays(7*contador);
                                    ritmoVentas.Fecha_fin_periodo__c = ritmoVentas.Fecha_inicio_periodo__c.addDays(6);
                                    ritmoVentas.N_semana__c = i;
   
                                }
                                ritmoVentas.name =  ritmoVentas.N_semana__c + ' '+ ritmoVentas.Fecha_inicio_periodo__c.year();
                                contador += 1;
                                ListRitmosACrear.add(ritmoVentas);
                                
                                
                            }//Fin for Ritmos de ventas nuevos
                }
                contador = 0;
 
    		}//Fin if cambia fecha comercialización prevista
            
            
            
            //Si cambia la fecha de fin de comercialización prevista
            if(newMap.get(pro).Fin_comercializacion_prevista__c != oldMap.get(pro).Fin_comercializacion_prevista__c ){
                
                 //Si es antes de lo previsto
                if(newMap.get(pro).fin_comercializacion_prevista__c < oldMap.get(pro).fin_comercializacion_prevista__c){
                    						
                    for(id rit : MapRitmoVentas.keyset()){
                        
                        if(MapRitmoVentas.get(rit).promocion__c == pro){
                            if(MapRitmoVentas.get(rit).Fecha_inicio_periodo__c.toStartOfWeek() > newMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek()){
                                
                                setRitmosABorrar.add(rit);
                            }    
                            //Si es la misma semana
                            else if(MapRitmoVentas.get(rit).Fecha_fin_periodo__c.toStartOfWeek() == newMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek() ){
                                					System.debug('SE ADELANTA DENTRO DE LA MISMA SEMANA');
                               MapRitmoVentas.get(rit).Fecha_fin_periodo__c = newMap.get(pro).fin_comercializacion_prevista__c;
                                
                            }
                            
                        }
                	}//Fin for ritmoVentas
                }
                //Si es despues de lo previsto
                else if(newMap.get(pro).fin_comercializacion_prevista__c > oldMap.get(pro).fin_comercializacion_prevista__c){
                    
                    System.debug('Es despues de lo previsto');
                    
                    for(id rit : MapRitmoVentas.keyset()){
                        
                        if(MapRitmoVentas.get(rit).promocion__c == pro){
                            if(MapRitmoVentas.get(rit).Fecha_fin_periodo__c.toStartOfWeek() == newMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek() ){
                                					System.debug('SE ATRASA DENTRO DE LA MISMA SEMANA');
                               MapRitmoVentas.get(rit).Fecha_fin_periodo__c = newMap.get(pro).fin_comercializacion_prevista__c;
                            }
                            
                            //El registro que tenía la última semana debe cambiar su fecha de fin de periodo al Domingo siguiente
                           else if(MapRitmoVentas.get(rit).Fecha_fin_periodo__c.toStartOfWeek() == oldMap.get(pro).fin_comercializacion_prevista__c.toStartOfWeek()){
                                
                                MapRitmoVentas.get(rit).Fecha_fin_periodo__c = MapRitmoVentas.get(rit).fecha_Inicio_Periodo__c.toStartofWeek().addDays(6);
                                
                            }
                        }
                	}//Fin for ritmoVentas
                    
                    contador=1;
                    Date fechaFinOld = oldMap.get(pro).fin_comercializacion_prevista__c.toStartofWeek();
                    Integer SemanasAtraso = oldMap.get(pro).fin_comercializacion_prevista__c.daysbetween(newMap.get(pro).fin_comercializacion_prevista__c)/7;
                    							
                    //Se crean los ritmos de ventas nuevos
                            for(integer i = 0; i < SemanasAtraso; i++){
                                						
                                Ritmo_ventas__c ritmoVentas = new Ritmo_ventas__c();
                                
                                ritmoVentas.promocion__c = pro;
                                ritmoVentas.Fecha_inicio_periodo__c = fechaFinOld.addDays(7*contador);
                                ritmoVentas.N_semana__c = getNumeroSemana(ritmoVentas.Fecha_inicio_periodo__c);
   
                                if(i == SemanasAtraso-1){
                                    
                                    ritmoVentas.Fecha_fin_periodo__c = newMap.get(pro).fin_comercializacion_prevista__c;
                                }
                                else{
                                    ritmoVentas.Fecha_fin_periodo__c = ritmoVentas.Fecha_inicio_periodo__c.addDays(6);
                                }
                                
                                ritmoVentas.name =  ritmoVentas.N_semana__c + ' '+ ritmoVentas.Fecha_fin_periodo__c.year();
								contador += 1;
                                ListRitmosACrear.add(ritmoVentas);
                                
                                
                            }//Fin for Ritmos de ventas nuevos
                }
  
            }
    	}//Fin for
        

        for(id rit : MapRitmoVentas.keyset()){
            
            if(setRitmosABorrar.contains(rit)){
                
                ListRitmosABorrar.add(MapRitmoVentas.get(rit));
            }
        }
        
        insert ListRitmosACrear;
        update MapRitmoVentas.values();
        delete ListRitmosABorrar;
    }
    
    
    private static void createSharePointDirsAfterModifyContext(List<Promocion__c> newVar) {
        List<String> foldersList = new List<String>();
        List<AggregateResult> results = [SELECT ParentDirectoryName__c  FROM DocumentCategory__c WHERE ParentDirectoryName__c != '' GROUP BY ParentDirectoryName__c];
        for(AggregateResult r : results) {
            foldersList.add((String) r.get('ParentDirectoryName__c'));
        }

        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c;
        baseDirPath = baseDirPath != null ? spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '') : '';

        if(spCustomSettings.spModifyPromotionTrigger__c && !Test.isRunningTest()) {
            for(Promocion__c promocion : newVar) {
                String parentDirPath = baseDirPath + parentDir + '/' + promocion.Name;
                FutureSharePointConnector.createFolders(parentDirPath, foldersList);
            }
        }
    }

    private static void createSharePointDirsAfterInsertContext(List<Promocion__c> newVar) {
        List<String> foldersList = new List<String>();
        List<AggregateResult> results = [SELECT ParentDirectoryName__c  FROM DocumentCategory__c WHERE ParentDirectoryName__c != '' GROUP BY ParentDirectoryName__c];
        for(AggregateResult r : results) {
            foldersList.add((String) r.get('ParentDirectoryName__c'));
        }

        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c;
        baseDirPath = baseDirPath != null ? spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '') : '';

        for(Promocion__c promocion : newVar) {
            if(!Test.isRunningTest()) {
                String parentDirPath = baseDirPath + parentDir + '/' + promocion.Name;
                FutureSharePointConnector.createFolders(parentDirPath, foldersList);
            }
        }
    }
    
    //Formula para obtener el número de la semana de una fecha concreta
    private static integer getNumeroSemana(Date fecha){
        Date fechaAux = date.newInstance(fecha.year(), 01, 01);
        integer diasTrancurridos = fechaAux.daysBetween(fecha);
        return math.mod(math.floor(diasTrancurridos/7).intValue(), 52)+1;
    }
    
    public static void updateContentDocumentMarketing(List<Promocion__c> promocionNew, List<Promocion__c> promocionOld) {
        List<Id> promocionIdList = new List<Id>();
        Map<Id, Id> mapOldUserNewUser = new Map<Id, Id>();
        for(Integer i = 0; i < promocionNew.size(); i++){
            if(promocionOld[i].Marketing__c != promocionNew[i].Marketing__c){
                mapOldUserNewUser.put(promocionOld[i].Marketing__c, promocionNew[i].Marketing__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Director_Comercial__c != promocionNew[i].Director_Comercial__c){
                mapOldUserNewUser.put(promocionOld[i].Director_Comercial__c, promocionNew[i].Director_Comercial__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Director_Negocio__c != promocionNew[i].Director_Negocio__c){
                mapOldUserNewUser.put(promocionOld[i].Director_Negocio__c, promocionNew[i].Director_Negocio__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Director_Promociones__c != promocionNew[i].Director_Promociones__c){
                mapOldUserNewUser.put(promocionOld[i].Director_Promociones__c, promocionNew[i].Director_Promociones__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Tecnico__c != promocionNew[i].Tecnico__c){
                mapOldUserNewUser.put(promocionOld[i].Tecnico__c, promocionNew[i].Tecnico__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Responsable_Comercial__c != promocionNew[i].Responsable_Comercial__c){
                mapOldUserNewUser.put(promocionOld[i].Responsable_Comercial__c, promocionNew[i].Responsable_Comercial__c);
                promocionIdList.add(promocionOld[i].Id);
            }
            if(promocionOld[i].Tecnico_Aprobador__c != promocionNew[i].Tecnico_Aprobador__c){
                mapOldUserNewUser.put(promocionOld[i].Tecnico_Aprobador__c, promocionNew[i].Tecnico_Aprobador__c);
                promocionIdList.add(promocionOld[i].Id);
            }
        }
        
        if(promocionIdList.size() > 0){
            List<ContentDocumentLink> cdlPromocionList = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN: promocionIdList];
             
            Set<Id> contentDocumentIdList = new Set<Id>();
            for(ContentDocumentLink contentDocumentLink : cdlPromocionList)
                contentDocumentIdList.add(contentDocumentLink.ContentDocumentId);
            
            if(!cdlPromocionList.isEmpty()) {
                List<ContentDocumentLink> cdlContentDocumentList = [SELECT ContentDocumentId, LinkedEntityId, ShareType FROM ContentDocumentLink WHERE ContentDocumentId IN: contentDocumentIdList];
                
                Set<Id> linkedUsers = new Set<Id>();
                for(ContentDocumentLink cdl : cdlContentDocumentList)
                    if(cdl.LinkedEntityId.getSObjectType() == Schema.User.getsObjectType() && !linkedUsers.contains(cdl.LinkedEntityId)) linkedUsers.add(cdl.LinkedEntityId);

                List<ContentDocumentLink> cdlToInsert = new List<ContentDocumentLink>();
                List<ContentDocumentLink> cdlToDelete = new List<ContentDocumentLink>();
                
                for(ContentDocumentLink cdlContentDocument : cdlContentDocumentList){
                    if(mapOldUserNewUser.keySet().contains(cdlContentDocument.LinkedEntityId) && cdlContentDocument.ShareType == 'C'){
                        if(mapOldUserNewUser.get(cdlContentDocument.LinkedEntityId) != null){
                            ContentDocumentLink contentDocumentLinkAux = new ContentDocumentLink();
                            contentDocumentLinkAux.LinkedEntityId = mapOldUserNewUser.get(cdlContentDocument.LinkedEntityId); 
                            contentDocumentLinkAux.ContentDocumentId = cdlContentDocument.ContentDocumentId;
                            contentDocumentLinkAux.ShareType = 'C';
                            if(!linkedUsers.contains(contentDocumentLinkAux.LinkedEntityId)) cdlToInsert.add(contentDocumentLinkAux);
                        }
                        cdlToDelete.add(cdlContentDocument);
                    }
                }
                
                if(!cdlToInsert.isEmpty()) insert cdlToInsert;
                if(!cdlToDelete.isEmpty()) delete cdlToDelete;
            }            
        }


    }

    
}