force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel de la categoría</description>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spClientId__c.field-meta.xml
<CustomField>
    <fullName>spClientId__c</fullName>
    <description>El identificador del cliente de la aplicación.</description>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spClientSecret__c.field-meta.xml
<CustomField>
    <fullName>spClientSecret__c</fullName>
    <description>La contraseña</description>
    <label>Client secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spDocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>spDocumentNumber__c</fullName>
    <label>Nº Documentos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spResource__c.field-meta.xml
<CustomField>
    <fullName>spResource__c</fullName>
    <description>Identificador del recurso</description>
    <label>Resource</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TEST_BotonAdendaController.cls
@isTest(SeeAllData=false)
public class TEST_BotonAdendaController {

    @TestSetUp
    public static void setUp() {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        insert new SharePointConnector__c(
            spClientId__c = 'test',
            spClientSecret__c = 'test',
            spResource__c = 'test',
            spDocumentNumber__c = 1,
            spParentDir__c = 'Promociones',
            spSiteDomain__c = 'http...',
            spSiteUrl__c = 'http..'
        );

        Plan_de_pagos__c planPagos = TESTUtil.getPlan_de_Pagos_controller();
        //TestUtil.getImagen();
		
        DocumentCategory__c c = new DocumentCategory__c();
        c.Level__c = 1;
        c.Code__c = '01';
        c.Name = 'Contratos de reserva viviendas';
        c.ParentDirectoryName__c = 'COMERCIAL';
        insert c;
        
        /*APXTConga4__Conga_Template__c CongaTemp = new APXTConga4__Conga_Template__c();
        CongaTemp.APXTConga4__Name__c = 'DocumentoAdendaSolution';
        insert CongaTemp;*/  
        
    }

    @IsTest 
    public static void getTipoVivienda_Test1(){
        Test.startTest();
        Plan_de_pagos__c planPagos = [SELECT Id,Oportunidad__c FROM Plan_de_pagos__c WHERE Name = 'Plan Pagos Test' LIMIT 1];
        system.debug('TEST PLAN DE PAGOS'+planPagos);
        
        BotonAdendaController.getUrl();
        //BotonAdendaController.getCongaURL(planPagos.Id);
        BotonAdendaController.generarContrato(planPagos.Oportunidad__c, 'Libre', 'VF_Documento_adenda', 'Prueba');
        List<ContentDocumentLink> docs = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :planPagos.Oportunidad__c];
        System.assert(docs.size() > 0);
       	Test.stopTest();
    }

    @IsTest
    public static void getTipoVivienda_Test2(){
        Test.startTest();
        Plan_de_pagos__c planPagos = [SELECT Id,Oportunidad__c FROM Plan_de_pagos__c WHERE Name = 'Plan Pagos Test' LIMIT 1];
        system.debug('TEST PLAN DE PAGOS'+planPagos);
        
        BotonAdendaController.getUrl();
        BotonAdendaController.generarContrato(planPagos.Oportunidad__c, 'Reserva', 'VF_Documento_reserva_conIVA', 'FichaReserva');
        List<ContentDocumentLink> docs = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :planPagos.Oportunidad__c];
        System.assert(docs.size() > 0);
        Test.stopTest();
    }

    @IsTest
    public static void getTipoVivienda_Test3(){
       	Test.startTest();
        Plan_de_pagos__c planPagos = [SELECT Id,Oportunidad__c FROM Plan_de_pagos__c WHERE Name = 'Plan Pagos Test' LIMIT 1];
        system.debug('TEST PLAN DE PAGOS'+planPagos);
           
        BotonAdendaController.getUrl();
        BotonAdendaController.generarContrato(planPagos.Oportunidad__c, 'Escrituración', 'VF_Documento_reserva_conIVA', 'FichaReserva');
        List<ContentDocumentLink> docs = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :planPagos.Oportunidad__c];
        System.assert(docs.size() > 0);
        Test.stopTest();
    }
    
    @IsTest
    public static void getTipoVivienda_Test4(){
        Test.startTest();
        Plan_de_pagos__c planPagos = [SELECT Id,Oportunidad__c FROM Plan_de_pagos__c WHERE Name = 'Plan Pagos Test' LIMIT 1];
        system.debug('TEST PLAN DE PAGOS'+planPagos);
        
        BotonAdendaController.getUrl();
        BotonAdendaController.generarContrato(planPagos.Oportunidad__c, 'Contrato', 'VF_Documento_reserva_conIVA', 'FichaReserva');
        List<ContentDocumentLink> docs = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :planPagos.Oportunidad__c];
        System.assert(docs.size() > 0);
        Test.stopTest();
    }
    
    @IsTest
    public static void getTipoVivienda_Test5(){
        Test.startTest();
        Plan_de_pagos__c planPagos = [SELECT Id,Oportunidad__c FROM Plan_de_pagos__c WHERE Name = 'Plan Pagos Test' LIMIT 1];
        system.debug('TEST PLAN DE PAGOS'+planPagos);
        
        BotonAdendaController.getUrl();
        BotonAdendaController.generarContrato(planPagos.Oportunidad__c, 'Cancelada', 'VF_Documento_reserva_conIVA', 'FichaReserva');
        List<ContentDocumentLink> docs = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :planPagos.Oportunidad__c];
        System.assert(docs.size() > 0);
        Test.stopTest();
    }
    
}