force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel de la categoría</description>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spClientId__c.field-meta.xml
<CustomField>
    <fullName>spClientId__c</fullName>
    <description>El identificador del cliente de la aplicación.</description>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spClientSecret__c.field-meta.xml
<CustomField>
    <fullName>spClientSecret__c</fullName>
    <description>La contraseña</description>
    <label>Client secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spDocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>spDocumentNumber__c</fullName>
    <label>Nº Documentos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spResource__c.field-meta.xml
<CustomField>
    <fullName>spResource__c</fullName>
    <description>Identificador del recurso</description>
    <label>Resource</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestSharePointConnectorMappings.cls
@IsTest
public class TestSharePointConnectorMappings {

    @TestSetUp
    private static void setUp() {
        //new TestUtil();
        TestUtil.getOportunidadDocumento_reserva_controller();

        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        if(spCustomSettings.spClientId__c == null) {
            insert new SharePointConnector__c(
                spClientId__c = 'test',
                spClientSecret__c = 'test',
                spResource__c = 'test',
                spDocumentNumber__c = 1,
                spParentDir__c = 'Promociones',
                spSiteDomain__c = 'http...',
                spSiteUrl__c = 'http..'
            );
        }

        DocumentCategory__c c = new DocumentCategory__c();
        c.Level__c = 1;
        c.Code__c = '02';
        c.Name = 'Contratos de reserva viviendas';
        c.ParentDirectoryName__c = 'COMERCIAL';
        insert c;
    }

    @IsTest
    public static void testGetFilterByType() {
        // Promocion
        Promocion__c promo = [SELECT Id FROM Promocion__c WHERE Name = 'Promocion test'];
        String filter = SharePointConnectorMappings.getFilterByType(promo.Id.getSObjectType(), promo.Id);
        System.assertEquals('IdPromocion eq \''+promo.Id+'\'', filter);

        // Oportunidad
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Promocion__c = :promo.Id];
        filter = SharePointConnectorMappings.getFilterByType(opp.Id.getSObjectType(), opp.Id);
        System.assertEquals('IdOportunidad eq \''+opp.Id+'\'', filter);
    }

    @IsTest
    public static void testGetSelectFieldsByType() {
        // Promocion
        Promocion__c promo = [SELECT Id FROM Promocion__c WHERE Name = 'Promocion test'];
        List<String> selectFields = SharePointConnectorMappings.getSelectFieldsByType(promo.Id.getSObjectType());
        System.assert(selectFields.contains('IdPromocion'));

        // Oportunidad
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Promocion__c = :promo.Id];
        selectFields = SharePointConnectorMappings.getSelectFieldsByType(opp.Id.getSObjectType());
        System.assert(selectFields.contains('IdOportunidad'));
    }

    @IsTest
    public static void testGetParentMetadataFieldByType() {
        // Promocion
        Promocion__c promo = [SELECT Id FROM Promocion__c WHERE Name = 'Promocion test'];
        String metaDataField = SharePointConnectorMappings.getParentMetadataFieldByType(promo.Id.getSObjectType());
        System.assert(metaDataField.equals('IdPromocion'));

        // Oportunidad
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Promocion__c = :promo.Id];
        metaDataField = SharePointConnectorMappings.getParentMetadataFieldByType(opp.Id.getSObjectType());
        System.assert(metaDataField.equals('IdOportunidad'));
    }

    @IsTest
    public static void testGetPromotionQueryByType() {
        // Promocion
        Promocion__c promo = [SELECT Id FROM Promocion__c WHERE Name = 'Promocion test'];
        String promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(promo.Id.getSObjectType());
        System.assert(promotionQuery.equals('SELECT Name FROM Promocion__c WHERE Id = $value$'));

        // Oportunidad
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Promocion__c = :promo.Id];
        promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(opp.Id.getSObjectType());
        System.assert(promotionQuery.equals('SELECT Name FROM Promocion__c WHERE Id IN (SELECT Promocion__c FROM Opportunity WHERE Id = $value$)'));
    }
	/*
    @IsTest
    public static void testGetNameByCats() {
        String fileName = SharePointConnectorMappings.getNameByCats(new List<String> {'Contratos de reserva viviendas'});
        system.debug('fileName:::'+fileName);
        System.assert(fileName.containsIgnoreCase('001-02-Contratos de reserva viviendas-COMERCIAL_Contratos de reserva viviendas-20'));
    }
	*/
}