force-app/main/default/objects/ContentVersion/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Version_History__c.field-meta.xml
<CustomField>
    <fullName>Document_Version_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Version History</label>
    <referenceTo>DocumentVersionHistory__c</referenceTo>
    <relationshipLabel>Content Versions (Document Version History)</relationshipLabel>
    <relationshipName>Content_Versions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/DocumentVersionHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico Versiones Documento</label>
    <nameField>
        <displayFormat>DVH-{00000}</displayFormat>
        <label>Document Version History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos Versiones de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de Aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro Superficies</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HL_DocumentVersionHistoryTrigger.cls
public class HL_DocumentVersionHistoryTrigger extends TriggerHandler {
    
    protected override void afterUpdate() {
        cloneApprovedContentVersion((Map<Id, DocumentVersionHistory__c>)Trigger.newMap, (Map<Id, DocumentVersionHistory__c>)Trigger.oldMap);
    }
    
    public void cloneApprovedContentVersion(Map<Id, DocumentVersionHistory__c> newMap, Map<Id, DocumentVersionHistory__c> oldMap) {
        Set<Id> dvhs = new Set<Id>();
        for(Id i : newMap.keySet()) {
            if(newMap.get(i).Estado__c != oldMap.get(i).Estado__c && newMap.get(i).Estado__c == 'Aprobado')
                dvhs.add(i);
        }
        if(!dvhs.isEmpty()) cloneApprovedContentVersion2(dvhs);
    }
    
    @future
    public static void cloneApprovedContentVersion2(Set<Id> dvhIds){
        List<ContentVersion> contentVersionApprovedList = [SELECT Id, Title, ContentDocumentId, Tipo__c, Activo__c, PathOnClient, VersionData 
                                                           FROM ContentVersion 
                                                           WHERE Document_Version_History__c = :dvhIds]; 
        
        List<ContentVersion> toCreate = new List<ContentVersion>();
        for(ContentVersion cv : contentVersionApprovedList){
            ContentVersion ncv = new ContentVersion();
            ncv.title = cv.title;
            ncv.ContentDocumentId = cv.ContentDocumentId;
            ncv.Tipo__c = cv.Tipo__c;
            ncv.Activo__c = true;
            ncv.PathOnClient = cv.PathOnClient;
            ncv.Document_Version_History__c = null;
            
            if(Test.isRunningTest()) ncv.VersionData = blob.valueOf('Unit.Test');
            else ncv.VersionData = cv.VersionData;
            
            toCreate.add(ncv);
        }
        insert toCreate;
    }
    
}