force-app/main/default/objects/ContentVersion/fields/Document_Version_History__c.field-meta.xml
<CustomField>
    <fullName>Document_Version_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Version History</label>
    <referenceTo>DocumentVersionHistory__c</referenceTo>
    <relationshipLabel>Content Versions (Document Version History)</relationshipLabel>
    <relationshipName>Content_Versions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cuadro_Superficies__c/Cuadro_Superficies__c.object-meta.xml
<CustomObject>
    <label>Cuadro Superficies</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Cuadro Superficies Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cuadros Superficies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cuadro_Superficies__c/fields/Document_Version_History__c.field-meta.xml
<CustomField>
    <fullName>Document_Version_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Version History</label>
    <referenceTo>DocumentVersionHistory__c</referenceTo>
    <relationshipLabel>Cuadros Superficies</relationshipLabel>
    <relationshipName>Cuadros_Superficies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cuadro_Superficies__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Cuadros Superficies</relationshipLabel>
    <relationshipName>Cuadros_Superficies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/DocumentVersionHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico Versiones Documento</label>
    <nameField>
        <displayFormat>DVH-{00000}</displayFormat>
        <label>Document Version History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos Versiones de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Director_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Director_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Versions_History4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Director_Promociones__c.field-meta.xml
<CustomField>
    <fullName>Director_Promociones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Promociones</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Versions_History2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Director_Tecnico__c.field-meta.xml
<CustomField>
    <fullName>Director_Tecnico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Técnico</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Versions_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Document_Version_History_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Version_History_Name__c</fullName>
    <label>Document Version History Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de Aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/isNew__c.field-meta.xml
<CustomField>
    <fullName>isNew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isNew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipName>Document_Versions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Versions_History3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Tecnico__c.field-meta.xml
<CustomField>
    <fullName>Tecnico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Document_Versions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro Superficies</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>VersionNumber__c</fullName>
    <label>VersionNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Director_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Director_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqw</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Director_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Director_Negocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Negocio Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Dirección</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXr6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Director_Promociones__c.field-meta.xml
<CustomField>
    <fullName>Director_Promociones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Promociones Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Director Promociones</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Tecnico__c.field-meta.xml
<CustomField>
    <fullName>Tecnico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director Técnico</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Departamento Técnico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Tecnico_Aprobador__c.field-meta.xml
<CustomField>
    <fullName>Tecnico_Aprobador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Departamento Técnico</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXrG</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HL_ContentVersionTrigger.cls
public class HL_ContentVersionTrigger extends TriggerHandler {

    protected override void afterInsert() {
        relateDocumentOpportunity(Trigger.new);    
        if(!System.isFuture()) HL_ContentVersionTrigger.createDocumentVersionHistoryRecord(((Map<Id, ContentVersion>) Trigger.newMap).keySet());
    } 
    
    protected override void afterUpdate() {
        Map<Id, ContentVersion> oldMap = (Map<Id, ContentVersion>) Trigger.oldMap;
        Set<Id> cvIds = new Set<Id>();
 		for(ContentVersion cv : ((List<ContentVersion>)Trigger.new)) {
            if(oldMap.get(cv.Id).Tipo__c != cv.Tipo__c && (cv.Tipo__c == 'Memoria_calidades' || cv.Tipo__c == 'Cuadro_superficies'))
                cvIds.add(cv.Id);
        }
        
        if(!cvIds.isEmpty() && !System.isFuture()) HL_ContentVersionTrigger.createDocumentVersionHistoryRecord(((Map<Id, ContentVersion>) Trigger.newMap).keySet());
        
        addURLPublica((Map<Id, ContentVersion>) Trigger.NewMap);
            }
    
        public void addURLPublica(Map<Id, ContentVersion> newMap){
        Map<Id,ContentDistribution> mapCD = new Map<Id,ContentDistribution>();
        Set<Id> setCv = new Set<id>();
        
        for(Id cv: newMap.keySet()){
            if((newMap.get(cv).tipo__c == 'Plano_PDF' || newMap.get(cv).tipo__c == 'Imagen_carrusel' || newMap.get(cv).tipo__c == 'Plano' ||newMap.get(cv).tipo__c =='Carrusel_lifestyle'||
                newMap.get(cv).tipo__c =='Video'||newMap.get(cv).tipo__c =='Folleto'||newMap.get(cv).tipo__c =='Memoria_calidades'||newMap.get(cv).tipo__c =='Planos_zonas_comunes'||
                newMap.get(cv).tipo__c =='Carrusel_entorno'||newMap.get(cv).tipo__c =='Pie_de_web'||newMap.get(cv).tipo__c =='Imagen_financiera' || newMap.get(cv).Tipo__c == 'Video_Youtube' ) && newMap.get(cv).url__c == null){
                    
                    ContentDistribution cd = new ContentDistribution();
                    cd.Name = newMap.get(cv).title;
                    cd.ContentVersionId = cv;
                    cd.PreferencesAllowViewInBrowser= true;
                    cd.PreferencesLinkLatestVersion=true;
                    cd.PreferencesNotifyOnVisit=false;
                    cd.PreferencesPasswordRequired=false;
                    cd.PreferencesAllowOriginalDownload= true;
                    mapCd.put(cv, cd);
                    setCv.add(cv);
                }
        }
        
        if(!mapCd.isEmpty()) {
            insert mapCd.values();
            
            Map<Id, ContentDistribution> mapCdConUrl = new Map<id, ContentDistribution>([SELECT id, DistributionPublicUrl, ContentVersionId 
                                                                                         FROM ContentDistribution
                                                                                         WHERE ContentVersionId IN: setCv]);
            Map<Id, contentVersion> mapCv = new Map<id, contentVersion>();
            for(Id cd: mapCdConUrl.keySet()) {
                for(Id cv : newMap.keyset()){
                    if(mapCdConUrl.get(cd).contentVersionId == cv && newMap.get(cv).url__c == null){
                        contentVersion imagen = new ContentVersion();
                        imagen.Id = cv;
                        imagen.URL__c = mapCdConUrl.get(cd).DistributionPublicUrl;
                        mapCv.put(cv, imagen);
                    }
                }
            }
            update mapCv.values();
        }
    }
    
    public void relateDocumentOpportunity(List<ContentVersion> newList) {
        List<ContentVersion> contentVersionFilteredList = new List<ContentVersion>();
        for(ContentVersion contentVersion : newList){
            if(contentVersion.Tipo__c == 'Plano_PDF' || contentVersion.Tipo__c == 'Memoria_calidades' && contentVersion.VersionNumber == '1')
                contentVersionFilteredList.add(contentVersion);
        }
        
        if(!contentVersionFilteredList.isEmpty()){
            List<Id> parentIdList = new List<Id>();
            for(ContentVersion contentVersionFiltered : contentVersionFilteredList){
                if(contentVersionFiltered.ParentId__c != null && !parentIdList.contains(contentVersionFiltered.ParentId__c))
                    parentIdList.add(contentVersionFiltered.ParentId__c);
            }
            
            if(!parentIdList.isEmpty()){
                List<Opportunity> opportunityList = [SELECT Id, Promocion__c FROM Opportunity WHERE Promocion__c IN: parentIdList];
                List<ContentDocumentLink> contentDocumentLinkToInsert = new List<ContentDocumentLink>();
                for(Opportunity opportunity : opportunityList){
                    for(ContentVersion contentVersionFiltered : contentVersionFilteredList){
                        if(opportunity.Promocion__c == contentVersionFiltered.ParentId__c){
                            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
                            contentDocumentLink.LinkedEntityId = opportunity.Id;
                            contentDocumentLink.ContentDocumentId = contentVersionFiltered.ContentDocumentId;
                            contentDocumentLink.ShareType = 'I';
                            contentDocumentLinkToInsert.add(contentDocumentLink);
                        }
                    }
                }
                insert contentDocumentLinkToInsert;                
            }            
        }
    }
    
    /*public static Map<Id, Integer> getVersionNumber(List<ContentVersion> cvs) {
       	Map<Id, Integer> versions = new Map<Id, Integer>();
        Map<Id, Id> DVHtoCV = new Map<Id, Id>();
        for(ContentVersion cv : cvs) 
            if(cv.Document_Version_History__c != null) DVHtoCV.put(cv.Document_Version_History__c, cv.Id);
        
        for(AggregateResult r : [SELECT Id, MAX(VersionNumber__c) vn FROM DocumentVersionHistory__c WHERE Id IN :DVHtoCV.keySet() GROUP BY Id])
            versions.put( DVHtoCV.get((Id)r.get('Id')), r.get('vn') != null ? ((Decimal)r.get('vn')).intValue() +1 : 0 );
 		
        for(ContentVersion cv : cvs) 
            if(!versions.containsKey(cv.Id)) versions.put(cv.Id, 1);
        
        return versions;
    }*/
    
    public static Map<Id, Integer> getVersionNumber(List<ContentVersion> cvs) {
       	Map<Id, Integer> versions = new Map<Id, Integer>();
        Map<Id, List<ContentVersion>> DVHtoCV = new Map<Id, List<ContentVersion>>();
        for(ContentVersion cv : cvs) {
            if(!DVHtoCV.containsKey(cv.ContentDocumentId)) DVHtoCV.put(cv.ContentDocumentId, new List<ContentVersion>());
        	DVHtoCV.get(cv.ContentDocumentId).add(cv);
        }
        
        for(AggregateResult r : [SELECT ContentDocumentId, MAX(Document_Version_History__r.VersionNumber__c) vn FROM ContentVersion WHERE Document_Version_History__c != null GROUP BY ContentDocumentId]){
            if(DVHtoCV.containsKey((Id)r.get('ContentDocumentId'))){
                for(ContentVersion cv : DVHtoCV.get((Id)r.get('ContentDocumentId'))) {
                    versions.put(cv.Id, r.get('vn') != null ? ((Decimal)r.get('vn')).intValue() + 1 : 1 );
                }
            }
        }
        
        for(ContentVersion cv : cvs) 
            if(!versions.containsKey(cv.Id)) versions.put(cv.Id, 1);
        
        return versions;
    }
    
    @future
    public static void createDocumentVersionHistoryRecord(Set<Id> cvIds) {
        List<ContentVersion> cvs = [SELECT Id, Title, Tipo__c, VersionNumber, ParentId__c, Document_Version_History__c, ContentDocumentId FROM ContentVersion WHERE Id = :cvIds AND IsLatest = true];
        List<ContentVersion> contentVersionFilteredList = new List<ContentVersion>();
        List<Id> cdIds = new List<Id>();
        for(ContentVersion contentVersion : cvs){
            if(contentVersion.Tipo__c == 'Cuadro_superficies' || contentVersion.Tipo__c == 'Memoria_calidades'){
                contentVersionFilteredList.add(contentVersion);
                if(!cdIds.contains(contentVersion.ContentDocumentId)) cdIds.add(contentVersion.ContentDocumentId);
            }
        }
        if(!contentVersionFilteredList.isEmpty()){
            Map<Id, Id> cvToPromo = new Map<Id, Id>();
            Map<Id, Set<Id>> linkedEntities = new Map<Id, Set<Id>>();
            List<ContentDocumentLink> cdls = [SELECT Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE ContentDocumentId IN :cdIds];
            for(ContentDocumentLink cdl : cdls) {
                if(cdl.LinkedEntityId.getSObjectType() == Schema.Promocion__c.getsObjectType())
                    cvToPromo.put(cdl.ContentDocumentId, cdl.LinkedEntityId);

                if(cdl.LinkedEntityId.getSObjectType() == Schema.User.getsObjectType()) {
                    if(!linkedEntities.containsKey(cdl.ContentDocumentId)) linkedEntities.put(cdl.ContentDocumentId, new Set<Id>());
                    linkedEntities.get(cdl.ContentDocumentId).add(cdl.LinkedEntityId);
                }
            }
            
            Map<Id, Promocion__c> promos = new Map<Id, Promocion__c>([SELECT Id, Tecnico_Aprobador__c, Tecnico__c, Director_Promociones__c, Responsable_Comercial__c, Director_Comercial__c, Director_Negocio__c   
                                                                      FROM Promocion__c 
                                                                      WHERE Id IN :cvToPromo.values()]);
            Map<Id, DocumentVersionHistory__c> CVandDVHMap = new Map<Id, DocumentVersionHistory__c>();
            List<ContentDocumentLink> cdlToInsert = new List<ContentDocumentLink>();
            Map<Id, Integer> versions = getVersionNumber(contentVersionFilteredList);
            for(ContentVersion contentVersionFiltered : contentVersionFilteredList){
                DocumentVersionHistory__c documentVersionHistory = new DocumentVersionHistory__c();
                documentVersionHistory.Document_Version_History_Name__c = contentVersionFiltered.Title + ' - v' + versions.get(contentVersionFiltered.Id);
                documentVersionHistory.Tipo__c = contentVersionFiltered.Tipo__c;
                documentVersionHistory.Estado__c = 'Pendiente de Aprobación';
                documentVersionHistory.Promocion__c = cvToPromo.get(contentVersionFiltered.ContentDocumentId);
                documentVersionHistory.isNew__c = true;
                documentVersionHistory.VersionNumber__c = versions.get(contentVersionFiltered.Id);
                documentVersionHistory.Tecnico__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Tecnico_Aprobador__c; 
                documentVersionHistory.Responsable_Comercial__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Responsable_Comercial__c;
                if(Test.isRunningTest() || !String.isBlank(promos.get(documentVersionHistory.Promocion__c).Tecnico__c) ){
                    documentVersionHistory.Director_Tecnico__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Tecnico__c;
                }else{
                    documentVersionHistory.Director_Tecnico__c = '';
                }
                documentVersionHistory.Director_Promociones__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Director_Promociones__c;
                documentVersionHistory.Director_de_Negocio__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Director_Negocio__c;
                documentVersionHistory.Director_Comercial__c = Test.isRunningTest() ? UserInfo.getUserId() : promos.get(documentVersionHistory.Promocion__c).Director_Comercial__c;
                CVandDVHMap.put(contentVersionFiltered.Id, documentVersionHistory);
                
                 if(versions.get(contentVersionFiltered.Id) == 1){
                    Map<Id, ContentDocumentLink> toAdd = new Map<Id, ContentDocumentLink>();
                    if(!String.isBlank(documentVersionHistory.Director_Tecnico__c) && !linkedEntities.get(contentVersionFiltered.ContentDocumentId).contains(documentVersionHistory.Tecnico__c)){
                        ContentDocumentLink cdlTecnico = new ContentDocumentLink(LinkedEntityId = documentVersionHistory.Tecnico__c, ContentDocumentId = contentVersionFiltered.ContentDocumentId, ShareType = 'C');
                        if(!toAdd.containsKey(cdlTecnico.LinkedEntityId)) toAdd.put(cdlTecnico.LinkedEntityId, cdlTecnico);
                    }
                    if(!linkedEntities.get(contentVersionFiltered.ContentDocumentId).contains(documentVersionHistory.Responsable_Comercial__c)){
                        ContentDocumentLink cdlRespComercial = new ContentDocumentLink(LinkedEntityId = documentVersionHistory.Responsable_Comercial__c, ContentDocumentId = contentVersionFiltered.ContentDocumentId, ShareType = 'C');
                       	if(!toAdd.containsKey(cdlRespComercial.LinkedEntityId)) toAdd.put(cdlRespComercial.LinkedEntityId, cdlRespComercial);
                    }
                    if(!String.isBlank(documentVersionHistory.Director_Tecnico__c) && !linkedEntities.get(contentVersionFiltered.ContentDocumentId).contains(documentVersionHistory.Director_Tecnico__c)){
                        ContentDocumentLink cdlDirectorTecnico = new ContentDocumentLink(LinkedEntityId = documentVersionHistory.Director_Tecnico__c, ContentDocumentId = contentVersionFiltered.ContentDocumentId, ShareType = 'C');
                        if(!toAdd.containsKey(cdlDirectorTecnico.LinkedEntityId)) toAdd.put(cdlDirectorTecnico.LinkedEntityId, cdlDirectorTecnico);
                    }
                    if(!linkedEntities.get(contentVersionFiltered.ContentDocumentId).contains(documentVersionHistory.Director_Promociones__c)){
                        ContentDocumentLink cdlDirectorPromociones = new ContentDocumentLink(LinkedEntityId = documentVersionHistory.Director_Promociones__c, ContentDocumentId = contentVersionFiltered.ContentDocumentId, ShareType = 'C');
                        if(!toAdd.containsKey(cdlDirectorPromociones.LinkedEntityId)) toAdd.put(cdlDirectorPromociones.LinkedEntityId, cdlDirectorPromociones);
                    }
                    if(!linkedEntities.get(contentVersionFiltered.ContentDocumentId).contains(documentVersionHistory.Director_Comercial__c)){
                        ContentDocumentLink cdlDirectorComercial = new ContentDocumentLink(LinkedEntityId = documentVersionHistory.Director_Comercial__c, ContentDocumentId = contentVersionFiltered.ContentDocumentId, ShareType = 'C');
                        if(!toAdd.containsKey(cdlDirectorComercial.LinkedEntityId)) toAdd.put(cdlDirectorComercial.LinkedEntityId, cdlDirectorComercial);
                    }
                    cdlToInsert.addAll(toAdd.values());
                }
            }
            if(!CVandDVHMap.isEmpty()) insert CVandDVHMap.values();
            if(!cdlToInsert.isEmpty()) insert cdlToInsert;
            
            Map<Id, Cuadro_Superficies__c> cuadroSuperficiesToInsert = new Map<Id, Cuadro_Superficies__c>();
            for(ContentVersion contentVersionFiltered : contentVersionFilteredList){
            	if(contentVersionFiltered.Tipo__c == 'Cuadro_superficies'){
                    Cuadro_Superficies__c cuadroSuperficies = new Cuadro_Superficies__c();
                    cuadroSuperficies.Promocion__c = cvToPromo.get(contentVersionFiltered.ContentDocumentId);
                    cuadroSuperficies.Cuadro_Superficies_Name__c = CVandDVHMap.get(contentVersionFiltered.Id).Document_Version_History_Name__c;
                    cuadroSuperficies.Document_Version_History__c = CVandDVHMap.get(contentVersionFiltered.Id).Id;
                    cuadroSuperficiesToInsert.put(contentVersionFiltered.Id, cuadroSuperficies);
                }
            }
            if(!cuadroSuperficiesToInsert.isEmpty()) insert cuadroSuperficiesToInsert.values();
            
            List<DocumentVersionHistory__c> DVHtoUpdate = new List<DocumentVersionHistory__c>();
            for(Id i : cuadroSuperficiesToInsert.keySet()) {
                CVandDVHMap.get(i).Cuadro_Superficies__c = cuadroSuperficiesToInsert.get(i).Id;
                DVHtoUpdate.add(CVandDVHMap.get(i));
            }
            if(!DVHtoUpdate.isEmpty()) update DVHtoUpdate;
            
            for(ContentVersion contentVersion : contentVersionFilteredList){
                contentVersion.Document_Version_History__c = CVandDVHMap.get(contentVersion.Id).Id; 
                contentVersion.Activo__c = false;          
            } 
            if(!contentVersionFilteredList.isEmpty()) update contentVersionFilteredList;
            
            List<ContentVersion> otherCVs = [SELECT Id, Title, ContentDocumentId, Tipo__c, Activo__c, PathOnClient, VersionData FROM ContentVersion WHERE ContentDocumentId = :cdIds AND Activo__c = true ORDER BY CreatedDate DESC LIMIT 1];
            List<ContentVersion> toCreate = new List<ContentVersion>();
            for(ContentVersion cv : otherCVs){ 
                ContentVersion ncv = new ContentVersion();
                ncv.title = cv.title;
                ncv.ContentDocumentId = cv.ContentDocumentId;
                ncv.Tipo__c = cv.Tipo__c;
                ncv.Activo__c = cv.Activo__c;
                ncv.PathOnClient = cv.PathOnClient;
                ncv.Document_Version_History__c = null;
                
                if(Test.isRunningTest()) ncv.VersionData = blob.valueOf('Unit.Test');
                else ncv.VersionData = cv.VersionData;
                
                toCreate.add(ncv);
            }
            if(!toCreate.isEmpty()) insert toCreate; 
        }
    }
}