force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garaje</fullName>
            </value>
            <value>
                <fullName>Trastero</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Mejoras</fullName>
            </value>
            <value>
                <fullName>Personalizacion</fullName>
                <label>Personalización</label>
            </value>
            <value>
                <fullName>Descuento</fullName>
                <isActive>false</isActive>
                <label>Descuento</label>
            </value>
            <value>
                <fullName>Mobiliario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TEST_PlanoTipoInmuebleController.cls
@isTest
public class TEST_PlanoTipoInmuebleController {
    
    @isTest
    public static void testPlanoInmueble() {
        Product2 inmueble = TestUtil.getInmueble();
        
        ContentVersion cv = new ContentVersion();
        
        cv.title = 'Imagen prueba';
        cv.PathOnClient = 'URL de prueba';
        cv.Tipo__c = 'Plano';
        cv.ParentId__c = inmueble.id;
        Blob b=Blob.valueOf('prueba');
        cv.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        
        ContentVersion cv2 = [SELECT id, ContentDocumentId FROM ContentVersion WHERE id =: cv.id LIMIT 1];
        ContentDocumentLink cdl = new ContentDocumentLink();
        
        cdl.LinkedEntityId = inmueble.Id;
        cdl.ContentDocumentId =  cv2.ContentDocumentId;
        cdl.ShareType = 'V';
        insert cdl;
        
        PageReference pageRef = Page.PlanoTipoInmueble;
        System.currentPageReference().getParameters().put('id', inmueble.id);
        
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(cv);
        
        PlanoTipoInmuebleController controller = new PlanoTipoInmuebleController(stdController);
        
        Test.setCurrentPage(pageRef);
        
        String nextPage = pageRef.getUrl();
        
        System.assertEquals('/apex/planotipoinmueble', nextPage); 
    }
    
    @isTest
    public static void testPlanoTipoInmueble() {
        
        Product2 inmueble = TestUtil.getInmueble();
        ContentVersion cv = TestUtil.getPlano(inmueble.Tipo_de_inmueble__c);
        
        PageReference pageRef = Page.PlanoTipoInmueble;
        System.currentPageReference().getParameters().put('id', inmueble.id);
        
        
        ApexPages.StandardController stdController = new Apexpages.StandardController(cv);
        
        PlanoTipoInmuebleController controller = new PlanoTipoInmuebleController(stdController);
        
        Test.setCurrentPage(pageRef);
        
        String nextPage = pageRef.getUrl();
        
        System.assertEquals('/apex/planotipoinmueble', nextPage); 
    }
    
    @isTest
    public static void testPlanoTipoInmuebleException() {
           
       Product2 inmueble = TestUtil.getInmueble();
           
        PageReference pageRef = Page.PlanoTipoInmueble;
        System.currentPageReference().getParameters().put('id', inmueble.id);


        ApexPages.StandardController stdController;

        PlanoTipoInmuebleController controller = new PlanoTipoInmuebleController(stdController);
        
        Test.setCurrentPage(pageRef);
        
        String nextPage = pageRef.getUrl();

        System.assertEquals('/apex/planotipoinmueble', nextPage);

    }
}