force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Posicion__c.field-meta.xml
<CustomField>
    <fullName>Posicion__c</fullName>
    <description>Posición de la imagen en el slide</description>
    <inlineHelpText>Posición de la imagen en el slide</inlineHelpText>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel de la categoría</description>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDocumentCategory__c.field-meta.xml
<CustomField>
    <fullName>ParentDocumentCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Document Category</label>
    <referenceTo>DocumentCategory__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>DocumentSubcategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PantallaSubidaFicherosController.cls
public with sharing class PantallaSubidaFicherosController {
 
    //Obtener valores de picklist del campo tipo
    @AuraEnabled
     public static List <String> getselectOptions(sObject objObject, string fld) {
         
      system.debug('objObject --->' + objObject);
      system.debug('fld --->' + fld);
         
      List <String> allOpts = new list <String>();
         
      //Obtener el tipo del objeto
      Schema.sObjectType objType = objObject.getSObjectType();
     
      // Describe the SObject using its object type.
      Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
     
      // Get a map of fields for the SObject
      map <String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
     
      // Get the list of picklist values for this field.
      list <Schema.PicklistEntry> values = fieldMap.get(fld).getDescribe().getPickListValues();
     
      // Add these values to the selectoption list.
      for (Schema.PicklistEntry a: values) {
          
       allOpts.add(a.getValue());
      }
      system.debug('allOpts ---->' + allOpts);
         
      allOpts.sort();
         
      return allOpts;
     }
 
    //-----------------------------------------------------------------------------------------------------------------------
    
 	@AuraEnabled
    public static Id guardarArchivo(Id parentId, String nombreArchivo, String base64Data, String contentType, 
                                    String tipo, Integer posicion, String descripcion, List<DocumentCategoryOptWrapper> categories, String fileId,
                                    Boolean completed) {
        // Obtenemos el nº de documento
        String docNum = SharePointConnector.getNewDocumentNumber();
        if(fileId == '') {            
            nombreArchivo = docNum + '-' + nombreArchivo;

            // SalesForce
    	    fileId = guardarArchivoSalesForce(parentId, nombreArchivo, base64Data, contentType, tipo, posicion, descripcion);

            // Actualizamos el contador de documentos
            if(fileId != null) SharePointConnector.commitDocumentNumber();
        } else {
            Integer intDocNum = Integer.valueOf(docNum);
            docNum = String.valueOf(intDocNum).leftPad(3, '0');
            nombreArchivo = docNum + '-' + nombreArchivo;
            ContentVersion file = anadirAArchivoSalesForce(fileId, base64Data, completed);
            if(completed && file != null) {
                // SharePoint
                guardarArchivoSharePoint(parentId, nombreArchivo, EncodingUtil.urlEncode(EncodingUtil.base64Encode(file.VersionData), 'UTF-8'), 
                                            contentType, tipo, descripcion, categories);
            }
        }
        
        return fileId;
    }
    
    public static Id guardarArchivoSalesForce(Id parentId, String nombreArchivo, String base64Data, String contentType, 
                                    String tipo, Integer posicion, String descripcion) {
        
    	base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        
        ContentVersion cv = new ContentVersion();
        //cv.parentId = promocionId;
 		cv.tipo__c = tipo;
        cv.versionData = EncodingUtil.base64Decode(base64Data);
        cv.Title = nombreArchivo;
        cv.PathOnClient = nombreArchivo;
        cv.Posicion__c = posicion;
        cv.parentId__c = parentId;
        cv.Description = descripcion;
        cv.IsMajorVersion = false;                
        //cv.ContentType = contentType;
        insert cv;
        
        ContentVersion cv2 = [SELECT id, ContentDocumentId FROM ContentVersion WHERE id =: cv.id LIMIT 1];
        
        //Crear ContentDocumentLink
        ContentDocumentLink cdl = new ContentDocumentLink();
        
        cdl.LinkedEntityId = parentId;
        cdl.ContentDocumentId =  cv2.ContentDocumentId;
        cdl.ShareType = 'V';
        insert cdl;
        
        return cv.id;                    
    }
 
    private static ContentVersion anadirAArchivoSalesForce(Id fileId, String base64Data, Boolean completed) {
        base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
        ContentVersion cv = [SELECT Id, VersionData FROM ContentVersion WHERE Id = :fileId];
        if(base64Data != '') {
            String existingBody = EncodingUtil.base64Encode(cv.VersionData);
            cv.VersionData = EncodingUtil.base64Decode(existingBody + base64Data);
            //if(completed) cv.IsMajorVersion = true;
            update cv;
        }
        return completed ? cv : null;
    }
    
    public static void guardarArchivoSharePoint(Id parentId, String nombreArchivo, String base64Data, String contentType, 
                                    String tipo, String descripcion, List<DocumentCategoryOptWrapper> categories) {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '');

        // Obtención de la promoción
        String promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(parentId.getSObjectType()).replace('$value$', ':parentId');
        System.debug('query promotion: ' + promotionQuery + parentId);
        Promocion__c promotion = Database.query(promotionQuery);

        // Metadatos
        Map<String, String> metaDataMap = new Map<String, String>();        
        metaDataMap.put(SharePointConnectorMappings.getParentMetadataFieldByType(parentId.getSObjectType()), parentId);
        metaDataMap.put('TipoDocumento', tipo);
        Integer i = 1;
        for(DocumentCategoryOptWrapper cat : categories) {
            if(cat.value != '') metaDataMap.put('Categoria' + i, cat.text);
            i++;
        }
        metaDataMap.put('IdUsuario', UserInfo.getUserId());
        metaDataMap.put('Usuario', UserInfo.getUserEmail());
        if(parentId.getSObjectType() + '' != 'Promocion__c') {
            metaDataMap.put(SharePointConnectorMappings.getParentMetadataFieldByType(promotion.Id.getSObjectType()), promotion.Id);
            if(parentId.getSObjectType() + '' == 'Opportunity') {
                Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :parentId];
                metaDataMap.put('IdCuenta', opp.AccountId); 
            }
        }

        // Categorización
		DocumentCategory__c customDocCategory = null;
        String dirPath = baseDirPath+parentDir+'/' + promotion.Name;
        if(categories.size() > 0) {
        	customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Id = :categories.get(0).value];                                
            dirPath += '/' + customDocCategory.ParentDirectoryName__c;
        }
   
        if(!Test.isRunningTest()) {
            // Subida Sharepoint
            SharePointConnector spConnector = new SharePointConnector(nombreArchivo, dirPath, metaDataMap);
            spConnector.login();
            spConnector.createFile(EncodingUtil.urlDecode(base64Data, 'UTF-8'));
            spConnector.updateFileMetaData();
        }
    }
    
    //Obtener picklist dependiente

    @AuraEnabled
    public static List<DocumentCategoryWrapper> getCategoryFields() {
        List<AggregateResult> res = [SELECT COUNT_DISTINCT(Level__c) levels FROM DocumentCategory__c];
        Integer levels = (Integer) res.get(0).get('levels');
        List<DocumentCategoryWrapper> wrapperList = new List<DocumentCategoryWrapper>();
        
        for(Integer i = 1; i <= levels; i++) {
            DocumentCategoryWrapper wrapper = new DocumentCategoryWrapper();
            wrapper.level = i;
            wrapper.disabled = i == 1 ? false : true;
            wrapper.label = 'Categoría nivel ' + i;

            List<DocumentCategoryOptWrapper> opts = new List<DocumentCategoryOptWrapper>();
            if(i == 1) {                
                List<DocumentCategory__c> cats = [SELECT Code__c, Level__c, Name, ParentDirectoryName__c 
                                                   FROM DocumentCategory__c 
                                                  WHERE Level__c = :i];
                for(DocumentCategory__c cat : cats) {
                    DocumentCategoryOptWrapper opt = new DocumentCategoryOptWrapper();
                    opt.folderName = cat.ParentDirectoryName__c;
                    opt.level = cat.Level__c.intValue();
                    opt.docCode = cat.Code__c;
                    opt.value = cat.Id;
                    opt.text = cat.Name;
                    opt.text = cat.Name;
                    opt.value = cat.Id;
                    opts.add(opt);
                }
                wrapper.options = opts.clone();
            }

            wrapperList.add(wrapper);
        }
        
        System.debug('WrapperList:' + wrapperList);

        return wrapperList;
    }

    @AuraEnabled
    public static List<DocumentCategoryOptWrapper> getDependentOptsByParentCat(Id parentCategoryId) {
        List<DocumentCategoryOptWrapper> opts = new List<DocumentCategoryOptWrapper>();
        List<DocumentCategory__c> categories = [SELECT Code__c,Level__c, Name,ParentDirectoryName__c 
                                                 FROM DocumentCategory__c 
                                                WHERE ParentDocumentCategory__c = :parentCategoryId];
        
        for(DocumentCategory__c c : categories) {
            DocumentCategoryOptWrapper opt = new DocumentCategoryOptWrapper();
            if(c.Level__c == 1) opt.folderName = c.ParentDirectoryName__c;
            opt.level = c.Level__c.intValue();
            opt.docCode = c.Code__c;
            opt.value = c.Id;
            opt.text = c.Name;
            System.debug('opt: ' + opt);
			opts.add(opt);            
        }
        return opts;
    }

    public class DocumentCategoryWrapper {
        @AuraEnabled public Integer level { get; set; }
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String value { get; set; }
        @AuraEnabled public Boolean disabled { get; set; }
        @AuraEnabled public List<DocumentCategoryOptWrapper> options { get; set; }
    }

    public class DocumentCategoryOptWrapper {
        @AuraEnabled public Integer level { get; set; }
        @AuraEnabled public String numDoc { get; set; }
        @AuraEnabled public String docCode { get; set; }
        @AuraEnabled public String folderName { get; set; }
        @AuraEnabled public String text { get; set; }
        @AuraEnabled public String value { get; set; }
    }

}