force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Posicion__c.field-meta.xml
<CustomField>
    <fullName>Posicion__c</fullName>
    <description>Posición de la imagen en el slide</description>
    <inlineHelpText>Posición de la imagen en el slide</inlineHelpText>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel de la categoría</description>
    <label>Level</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDocumentCategory__c.field-meta.xml
<CustomField>
    <fullName>ParentDocumentCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Document Category</label>
    <referenceTo>DocumentCategory__c</referenceTo>
    <relationshipLabel>Document Categories</relationshipLabel>
    <relationshipName>DocumentSubcategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spClientId__c.field-meta.xml
<CustomField>
    <fullName>spClientId__c</fullName>
    <description>El identificador del cliente de la aplicación.</description>
    <label>Client Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spClientSecret__c.field-meta.xml
<CustomField>
    <fullName>spClientSecret__c</fullName>
    <description>La contraseña</description>
    <label>Client secret</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spDocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>spDocumentNumber__c</fullName>
    <label>Nº Documentos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spResource__c.field-meta.xml
<CustomField>
    <fullName>spResource__c</fullName>
    <description>Identificador del recurso</description>
    <label>Resource</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TEST_PantallaSubidaFicherosController.cls
@isTest
public class TEST_PantallaSubidaFicherosController {

    private static List<DocumentCategory__c> cats = new List<DocumentCategory__c>();

    @TestSetUp
    public static void setUp() {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        insert new SharePointConnector__c(
            spClientId__c = 'test',
            spClientSecret__c = 'test',
            spResource__c = 'test',
            spDocumentNumber__c = 1,
            spParentDir__c = 'Promociones',
            spSiteDomain__c = 'http...',
            spSiteUrl__c = 'http..'
        );
    }

    private static void setCustomCategories() {
        DocumentCategory__c cat = new DocumentCategory__c(Code__c = '01', Level__c = 1, Name = 'Categoría nivel 1', ParentDirectoryName__c = 'TECNICO');
        insert cat;
        cats.add(cat);
        cat = new DocumentCategory__c(Code__c = '01.01', Level__c = 2, Name = 'Categoría nivel 2', ParentDocumentCategory__c = cat.Id);
        cats.add(cat);
        insert cat;
    }
    
    //Comprueba que se obtienen los valores de una picklist de un determinado campo
    @isTest
    public static void testObtenerValoresPicklist(){
        
        ContentVersion imagen = TestUtil.getImagen();
        

        //Se recuperan los valores de 'tipo' de contentVersion
        
        Test.startTest();
        List <String> listaValores = PantallaSubidaFicherosController.getselectOptions(imagen, 'Tipo__c');
        
        //API name de valores disponibles 
        List <String> listaValoresEsperados = new List<String>{'Imagen','Archivo','Plano', 'Plano_PDF','Pre-reserva','Justificante de pago',
            													'Reserva','Borrador de contrato','Contrato','Factura','Imagen_carrusel',
                                                                'Carrusel_lifestyle','Video','Folleto','Memoria_calidades','Planos_zonas_comunes',
                                                                'Carrusel_entorno','Pie_de_web', 'Imagen_financiera', 'Logo Promoción', 'Cuadro_superficies',
            													'Video_Youtube', 'Visita VR'};
        
        //Se ordenan las listas para la comparacion                                                            
        listaValores.sort();
        listaValoresEsperados.sort();
        
               system.debug('listaValores '+listaValores);
               system.debug('listaValoresEsperados '+listaValoresEsperados);
                                                                    
        //Si las listas no son iguales salta
        System.assert(listaValoresEsperados == listaValores);
        Test.stopTest();
  
    }
    
    //Guarda un archivo en base de datos
    @isTest
    public static void testGuardarArchivoFromPromo(){
        ContentVersion imagen = TestUtil.getImagen();
        Id parentId = imagen.ParentId__c;
        String VersionData = EncodingUtil.base64Encode(imagen.VersionData); 
        Integer posicion = integer.valueOf(imagen.Posicion__c);
		
        Test.startTest();
        Id fileId = PantallaSubidaFicherosController.guardarArchivo(parentId, imagen.Title, VersionData, 'tipo', 
                                    imagen.Tipo__c, posicion, imagen.Description, new List<PantallaSubidaFicherosController.DocumentCategoryOptWrapper>(), '', true);
        
        PantallaSubidaFicherosController.guardarArchivo(parentId, imagen.Title, '', 'tipo', imagen.Tipo__c, posicion, imagen.Description,
                                    new List<PantallaSubidaFicherosController.DocumentCategoryOptWrapper>(), fileId, true);

        ContentVersion imagenInsertada = [SELECT id, VersionData, ContentDocumentId, ParentId__c FROM ContentVersion WHERE Title = 'Imagen prueba' LIMIT 1];
        system.assertEquals(EncodingUtil.base64Encode(imagenInsertada.VersionData), EncodingUtil.base64Encode(imagen.VersionData));
        
        ContentDocumentLink cdl = [SELECT id, ContentDocumentId,  LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: imagen.ParentId__c order by Id asc LIMIT 1];
        //system.assertEquals(cdl.ContentDocumentId, imagenInsertada.ContentDocumentId);
        Test.stopTest();
        

    }

    @isTest
    public static void testGuardarArchivoFromOpportunity() {
        
        TestUtil.getOportunidad_Contrato_Compraventa_Libre_controller();
        Test.startTest();
        ContentVersion imagen = TestUtil.testCrearImagenOpp();
        Id parentId = imagen.ParentId__c;
        String VersionData = EncodingUtil.base64Encode(imagen.VersionData); 
        Integer posicion = integer.valueOf(imagen.Posicion__c);
		system.debug('Comprobar queries aqui');
        
        Id fileId = PantallaSubidaFicherosController.guardarArchivo(parentId, imagen.Title, VersionData, 'tipo', 
                                    imagen.Tipo__c, posicion, imagen.Description, new List<PantallaSubidaFicherosController.DocumentCategoryOptWrapper>(), '', true);
		
        
        PantallaSubidaFicherosController.guardarArchivo(parentId, imagen.Title, '', 'tipo', imagen.Tipo__c, posicion, imagen.Description,
                                    new List<PantallaSubidaFicherosController.DocumentCategoryOptWrapper>(), fileId, true);
        
        ContentVersion imagenInsertada = [SELECT id, VersionData, ContentDocumentId, ParentId__c FROM ContentVersion WHERE Title = 'Imagen prueba' LIMIT 1];
        system.assertEquals(EncodingUtil.base64Encode(imagenInsertada.VersionData), EncodingUtil.base64Encode(imagen.VersionData));
        
        ContentDocumentLink cdl = [SELECT id, ContentDocumentId,  LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: imagen.ParentId__c order by Id asc LIMIT 1];
        //system.assertEquals(cdl.ContentDocumentId, imagenInsertada.ContentDocumentId);
        Test.stopTest();
    }

    @isTest
    public static void testGetCategoryFieldsOK() {
        setCustomCategories();
		
        Test.startTest();
        List<PantallaSubidaFicherosController.DocumentCategoryWrapper> wrappers = PantallaSubidaFicherosController.getCategoryFields();
        Integer i = 0;
        for(PantallaSubidaFicherosController.DocumentCategoryWrapper w : wrappers) {
            DocumentCategory__c cat = cats.get(i);
            System.assertEquals(cat.Level__c, w.level);
            System.assertEquals(cat.Name, w.label);
            if(i == 0) {
                System.assert(!w.disabled);
                System.assert(w.options.size() > 0);
                for(PantallaSubidaFicherosController.DocumentCategoryOptWrapper opt : w.options) {
                    System.assertEquals(cat.Level__c, opt.level);
                    System.assertEquals(cat.Code__c, opt.docCode);
                    System.assertEquals(cat.ParentDirectoryName__c, opt.folderName);
                    System.assertEquals(cat.Name, opt.text);
                    System.assertEquals(cat.Id, opt.value);
                }
            } else {
                System.assert(w.disabled);
                System.assert(w.options == null);
            }
            i++;
        }
        Test.stopTest();
    }

    @isTest
    public static void testGetDependentOptsByParentCat() {
        setCustomCategories();
        Test.startTest();
        List<PantallaSubidaFicherosController.DocumentCategoryOptWrapper> subcats = PantallaSubidaFicherosController.getDependentOptsByParentCat(cats.get(0).Id);
        DocumentCategory__c cat = cats.get(1);
        System.assertEquals(1, subcats.size());
        Test.stopTest();
    }

}