force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Precio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Precio_propuesto__c.field-meta.xml
<CustomField>
    <fullName>Precio_propuesto__c</fullName>
    <label>Precio propuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Construida_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Construida_m2__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Construida_m2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Superficie Construida Cerrada viv m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Construida_total_con_ZZCC_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Construida_total_con_ZZCC_m2__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Construida_total_con_ZZCC_m2__c</formula>
    <label>Superficie Construida total con ZZCC m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Jardines__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Jardines__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Jardines__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Superficie Jardines</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Terrazas_Cubiertas__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Terrazas_Cubiertas__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Terrazas_Cubiertas__c</formula>
    <label>Superficie Terrazas Cubiertas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Terrazas_Descubiertas__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Terrazas_Descubiertas__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Terrazas_Descubiertas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Superficie Terrazas Descubiertas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Superficie_Util_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Util_m2__c</fullName>
    <formula>Tipo_de_inmueble__r.Superficie_Util_m2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Superficie Util m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/N_de_banos__c.field-meta.xml
<CustomField>
    <fullName>N_de_banos__c</fullName>
    <label>Nº de baños</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/N_de_habitaciones__c.field-meta.xml
<CustomField>
    <fullName>N_de_habitaciones__c</fullName>
    <label>Nº de habitaciones</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Tipo de inmueble</relationshipLabel>
    <relationshipName>Tipo_de_inmueble</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Construida_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Construida_m2__c</fullName>
    <label>Superficie Construida Cerrada viv m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Construida_total_con_ZZCC_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Construida_total_con_ZZCC_m2__c</fullName>
    <label>Superficie Construida total con ZZCC m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Jardines__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Jardines__c</fullName>
    <label>Superficie Jardines</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Terrazas_Cubiertas__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Terrazas_Cubiertas__c</fullName>
    <label>Superficie Terrazas Cubiertas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Terrazas_Descubiertas__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Terrazas_Descubiertas__c</fullName>
    <label>Superficie Terrazas Descubiertas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Superficie_Util_m2__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Util_m2__c</fullName>
    <label>Superficie Util m2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garaje</fullName>
            </value>
            <value>
                <fullName>Trastero</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Mejoras</fullName>
            </value>
            <value>
                <fullName>Personalizacion</fullName>
                <label>Personalización</label>
            </value>
            <value>
                <fullName>Descuento</fullName>
                <isActive>false</isActive>
                <label>Descuento</label>
            </value>
            <value>
                <fullName>Mobiliario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSVProduct2LoaderController_TEST.cls
@isTest
public class CSVProduct2LoaderController_TEST {
	
    public static Id testSetup() {
        TestUtil.getProductoOportunidad();
        Id recordId = TestUtil.getPromocion(Date.newInstance(2018, 09, 20), Date.today()).Id;
        
        Tipo_de_inmueble__c tipoInmueble = new Tipo_de_inmueble__c();
        tipoInmueble.name = 'Tipo de Inmueble Vivienda Test';
        tipoInmueble.Tipo__c = 'Vivienda';
        tipoInmueble.N_de_habitaciones__c = 3;
        tipoInmueble.N_de_banos__c=2;
        tipoInmueble.Superficie_Terrazas_Descubiertas__c=7;
        tipoInmueble.Superficie_Terrazas_Cubiertas__c=6;
        tipoInmueble.Superficie_Jardines__c=12;
        tipoInmueble.Superficie_Construida_m2__c = 50;
        tipoInmueble.Superficie_Util_m2__c=55;
        tipoInmueble.Superficie_Construida_total_con_ZZCC_m2__c=60;
        insert tipoInmueble;
       	
        List<Product2> prds = new List<Product2>();
        Product2 prd1 = new Product2();
        prd1.name = 'Inmueble Test';
        prd1.Tipo_de_inmueble__c = tipoInmueble.Id;
        prd1.Precio__c=200.000;
        prd1.Promocion__c = recordId;
        prds.add(prd1);
        
        Product2 prd2 = new Product2();
        prd2.name = 'Inmueble 2 Test';
        prd2.Tipo_de_inmueble__c = tipoInmueble.Id;
        prd2.Precio__c=200.000;
        prd2.Promocion__c = recordId;
       	prds.add(prd2);
        
        insert prds;
            
        ContentVersion cv = new ContentVersion();
        cv.title = 'Test Doc';
        cv.ParentId__c = recordId;
        cv.versiondata = Blob.valueOf('Id;Name;Precio_propuesto__c\n' + prd1.Id + ';1A;11.11\n' + prd2.Id + ';1B;22.22');
        cv.Tipo__c = 'Memoria_calidades';
        cv.IsMajorVersion = true;
        cv.PathOnClient = 'URL de prueba';
        insert cv;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink link = new ContentDocumentLink(
            LinkedEntityId = recordId,
            ContentDocumentId = documents.get(0).Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert link;
        
        return recordId;
    }
    
    @isTest
    public static void testGetProfileInfo() {
        CSVProduct2LoaderController.getProfileInfo(testSetup());
    }
    
    @isTest
    public static void testFileProcessingSuccess() {
        Id prm = testSetup();

        Test.startTest();
        Opportunity opp = [SELECT Id FROM Opportunity WHERE name = 'Oportunidad Test' LIMIT 1];
        
        HelloSign__HelloSign_Signature_Request__c hellosignStatus = new HelloSign__HelloSign_Signature_Request__c(HelloSign__Latest_Action__c = 'Signature Completed',
                                                                                                                  HelloSign__Opportunity__c= opp.Id);
        insert hellosignStatus;
        List<CSVProduct2LoaderController.DocumentInfo> cdocs = new List<CSVProduct2LoaderController.DocumentInfo>();
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        CSVProduct2LoaderController.DocumentInfo di = new CSVProduct2LoaderController.DocumentInfo();
        di.Name = 'DocName';
        di.documentId = cv.ContentDocumentId;
        cdocs.add(di);
        
        CSVProduct2LoaderController.fileProcessing(prm, cdocs);
        Test.stopTest();
    }
    
    @isTest
    public static void testSaveFileSuccess() {
       	Id prm = testSetup();
        
        Test.startTest();
        List<CSVProduct2LoaderController.DocumentInfo> cdocs = new List<CSVProduct2LoaderController.DocumentInfo>();
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        CSVProduct2LoaderController.DocumentInfo di = new CSVProduct2LoaderController.DocumentInfo();
        di.Name = 'DocName';
        di.documentId = cv.ContentDocumentId;
        cdocs.add(di);
        
        CSVProduct2LoaderController.saveFile(prm, cdocs);
        Test.stopTest();
    }
    
    @isTest
    public static void testDeleteFile() {
        testSetup();
        
        ContentVersion cv = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        
        CSVProduct2LoaderController.DocumentInfo di = new CSVProduct2LoaderController.DocumentInfo();
        di.documentId = cv.ContentDocumentId;
        CSVProduct2LoaderController.deleteFile(new List<CSVProduct2LoaderController.DocumentInfo>{di});
        
        List<ContentDocument> cds = [SELECT Id FROM ContentDocument WHERE Id = :cv.ContentDocumentId];
        System.assert(cds.isEmpty());
    }
    
    @isTest
    public static void testGetProducts() {
      	CSVProduct2LoaderController.getProducts(testSetup());
    }
    
    @isTest
    public static void testReturnException() {
        CSVProduct2LoaderController.returnException('Prueba', 'Cuerpo', '');
    }
    
}