force-app/main/default/objects/ContentVersion/fields/Posicion__c.field-meta.xml
<CustomField>
    <fullName>Posicion__c</fullName>
    <description>Posición de la imagen en el slide</description>
    <inlineHelpText>Posición de la imagen en el slide</inlineHelpText>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garaje</fullName>
            </value>
            <value>
                <fullName>Trastero</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Mejoras</fullName>
            </value>
            <value>
                <fullName>Personalizacion</fullName>
                <label>Personalización</label>
            </value>
            <value>
                <fullName>Descuento</fullName>
                <isActive>false</isActive>
                <label>Descuento</label>
            </value>
            <value>
                <fullName>Mobiliario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlanoTipoInmuebleController.cls
public class PlanoTipoInmuebleController {

    public ContentVersion imagen {get;set;}
    public String prefijo {get;set;} 
    public List<ContentDocumentLink> contentDocumentLinks {get;set;}

    public PlanoTipoInmuebleController(ApexPages.StandardController stdController){
        String idInmueble = ApexPages.currentPage().getParameters().get('Id');
        prefijo = '../sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&versionId=';
        Product2 inmueble = [SELECT id, tipo_de_inmueble__c FROM Product2 WHERE id = :idInmueble LIMIT 1];
                
        try{
            contentDocumentLinks = [Select ContentDocumentId from ContentDocumentLink where LinkedEntityId =:inmueble.Id];
            if(contentDocumentLinks != null && !contentDocumentLinks.isEmpty()){
                Set<Id> contentDocumentIds = new Set<Id>();
                for (ContentDocumentLink cdl : contentDocumentLinks){
                    contentDocumentIds.add(cdl.ContentDocumentId);
                }
                List<ContentVersion> posiblesImagenes = [Select id from ContentVersion where ContentDocumentId IN: contentDocumentIds AND tipo__c='Plano' order by Posicion__c LIMIT 1];
                if(posiblesImagenes != null && !posiblesImagenes.isEmpty()){
                    imagen = posiblesImagenes.get(0);
                	return;
                }
            }
            contentDocumentLinks=[Select ContentDocumentId from ContentDocumentLink where LinkedEntityId =:inmueble.tipo_de_inmueble__c];
            Set<Id> contentDocumentIds = new Set<Id>();
            for (ContentDocumentLink cdl : contentDocumentLinks){
                contentDocumentIds.add(cdl.ContentDocumentId);
            }
            imagen = [Select id from ContentVersion where ContentDocumentId IN: contentDocumentIds AND tipo__c='Plano' order by Posicion__c LIMIT 1];
        }
        catch(exception e){
            System.debug('Se ha generado la siguiente excepción en la clase PlanoTipoInmuebleController: ' + e.getMessage());
        }
        
        /*try{
            contentDocumentLinks=[Select ContentDocumentId from ContentDocumentLink where LinkedEntityId =:inmueble.tipo_de_inmueble__c];
            System.debug(contentDocumentLinks);
            Set<Id> contentDocumentIds = new Set<Id>();
            for (ContentDocumentLink cdl : contentDocumentLinks){
                contentDocumentIds.add(cdl.ContentDocumentId);
            }
        	//imagen = [Select id from ContentVersion where Tipo_de_inmueble__c =:inmueble.tipo_de_inmueble__c AND tipo__c='Plano' LIMIT 1];
        	imagen = [Select id from ContentVersion where ContentDocumentId IN: contentDocumentIds AND tipo__c='Plano' order by Posicion__c LIMIT 1];
        }
        catch(exception e){
            System.debug('Se ha generado la siguiente excepción en la clase PlanoTipoInmuebleController: ' + e.getMessage());
        }*/
    }
}