force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Idealista__c.field-meta.xml
<CustomField>
    <fullName>Idealista__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Idealista</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Idealista__c.field-meta.xml
<CustomField>
    <fullName>Idealista__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Idealista</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/PropiedadesIntegracion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Propiedades integración</description>
    <label>PropiedadesIntegracion</label>
</CustomObject>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/ILC_IDEALISTA__c.field-meta.xml
<CustomField>
    <fullName>ILC_IDEALISTA__c</fullName>
    <label>ILC_IDEALISTA</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/URL_IDEALISTA__c.field-meta.xml
<CustomField>
    <fullName>URL_IDEALISTA__c</fullName>
    <label>URL_IDEALISTA</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Tipo de inmueble</relationshipLabel>
    <relationshipName>Tipo_de_inmueble</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPublicacionPortalIdealista.cls
@IsTest
public class TestPublicacionPortalIdealista {
	@TestSetUp
    public static void setUp() {
        new TestUtil();
        Promocion__c promo = [SELECT Id FROM Promocion__c WHERE Idealista__c = true];
        TestUtil.getImagen();
        Test.startTest();
        TestUtil.testCrearInmueblePromocionWithReturn(promo.Id);
        
        PropiedadesIntegracion__c propiedades = new PropiedadesIntegracion__c();
        propiedades.URL_IDEALISTA__c = 'http://prueba.com';
        propiedades.ILC_IDEALISTA__c = 'ilc1f58c0cc5ad3dd64528c6ae121a8de8a11a8a4f7';
        upsert propiedades;
        Test.stopTest();
    }
    
    @IsTest
    public static void test_GetPromotions() {
        Test.startTest();
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        System.assert(promos.size() > 0);
        Test.stopTest();
    }

    @IsTest
    public static void test_GetPromotionsInmuebles() {
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        Set<Id> promosIds = new Set<Id>();
        for(Promocion__c promo : promos) promosIds.add(promo.Id);

        Test.startTest();
        Map<Id, List<Product2>> inmuebles = PublicacionPortalIdealista.getPromotionsInmuebles(promosIds);
        System.assert(inmuebles.size() > 0);
        Test.stopTest();
    }

    @IsTest
    public static void test_GetProductAnnexesByPromo() {
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        Set<Id> promosIds = new Set<Id>();
        for(Promocion__c promo : promos) promosIds.add(promo.Id);

        Test.startTest();
        Map<Id, List<Product2>> annexes = PublicacionPortalIdealista.getProductAnnexesByPromo(promosIds);
        System.assert(!annexes.isEmpty());
        Test.stopTest();
    }

    @IsTest
    public static void test_getTotalPriceWithAnnexesIncluded() {
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        Set<Id> promosIds = new Set<Id>();
        for(Promocion__c promo : promos) promosIds.add(promo.Id);
        Map<Id, List<Product2>> inmuebles = PublicacionPortalIdealista.getPromotionsInmuebles(promosIds);
        Map<Id, List<Product2>> annexes = PublicacionPortalIdealista.getProductAnnexesByPromo(promosIds);

        Test.startTest();
        Decimal priceTotal = PublicacionPortalIdealista.getTotalPriceWithAnnexesIncluded(inmuebles.get(promos[0].Id).get(0), annexes.get(inmuebles.get(promos[0].Id).get(0).Id));
        System.assertEquals(1200, priceTotal);
        Test.stopTest();
    }

    @IsTest
    public static void test_GetPromotionsImgs() {
        PropiedadesIntegracion__c propiedadesIntegracion = PropiedadesIntegracion__c.getInstance();	
        String base64Content = EncodingUtil.Base64Encode( 
                Blob.valueOf('Test') 
        );
        Blob blobContent = EncodingUtil.base64Decode( base64Content );
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        System.debug('SIZE 19723: ' + promos.size());
        Set<Id> promosIds = new Set<Id>();
        for(Promocion__c promo : promos) promosIds.add(promo.Id);

        Test.startTest();
        Map<Id, List<ContentVersion>> imgsMap = PublicacionPortalIdealista.getPromotionsImgs(promosIds);
        System.debug('SIZE: ' + imgsMap.size());
        System.assert(imgsMap.size() == 1);
        Test.stopTest();
    }

    @IsTest
    public static void test_GetInmueblesImgs() {
        List<Promocion__c> promos = PublicacionPortalIdealista.getPromotions();
        Set<Id> promosIds = new Set<Id>();
        for(Promocion__c promo : promos) promosIds.add(promo.Id);

        Map<Id, Product2> inmueblesMap = new Map<Id, Product2>();
        Set<Id> tipoInmueblesIds = new Set<Id>();
        Map<Id, List<Product2>> inmuebles = PublicacionPortalIdealista.getPromotionsInmuebles(promosIds);
        for(Id promoId : inmuebles.keySet()) {
            for(Product2 inmueble : inmuebles.get(promoId)) {
                inmueblesMap.put(inmueble.Id, inmueble);    
                tipoInmueblesIds.add(inmueble.Tipo_de_inmueble__c);
            }
        }

        Test.startTest();
        Map<Id, List<ContentDocumentLink>> imgsMap = PublicacionPortalIdealista.getInmueblesImgs(tipoInmueblesIds, inmueblesMap);
        System.assertEquals(1, imgsMap.size());
        System.assertEquals(2, imgsMap.values().get(0).size());
        Test.stopTest();
    }

    @IsTest
    public static void test_GenerarJson() {
        Test.startTest();
        try{
            String jsonStr = PublicacionPortalIdealista.generarJson();
            System.debug(jsonStr);
            //JSONParser jsonParser = JSON.createParser(jsonStr);
            System.assert(jsonStr.contains('"customerCountry" : "Spain",'));
            System.assert(jsonStr.contains('"propertyCode" : "'));
            System.assert(jsonStr.contains('"addressVisibility" : "hidden",'));
            System.assert(jsonStr.contains('"featuresType" : "promo",'));
            System.assert(jsonStr.contains('"newDevelopmentTypologies" : [ {'));
            System.assert(jsonStr.contains('"featuresType" : "'));
        }catch(System.Exception e){
            System.debug(e);
        }
        

        Test.stopTest();
    }

    /*@IsTest
    public static void test_PublishOK() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IdealistaJsonPublicationCalloutMock());
        HttpResponse response = PublicacionPortalIdealista.publish();
        System.assertEquals(202, response.getStatusCode());
        Test.stopTest();
    }

    @IsTest
    public static void test_PublishJSONKO() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IdealistaJsonPublicationErrCalloutMock());
        try {
            HttpResponse response = PublicacionPortalIdealista.publish();
        } catch(Exception e) {
            System.assert(e.getMessage().contains('Error al formar el JSON de las promociones y propiedades'));
        }
        Test.stopTest();
    }

    @IsTest
    public static void test_PublishResponseKO() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IdealistaJsonPublicationErrCalloutMock());
        try {
            HttpResponse response = PublicacionPortalIdealista.publish();
        } catch(Exception e) {
            System.assert(e.getMessage().contains('Error en la llamada a Logic App de Azure -> Req: '));
        }
        Test.stopTest();
    }*/
}