force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>Pdte de Aprobación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BotonAdendaController.cls
public class BotonAdendaController {

     @auraEnabled
     public static String getUrl(){
        String dominio = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/'; 
        //String dominio = System.URL.getSalesforceBaseUrl().toExternalForm();
        return (dominio);
    }

    /* @auraEnabled
     public static String getCongaURL(String RecordId){ 
         
        APXTConga4__Conga_Solution__c CongaSol = [SELECT Id, APXTConga4__Button_body_field__c FROM APXTConga4__Conga_Solution__c WHERE Name = 'DocumentoAdendaSolution' LIMIT 1];
         
        String dominio = CongaSol.APXTConga4__Button_body_field__c;
        dominio = dominio.replace('{!Plan_de_pagos__c.Id}', RecordId);
        
         return dominio;
    }*/
    
    @auraEnabled
    public static Boolean generarContrato(Id oportunidadId, String estado, String plantilla, String nombreFichero){
    
    	List<ContentDocumentLink> listaDocumentos = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: oportunidadId];
        
        Set<id> setIdDocumentos = new Set<id>();
        system.debug('1');
       
        
        for(integer i = 0; i < listaDocumentos.size(); i++){
            
            setIdDocumentos.add(listaDocumentos[i].ContentDocumentId);
        }
        
         List<ContentVersion> listaContenidoDocumentos = [SELECT id FROM ContentVersion WHERE ContentDocumentId IN : setIdDocumentos];
         system.debug('2');

        
            
            guardarPresupuesto(oportunidadId, estado, plantilla, nombreFichero);
            
            return true;
    
    }
    
    public static void guardarPresupuesto(Id oportunidadId, String estado, String plantilla, String nombreFichero){
        PageReference pdfPage;
        if(estado =='Contrato'){ 
            pdfPage = new PageReference('/apex/'+plantilla);
            pdfPage.getParameters().put('Id', oportunidadId);
            system.debug(oportunidadId); 
        }
        if(estado =='Plan de pagos'){ 
            
            Plan_de_pagos__c planPagos = [SELECT Id, Oportunidad__c FROM Plan_de_pagos__c WHERE Oportunidad__c =: oportunidadId AND Estado__c = 'Activo'];
            
            pdfPage = new PageReference('/apex/'+plantilla);
            system.debug('pdfPage 1:::'+pdfPage);
            pdfPage.getParameters().put('Id', planPagos.Id);
            system.debug(planPagos.Id); 
        }
        guardarPresupuestoSharePoint(pdfPage, oportunidadId, nombreFichero);
        guardarPresupuestoSF(pdfPage, oportunidadId, estado, nombreFichero);
    }

    private static void guardarPresupuestoSF(PageReference pdfPage, Id oportunidadId, String estado, String nombreFichero) {
        ContentVersion cv = new ContentVersion();
        if(estado == 'Contrato') cv.title = nombreFichero + ' ' + oportunidadId;
        cv.PathOnClient = 'file.pdf';
        if(Test.isRunningTest()) cv.VersionData = blob.valueOf('Unit.Test');
        else cv.VersionData = pdfPage.getContentAsPdf();
        insert cv;
        
        ContentVersion cv2 = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE id = :cv.id LIMIT 1];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv2.ContentDocumentId;
        cdl.LinkedEntityId = oportunidadId;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
    }

    private static void guardarPresupuestoSharePoint(PageReference pdfPage, Id oportunidadId, String nombreFichero) {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '');

        // Datos fichero
        String fileNameKey = nombreFichero;
        nombreFichero += ' ' + oportunidadId;

        // Obtenemos las categorías para ese tipo de archivo    
        List<String> fileCats = SharePointConnectorMappings.getCatsByFileType(fileNameKey);
        if(fileCats == null) fileCats = new List<String>();

        // Obtenemos los datos de la oportunidad
        Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :oportunidadId];
        
        // Obtenemos la promoción mediante la oportunidad
        String promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(oportunidadId.getSObjectType()).replace('$value$', ':oportunidadId');
        Promocion__c promotion = Database.query(promotionQuery);

        // Preparamos subida a Sharepoint:
        Map<String, String> metaDataMap = new Map<String, String>();
        metaDataMap.put('IdPromocion', promotion.Id);
        metaDataMap.put('IdOportunidad', oportunidadId);
        metaDataMap.put('TipoDocumento', 'Contrato'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
        metaDataMap.put('IdCuenta', opp.AccountId);
        Integer i = 1;
        for(String cat : fileCats) {
            metaDataMap.put('Categoria' + i, cat);
            i++;
        }
        metaDataMap.put('IdUsuario', UserInfo.getUserId());
        metaDataMap.put('Usuario', UserInfo.getUserEmail());

        DocumentCategory__c customDocCategory = null;
        String dirPath = baseDirPath + parentDir + '/' + promotion.Name;
        if(fileCats.size() > 0) {
        	customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
            dirPath += '/' + customDocCategory.ParentDirectoryName__c;
        }

        nombreFichero = SharePointConnectorMappings.getNameByCats(fileCats);
        if(!Test.isRunningTest()) {
            SharePointConnector spConnector = new SharePointConnector(nombreFichero + '.pdf', dirPath, metaDataMap);
            spConnector.login();
            spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
            spConnector.updateFileMetaData();
        }
        SharePointConnector.commitDocumentNumber();
    }

}