force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_vivienda__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_vivienda__c</fullName>
    <label>Tipo de vivienda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_vivienda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Tipo_de_vivienda__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_vivienda__c</fullName>
    <label>Tipo de promoción</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_vivienda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Tipo de inmueble</relationshipLabel>
    <relationshipName>Tipo_de_inmueble</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garaje</fullName>
            </value>
            <value>
                <fullName>Trastero</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Mejoras</fullName>
            </value>
            <value>
                <fullName>Personalizacion</fullName>
                <label>Personalización</label>
            </value>
            <value>
                <fullName>Descuento</fullName>
                <isActive>false</isActive>
                <label>Descuento</label>
            </value>
            <value>
                <fullName>Mobiliario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tipos_de_vivienda.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Libre</fullName>
    </customValue>
    <customValue>
        <fullName>VPO</fullName>
    </customValue>
    <customValue>
        <fullName>VPT</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativa</fullName>
    </customValue>
    <masterLabel>Tipos de vivienda</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BotonPreReserva_Controller.cls
public class BotonPreReserva_Controller {
    
    @AuraEnabled
    public static String getTipoInmueble(Id quoteId){
    	List<QuoteLineItem> productoPresupuestoList = [SELECT Id, QuoteId, Product2.Tipo_de_vivienda__c, Product2.Tipo_de_inmueble__r.Tipo__c 
                                                   			FROM QuoteLineItem 
                                                   			WHERE QuoteId =: quoteId]; 
        
        List<String> tipoInmuebleList = new List<String>();
        for(QuoteLineItem productoPresupuesto : productoPresupuestoList){
            tipoInmuebleList.add(productoPresupuesto.Product2.Tipo_de_inmueble__r.Tipo__c);
        }
        system.debug('tipoInmuebleList:::'+tipoInmuebleList);
        
        if(!tipoInmuebleList.isEmpty()){
            if(tipoInmuebleList.contains('Vivienda')){
                String tipoInmueble = 'Vivienda';
                system.debug('tipoInmueble es:::'+ tipoInmueble);
                return tipoInmueble;
            }else if(tipoInmuebleList.contains('Local')){
                String tipoInmueble = 'Local';
                system.debug('tipoInmueble es:::'+ tipoInmueble);
                return tipoInmueble;
            }else if(tipoInmuebleList.contains('Trastero') && !tipoInmuebleList.contains('Trastero')){
                String tipoInmueble = 'Trastero';
                system.debug('tipoInmueble es:::'+ tipoInmueble);
                return tipoInmueble;                
            }else if(tipoInmuebleList.contains('Garaje') && !tipoInmuebleList.contains('Garaje')){
                String tipoInmueble = 'Garaje';
                system.debug('tipoInmueble es:::'+ tipoInmueble);
                return tipoInmueble ;                
            }
    
        } 
        return null;
    }
    
    @AuraEnabled
    public static String getUrl(){
        String dominio = System.URL.getSalesforceBaseUrl().toExternalForm() + '/'; 
        return (dominio);
    }
    
    @auraEnabled
     public static String getCongaTemplateId(){
        APXTConga4__Conga_Template__c CongaTemplateId = [SELECT Id FROM APXTConga4__Conga_Template__c WHERE APXTConga4__Name__c = 'FichaFormaPagoTemplate'];
        return (CongaTemplateId.Id);
    }   
    

    @AuraEnabled
    public static Boolean generarContrato(Id quoteId, String estado){
    	List<ContentDocumentLink> listaDocumentos = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: quoteId];
        
        Set<id> setIdDocumentos = new Set<id>();
        system.debug('1');
       
        for(integer i = 0; i < listaDocumentos.size(); i++) {
            setIdDocumentos.add(listaDocumentos[i].ContentDocumentId);
        }
        
        List<ContentVersion> listaContenidoDocumentos = [SELECT id FROM ContentVersion WHERE ContentDocumentId IN : setIdDocumentos];
        system.debug('2');

        
        guardarPresupuestoSharepoint(quoteId);
        guardarPresupuesto(quoteId, estado);
            
        return true;
    }
    
    public static void guardarPresupuesto(Id quoteId, String estado){
         
        PageReference pdfPage;
        pdfPage = new PageReference('/apex/VF_Ficha_Forma_pago');
         
        pdfPage.getParameters().put('Id', quoteId);
        system.debug(quoteId);
        
        Id oppId = [SELECT OpportunityId FROM Quote WHERE Id = :quoteId].OpportunityId;

        ContentVersion cv = new ContentVersion();
		cv.title = 'FichaPreReserva ' + quoteId;
         
        cv.PathOnClient = 'file.pdf';
        system.debug('llega aqui');
            if(Test.isRunningTest()){
                
                 cv.VersionData = blob.valueOf('Unit.Test');
            }
            else{
                 system.debug('antes de la llamada');
                 cv.VersionData = pdfPage.getContentAsPdf();
                 system.debug('despues');
            }
           
            
        
        insert cv;
        
        ContentVersion cv2 = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE id = :cv.id LIMIT 1];
        ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv2.ContentDocumentId;
            //cdl.LinkedEntityId = quoteId;
            cdl.LinkedEntityId = oppId;
            cdl.ShareType = 'V';
        

            cdl.Visibility = 'AllUsers';
        
        insert cdl; 
     }

    private static void guardarPresupuestoSharepoint(Id quoteId) {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '');

        String fileNameKey = 'FichaPreReserva';
        String fileName = fileNameKey + ' ' + quoteId;
        PageReference pdfPage;
        pdfPage = new PageReference('/apex/VF_Ficha_Forma_pago');         
        pdfPage.getParameters().put('Id', quoteId);

        // Obtenemos las categorías para ese tipo de archivo    
        List<String> fileCats = SharePointConnectorMappings.getCatsByFileType(fileNameKey);
        if(fileCats == null) fileCats = new List<String>();

        List<Quote> qs = [SELECT Opportunity.Promocion__c FROM Quote WHERE Id = :quoteId];
        if(qs.size() == 1) {
            Promocion__c promo = [SELECT Id,Name FROM Promocion__c WHERE Id = :qs.get(0).Opportunity.Promocion__c];

            // Preparamos subida a Sharepoint:
            Map<String, String> metaDataMap = new Map<String, String>();
            metaDataMap.put('IdPromocion', promo.Id);
            metaDataMap.put('TipoDocumento', 'Archivo'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
            Integer i = 1;
            for(String cat : fileCats) {
                metaDataMap.put('Categoria' + i, cat);
                i++;
            }
            metaDataMap.put('IdUsuario', UserInfo.getUserId());
            metaDataMap.put('Usuario', UserInfo.getUserEmail());

            DocumentCategory__c customDocCategory = null;
            String dirPath = baseDirPath + parentDir + '/' + promo.Name;
            if(fileCats.size() > 0) {
                customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
                dirPath += '/' + customDocCategory.ParentDirectoryName__c;
            }

            fileName = SharePointConnectorMappings.getNameByCats(fileCats);
            if(!Test.isRunningTest()) {
                SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
                spConnector.login();
                spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
                spConnector.updateFileMetaData();
            }
            fileName = SharePointConnectorMappings.getNameByCats(fileCats);
        }
    }

    
}