force-app/main/default/objects/Mejora__c/Mejora__c.object-meta.xml
<CustomObject>
    <label>Mejora</label>
    <nameField>
        <label>Mejoras Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mejoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mejora__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Mejoras</relationshipLabel>
    <relationshipName>Mejoras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MejoraPresupuesto__c/MejoraPresupuesto__c.object-meta.xml
<CustomObject>
    <label>Mejora Presupuesto</label>
    <nameField>
        <label>Mejora Presupuesto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mejoras Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MejoraPresupuesto__c/fields/Mejora__c.field-meta.xml
<CustomField>
    <fullName>Mejora__c</fullName>
    <label>Mejora</label>
    <referenceTo>Mejora__c</referenceTo>
    <relationshipLabel>Mejoras Presupuesto</relationshipLabel>
    <relationshipName>Mejoras_Presupuesto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MejoraPresupuesto__c/fields/Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Presupuesto__c</fullName>
    <label>Presupuesto</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Mejoras Presupuesto</relationshipLabel>
    <relationshipName>Mejoras_Presupuesto</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SelectMejoraQuoteController.cls
public class SelectMejoraQuoteController {

    @AuraEnabled
    public static List<Mejora> getMejoras(Id quoteId) {
        Quote qu = [SELECT Id, Opportunity.Promocion__c FROM Quote WHERE Id = :quoteId LIMIT 1];
        List<Mejora__c> mejoras = new List<Mejora__c>([SELECT Id, Name, Precio__c, Descripcion__c FROM Mejora__c WHERE Promocion__c = :qu.Opportunity.Promocion__c]);

        List<Mejora> response = new List<Mejora>();
        for(Mejora__c m : mejoras) {
            Mejora nm = new Mejora();
            nm.ident = m.Id;
            nm.Name = m.Name;
            nm.Descripcion = m.Descripcion__c;
            nm.Precio = m.Precio__c;
            nm.check = false;
            response.add(nm);
        }
        return response;
    }
    
    @AuraEnabled
    public static void saveMejoras(Id quoteId, List<Mejora> mejoras) {
        List<MejoraPresupuesto__c> toCreate = new List<MejoraPresupuesto__c>();
        
        for(Mejora mj : mejoras)
            if(mj.check){
                MejoraPresupuesto__c mp = new MejoraPresupuesto__c();
                mp.Mejora__c = mj.ident;
                mp.Presupuesto__c = quoteId;
                mp.Name = mj.Name;
                mp.Descripcion__c = mj.Descripcion;
                mp.Precio__c = mj.Precio;
                toCreate.add(mp);
            }
        
        if(!toCreate.isEmpty()) insert toCreate;
    }
    
    public class Mejora {
        @AuraEnabled public Id ident{get;set;}
        @AuraEnabled public String Name{get;set;}
        @AuraEnabled public String Descripcion{get;set;}
        @AuraEnabled public Double Precio{get;set;}
        @AuraEnabled public Boolean check {get;set;} 
    }
    
}