force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnviadoAmlCheck__c.field-meta.xml
<CustomField>
    <fullName>EnviadoAmlCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que permite distinguir los registros que se han enviado correctamente a AMLCHECK</description>
    <label>EnviadoAmlCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Situacion_laboral__c.field-meta.xml
<CustomField>
    <fullName>Situacion_laboral__c</fullName>
    <defaultValue>&quot;SL009&quot;</defaultValue>
    <label>Situación laboral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Situacion_laboral</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <label>CNAE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNAEs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cliente Personal</label>
</RecordType>

force-app/main/default/globalValueSets/Situacion_laboral.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SL001</fullName>
        <label>Trabajador por cuenta ajena</label>
    </customValue>
    <customValue>
        <fullName>SL002</fullName>
        <label>Trabajador por cuenta propia</label>
    </customValue>
    <customValue>
        <fullName>SL003</fullName>
        <label>Labores del Hogar</label>
    </customValue>
    <customValue>
        <fullName>SL004</fullName>
        <label>Desempleado</label>
    </customValue>
    <customValue>
        <fullName>SL005</fullName>
        <label>Rentista</label>
    </customValue>
    <customValue>
        <fullName>SL006</fullName>
        <label>Pensionista</label>
    </customValue>
    <customValue>
        <fullName>SL007</fullName>
        <label>Sin actividad</label>
    </customValue>
    <customValue>
        <fullName>SL008</fullName>
        <label>Funcionario o similar</label>
    </customValue>
    <customValue>
        <fullName>SL009</fullName>
        <default>true</default>
        <label>Otros</label>
    </customValue>
    <masterLabel>Situación laboral</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AMLCheckBatch.cls
/**
@description
<pre>
Manejador para el trigger sobre Account</br>
DATE       	AUTHOR     	DESCRIPTION<br/>
                        Created.  
04/01/2021 	LCS - JZD   Modificado. Cambiada la llamada al método de envioClienteAmlCheck para usar la nueva clase AmlCheckHelper                         
</pre>
@author Leadclic Solutions
@date 04/01/2021
*/
global class AMLCheckBatch implements Database.Batchable<sObject>, Schedulable{
    
    private static final Id CUENTA_PERSONAL  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'PersonAccount');
    private static final Id CUENTA_EMPRESA  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'Cuenta');

    global void execute(SchedulableContext sc){
        //Instancia de la clase.
        AMLCheckBatch b = new AMLCheckBatch();
        Database.executebatch(b, 50);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,Name,FirstName, CNAE__c, CNO__c, Situacion_laboral__c, RecordTypeId, EnviadoAmlCheck__c
                                         FROM Account
                                         WHERE RecordTypeId IN (:CUENTA_PERSONAL, :CUENTA_EMPRESA) AND EnviadoAmlCheck__c = false
                                         AND (CNAE__c != null OR CNO__c != null OR Situacion_laboral__c != null)]);
    }
    
    global void execute(Database.BatchableContext bc, List<Account> accounts){
        List<Id> accsIds = new List<Id>(); 
        for(Account acc: accounts){
            accsIds.add(acc.Id);
        }
       // AmlCheckHelper.envioClienteAmlCheck(accsIds, false);
    }
    
    global void finish(Database.BatchableContext bc){}
   
}