force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DFI_Provincia__c.field-meta.xml
<CustomField>
    <fullName>DFI_Provincia__c</fullName>
    <formula>Localidad_FISCAL__r.Provincia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Pais__c.field-meta.xml
<CustomField>
    <fullName>DP_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_1</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DP - País)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnviadoAmlCheck__c.field-meta.xml
<CustomField>
    <fullName>EnviadoAmlCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que permite distinguir los registros que se han enviado correctamente a AMLCHECK</description>
    <label>EnviadoAmlCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_constitucion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_constitucion__c</fullName>
    <label>Fecha constitución</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nivel_Riesgo_PBC__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Riesgo_PBC__c</fullName>
    <label>Nivel Riesgo PBC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>risk.4.prohibited</fullName>
                <label>Prohibido</label>
            </value>
            <value>
                <fullName>risk.5.direct.high</fullName>
                <label>Alto Directo</label>
            </value>
            <value>
                <fullName>risk.3.high</fullName>
                <label>Alto</label>
            </value>
            <value>
                <fullName>risk.2.medium</fullName>
                <label>Medio</label>
            </value>
            <value>
                <fullName>risk.1.low</fullName>
                <label>Bajo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Respuesta_alta_PBC__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_alta_PBC__c</fullName>
    <label>Respuesta alta PBC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Respuesta_Alta_PBC</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Situacion_laboral__c.field-meta.xml
<CustomField>
    <fullName>Situacion_laboral__c</fullName>
    <defaultValue>&quot;SL009&quot;</defaultValue>
    <label>Situación laboral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Situacion_laboral</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <label>CNAE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNAEs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNAE__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cliente Personal</label>
</RecordType>

force-app/main/default/objects/PropiedadesIntegracion__c/PropiedadesIntegracion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Propiedades integración</description>
    <label>PropiedadesIntegracion</label>
</CustomObject>

force-app/main/default/globalValueSets/Situacion_laboral.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SL001</fullName>
        <label>Trabajador por cuenta ajena</label>
    </customValue>
    <customValue>
        <fullName>SL002</fullName>
        <label>Trabajador por cuenta propia</label>
    </customValue>
    <customValue>
        <fullName>SL003</fullName>
        <label>Labores del Hogar</label>
    </customValue>
    <customValue>
        <fullName>SL004</fullName>
        <label>Desempleado</label>
    </customValue>
    <customValue>
        <fullName>SL005</fullName>
        <label>Rentista</label>
    </customValue>
    <customValue>
        <fullName>SL006</fullName>
        <label>Pensionista</label>
    </customValue>
    <customValue>
        <fullName>SL007</fullName>
        <label>Sin actividad</label>
    </customValue>
    <customValue>
        <fullName>SL008</fullName>
        <label>Funcionario o similar</label>
    </customValue>
    <customValue>
        <fullName>SL009</fullName>
        <default>true</default>
        <label>Otros</label>
    </customValue>
    <masterLabel>Situación laboral</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AmlCheckHelper.cls
/**
@description
<pre>
Clase helper para realizar llamadas al WS de AMLCheck</br>
DATE       	AUTHOR     	DESCRIPTION<br/>
04/01/2021 	LCS - JZD   Created.        
26/03/2021  LCS - JZD   Añadido método para llamar a AML Check a no futuro cuando se invoca desde el batch                  
</pre>
@author Leadclic Solutions
@date 04/01/2021
*/
public class AmlCheckHelper {

    /*private static final Id CUENTA_PERSONAL  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'PersonAccount');
    private static final Id CUENTA_EMPRESA  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'Cuenta');

    @AuraEnabled
    public static String getCurrentProfile() {
        Profile p = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId()];
        return p.Name;
    }

    @AuraEnabled
    public static List<Id> getAmlCheckOldAccounts() {
        Map<Id, Account> accounts = new Map<Id, Account>([SELECT Id,Name,FirstName 
                                                          FROM Account 
                                                          WHERE RecordTypeId IN (:CUENTA_PERSONAL, :CUENTA_EMPRESA) AND EnviadoAmlCheck__c = false AND
                                                          (CNAE__c != null OR CNO__c != null OR Situacion_laboral__c != null)]);
        List<Id> accsIds = new List<Id>(accounts.keySet()); 
        return accsIds;
    }

    @future(callout = true)
    @AuraEnabled
    public static void envioClienteAmlCheckFuture(List<Id> accsIds, Boolean isInsert) {
        envioClienteAmlCheck(accsIds, isInsert);
    }
    
    public static void envioClienteAmlCheck(List<Id> accsIds, Boolean isInsert) {

        PropiedadesIntegracion__c propiedades = PropiedadesIntegracion__c.getInstance();
        AmlCheckClienteWS clienteConnection = new AmlCheckClienteWS();       

        List<Account> cuentas = [SELECT ID, RecordTypeId, Name, FirstName, LastName, Suffix, Tipo_de_documento__c, N_Documento__c, Sexo__pc, 
                                    Nacionalidad__r.Codigo_ISO3__c, Nacionalidad__pr.Codigo_ISO3__c, Pais_nacimiento__pr.Codigo_ISO3__c , 
                                    DP_Pais__r.Codigo_ISO3__c ,Fecha_constitucion__c, PersonBirthdate, 
                                    Situacion_laboral__c, DFI_Provincia__c, CNAE__c, CNO__c, CNAE__r.Codigo__c, CNO__r.Codigo__c
                                  FROM  Account 
                                  WHERE ID IN :accsIds];
        
        List<String> errors = new List<String>();
        List<Account> accs2Upd = new List<Account>();
        AmlCheckClienteWS.AmlCheckParams params;
        for(Account acc : cuentas) {
            try {
                params = new AmlCheckClienteWS.AmlCheckParams(); 
                AmlCheckClienteWS.Respuesta respuesta = new AmlCheckClienteWS.Respuesta();
                String tipoDocumento = '';
                String genero = '';
                
                // Comprobamos campos obligatorios de AML
                if(String.isBlank(acc.CNO__c) && String.isBlank(acc.CNAE__c) && String.isBlank(acc.Situacion_laboral__c)) {
                    errors.add('La cuenta ' + acc.Name + ' (' + acc.Id + ') no tiene relleno al menos uno de los siguientes campos: CNO, CNAE o Sitúación laboral');
                    continue;
                }

                // Se mapea el tipo de documento con la lista de valores de AML-CHECK
                tipoDocumento = AmlCheckClienteWS.docTypeMapping(acc.Tipo_de_documento__c);

                // Se mapea el género con la lista de valores de AML-CHECK
                genero = AmlCheckClienteWS.genderMapping(acc.Sexo__pc);

                // Hacemos la llamada
                System.debug('Se va a proceder a realizar el envío');
                if(acc.RecordTypeId.equals(CUENTA_PERSONAL)) {
                    System.debug('cuenta personal');
                    System.debug(acc.ID);
                    params.orisys = 'ADI-CRM';
                    params.persnume = String.valueOf(acc.ID);
		            params.perscodi = tipoDocumento;
		            params.persiden = acc.N_Documento__c == null ? '' : acc.N_Documento__c;
		            params.apellido1 = acc.LastName;
		            params.apellido2 = acc.Suffix == null ? '' : acc.Suffix;
		            params.nombre = String.isBlank(acc.FirstName) ? acc.LastName : acc.FirstName;
		            params.gender = String.isBlank(genero) ? '' : genero;
		            params.persnaci = acc.Nacionalidad__pr.Codigo_ISO3__c == null ? '' : acc.Nacionalidad__pr.Codigo_ISO3__c;
		            params.persnaci2 = '';
		            params.persnac = acc.Pais_nacimiento__pr.Codigo_ISO3__c == null ? '' : acc.Pais_nacimiento__pr.Codigo_ISO3__c;
		            params.perspais = acc.DP_Pais__r.Codigo_ISO3__c == null ? '' : acc.DP_Pais__r.Codigo_ISO3__c;
		            params.perspais2 = '';
		            params.persfiju = 'F';
		            params.persfnac = acc.PersonBirthdate == null ? '' : String.valueOf(acc.PersonBirthdate);
		            params.usertokenid = '';
                    params.dacosila = acc.Situacion_laboral__c;
                    params.persprof = acc.CNO__r.Codigo__c;
                    params.perscnae = acc.CNAE__r.Codigo__c;

                    // Comprobamos si están rellenos los campos obligatorios
                    checkRequiredParams(params);

                    if(!Test.isRunningTest()) respuesta = clienteConnection.onboardingRBA(params, isInsert);
                    else {
                        System.debug('entra test cuenta personal');
                        respuesta.returnCode = '0';
                        respuesta.returnCodeDescription = 'OK';		
                        respuesta.persiden = '0000001A';
                        respuesta.idalerta = '0';
                        respuesta.idevidencia = '0';
                        respuesta.rbalevel = 'risk.2.medium';
                        respuesta.rbarulecode = '';
                        respuesta.rbarulecodedesc = '';
                        respuesta.manualGlobalRisk = 'risk.2.medium';
                    }
                    System.debug(acc.ID);
                } else {
                    System.debug('Cuenta empresa');
                    params.orisys = 'ADI-CRM';
                    params.persnume = String.valueOf(acc.ID);
                    params.perscodi = tipoDocumento;
		            params.persiden = acc.N_Documento__c == null ? '' : acc.N_Documento__c;
		            params.apellido1 = '';
		            params.apellido2 = '';
		            params.nombre = acc.Name;
		            params.gender = '';
		            params.persnaci = acc.Nacionalidad__r.Codigo_ISO3__c == null ? '' : acc.Nacionalidad__r.Codigo_ISO3__c;
		            params.persnaci2 = '';
		            params.persnac = '';
		            params.perspais = '';
		            params.perspais2 = '';
		            params.persfiju = 'J';
		            params.persfnac = acc.Fecha_constitucion__c == null ? '' : String.valueOf(acc.Fecha_constitucion__c);
		            params.usertokenid = '';
                    params.dacosila = acc.Situacion_laboral__c;
                    params.persprof = acc.CNO__r.Codigo__c;
                    params.perscnae = acc.CNAE__r.Codigo__c;

                    // Comprobamos si están rellenos los campos obligatorios
                    checkRequiredParams(params);

                    if(!Test.isRunningTest()) respuesta = clienteConnection.onboardingRBA(params, isInsert);
                    else {
                        respuesta.returnCode = '0';
                        respuesta.returnCodeDescription = 'OK';		
                        respuesta.persiden = '0000001A';
                        respuesta.idalerta = '0';
                        respuesta.idevidencia = '0';
                        respuesta.rbalevel = 'risk.2.medium';
                        respuesta.rbarulecode = '';
                        respuesta.rbarulecodedesc = '';
                        respuesta.manualGlobalRisk = 'risk.2.medium';
                    }
                }

                if(respuesta != null) {
                    System.debug('Cuenta ' + acc.Name + ' (' + acc.Id + ') insertada en AML');

                    if(String.isNotBlank(respuesta.returnCode)) { 
                        Account cuenta = new Account( 
                            Id = acc.Id,
                            Respuesta_alta_PBC__c = respuesta.returnCode
                        );

                        if(respuesta.returnCode == '2' && cuenta.IsPersonAccount){
                            cuenta.PEP__pc = true;
                        }
                        if (respuesta.returnCode == '0' || respuesta.returnCode == '1' || respuesta.returnCode == '2' || respuesta.returnCode == '3') {
                            cuenta.EnviadoAmlCheck__c = true;
                            if(isInsert){
                                cuenta.Nivel_Riesgo_PBC__c = respuesta.returnCode == '0' ? respuesta.rbalevel : 'risk.2.medium';
                            } else {
                                cuenta.Nivel_Riesgo_PBC__c = respuesta.manualGlobalRisk;
                            }
                            accs2Upd.add(cuenta);
                        }                          
                    }
                }
            } catch(AmlCheckClienteWS.AmlAlreadyExistException e) {
                AmlCheckClienteWS.Respuesta respuesta = AmlCheckClienteWS.getClient(params);
                Account cuenta = new Account(
                    Id = acc.Id,
                    EnviadoAmlCheck__c = true,
                    Respuesta_alta_PBC__c = respuesta.returnCode,
                    Nivel_Riesgo_PBC__c = respuesta.manualGlobalRisk != null ? respuesta.manualGlobalRisk : respuesta.rbalevel
                );
                accs2Upd.add(cuenta);
                continue;
            } catch(AmlCheckClienteWS.AmlNoExistException e) {
                System.debug('No se ha podido enviar la cuenta a AMLCHECK. Error: ' + e.getMessage());
                errors.add(e.getMessage());
                continue;
            } catch(AmlCheckClienteWS.AmlNoExistParamsException e) {
                System.debug('No se ha podido enviar la cuenta a AMLCHECK. Error: ' + e.getMessage());
                errors.add(e.getMessage());
                continue;
            } catch(AmlCheckClienteWS.AmlRequiredParamsException e) {
                System.debug('No se ha podido enviar la cuenta a AMLCHECK. Error: ' + e.getMessage());
                errors.add(e.getMessage());
                continue;
            } catch(CalloutException e) {
                System.debug('No se ha podido enviar la cuenta a AMLCHECK. Error: ' + e.getMessage());
                errors.add(e.getMessage());
                continue;
            } catch( Exception e ) {
                System.debug('No se ha podido enviar la cuenta a AMLCHECK. Error: ' + e.getMessage() + ' | Traza: ' + e.getStackTraceString());
                errors.add(e.getMessage());
                continue;
            }
        }

        if(!accs2Upd.isEmpty()) {
            System.debug('Cuentas a actualizar por inserción en AML: ' + accs2Upd);
            TriggerHandler.bypass('AccountTriggerHandler');
            update accs2Upd;
            TriggerHandler.clearBypass('AccountTriggerHandler');
        }

        if(!errors.isEmpty()) {
            String errorsStr = String.join(errors, '\n\r');
            throw new CalloutException(errorsStr);
        }
    }

    private static void checkRequiredParams(AmlCheckClienteWS.AmlCheckParams params) {
        Boolean condition = String.isBlank(params.persnume) || String.isBlank(params.perscodi) ||
                String.isBlank(params.persiden) || String.isBlank(params.nombre) || String.isBlank(params.persnaci);
        if(params == null) throw new AmlCheckClienteWS.AmlNoExistParamsException('No se han encontrado parámetros');
        else if(condition) throw new AmlCheckClienteWS.AmlRequiredParamsException('Falta alguno de los siguientes párametros obligatorios: PERSNUME, PERSCODI, PERSIDEN, NOMBRE o PERSNACI');
    }*/
}