force-app/main/default/objects/Account/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_postal_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal_FISCAL__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DF_Codigo_postal__c</fullName>
    <label>Código postal_2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Escalera__c.field-meta.xml
<CustomField>
    <fullName>DF_Escalera__c</fullName>
    <label>Escalera_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DF_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_2</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (DF - Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_N_via__c.field-meta.xml
<CustomField>
    <fullName>DF_N_via__c</fullName>
    <label>Nº vía_2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Nombre_via__c</fullName>
    <label>Nombre vía_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Pais__c.field-meta.xml
<CustomField>
    <fullName>DF_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_2</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DF - País)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Puerta__c.field-meta.xml
<CustomField>
    <fullName>DF_Puerta__c</fullName>
    <label>Puerta_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Tipo_de_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Tipo_de_via__c</fullName>
    <label>Tipo de vía_2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DP_Codigo_postal__c</fullName>
    <label>Código postal_1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Escalera__c.field-meta.xml
<CustomField>
    <fullName>DP_Escalera__c</fullName>
    <label>Escalera_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DP_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_1</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_N_via__c.field-meta.xml
<CustomField>
    <fullName>DP_N_via__c</fullName>
    <label>Nº vía_1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DP_Nombre_via__c</fullName>
    <label>Nombre vía_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Pais__c.field-meta.xml
<CustomField>
    <fullName>DP_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_1</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DP - País)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Puerta__c.field-meta.xml
<CustomField>
    <fullName>DP_Puerta__c</fullName>
    <label>Puerta_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Tipo_de_vIa__c.field-meta.xml
<CustomField>
    <fullName>DP_Tipo_de_vIa__c</fullName>
    <label>Tipo de vía_1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Correo electrónico</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Escalera_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Escalera_FISCAL__c</fullName>
    <label>Escalera</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_constitucion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_constitucion__c</fullName>
    <label>Fecha constitución</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Folio__c.field-meta.xml
<CustomField>
    <fullName>Folio__c</fullName>
    <label>Folio</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Localidad_FISCAL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (Localidad)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Movil_empresa__c.field-meta.xml
<CustomField>
    <fullName>Movil_empresa__c</fullName>
    <label>Móvil Empresa</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_Hoja__c.field-meta.xml
<CustomField>
    <fullName>N_Hoja__c</fullName>
    <label>Nº Hoja</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>N_via_FISCAL__c</fullName>
    <label>Nº vía</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_de_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_via_FISCAL__c</fullName>
    <label>Nombre de vía</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Pais_FISCAL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Puerta_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Puerta_FISCAL__c</fullName>
    <label>Puerta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seccion__c.field-meta.xml
<CustomField>
    <fullName>Seccion__c</fullName>
    <label>Sección</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_via_FISCAL__c</fullName>
    <label>Tipo de vía</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tomo__c.field-meta.xml
<CustomField>
    <fullName>Tomo__c</fullName>
    <label>Tomo</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/Comunidad_Autonoma__c.object-meta.xml
<CustomObject>
    <label>Comunidad autónoma</label>
    <nameField>
        <label>Nombre de Comunidad Autónoma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunidades autónomas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Comunidades autónomas</relationshipLabel>
    <relationshipName>Comunidades_autonomas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Tabla que contendrá el detalle de la trazabilidad de las integraciones.</description>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Aplicacion__c.field-meta.xml
<CustomField>
    <fullName>Aplicacion__c</fullName>
    <label>Aplicacion</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Municipio__c/fields/Codigo_municipio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio__c</fullName>
    <label>Código municipio</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <referenceTo>Provincia__c</referenceTo>
    <relationshipName>Municipios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/PropiedadesIntegracion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Propiedades integración</description>
    <label>PropiedadesIntegracion</label>
</CustomObject>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/ILC_IDEALISTA__c.field-meta.xml
<CustomField>
    <fullName>ILC_IDEALISTA__c</fullName>
    <label>ILC_IDEALISTA</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/PasswordAMLCHECK__c.field-meta.xml
<CustomField>
    <fullName>PasswordAMLCHECK__c</fullName>
    <label>PasswordAMLCHECK</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/URL_AMLCHECK__c.field-meta.xml
<CustomField>
    <fullName>URL_AMLCHECK__c</fullName>
    <label>URL_AMLCHECK</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/UsuarioAMLCHECK__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAMLCHECK__c</fullName>
    <label>UsuarioAMLCHECK</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provincia__c/Provincia__c.object-meta.xml
<CustomObject>
    <label>Provincia</label>
    <nameField>
        <label>Nombre de Provincia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provincias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Provincia__c/fields/Comunidad_autonoma__c.field-meta.xml
<CustomField>
    <fullName>Comunidad_autonoma__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comunidad autónoma</label>
    <referenceTo>Comunidad_Autonoma__c</referenceTo>
    <relationshipLabel>Provincias</relationshipLabel>
    <relationshipName>Provincias</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_via.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avenida</fullName>
    </customValue>
    <customValue>
        <fullName>Calle</fullName>
    </customValue>
    <customValue>
        <fullName>Glorieta</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>Bulevar</fullName>
    </customValue>
    <customValue>
        <fullName>Paseo</fullName>
    </customValue>
    <customValue>
        <fullName>Camino</fullName>
    </customValue>
    <customValue>
        <fullName>Carretera</fullName>
    </customValue>
    <masterLabel>Tipo de vía</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DTT_TEST_AmlCheckClienteWS.cls
@IsTest
public with sharing class DTT_TEST_AmlCheckClienteWS {

    /*@TestSetUp
    private static void setUp() {
        CNO__c cnoObj = new CNO__c(
            Codigo__c = '1212',
            Name = 'CNO TEST',
            FullName__c = 'CNO TEST'
        );
        insert cnoObj;

        Pais__c pais = new Pais__c();
        pais.name = 'España';
        pais.Codigo_ISO3__c='ESP';
        insert pais;

        Comunidad_Autonoma__c comunidadAutonoma = new Comunidad_Autonoma__c();
        comunidadAutonoma.name = 'Madrid';
        comunidadAutonoma.Pais__c = pais.id;
        
        insert comunidadAutonoma;

        Provincia__c provincia = new Provincia__c();
        provincia.name = 'Madrid';
        provincia.Codigo__c=8;
        provincia.Comunidad_autonoma__c = comunidadAutonoma.id;
        
        
        insert provincia;

        Municipio__c localidad = new Municipio__c();
        localidad.name = 'Madrid';
        localidad.Codigo_municipio__c = 28;

        localidad.provincia__c = provincia.id;
        
        insert localidad;

        Account cuenta = new Account();
        cuenta.name = 'Cuenta test1';
        cuenta.Movil_empresa__c = '660112233';
        cuenta.Email__c = 'test@test.test';
        cuenta.Tipo_de_documento__c = 'NIF';
        cuenta.N_Documento__c = '00000001A';
        cuenta.AccountSource = 'Caseta';
        cuenta.Nacionalidad__c = pais.Id;
        cuenta.Fecha_constitucion__c = date.newInstance(2018, 3, 13);
        
        //Dirección fiscal
        cuenta.Tipo_de_via_FISCAL__c = 'Calle';
        cuenta.Puerta_FISCAL__c = 'a';
        cuenta.Nombre_de_via_FISCAL__c = 'via';
        cuenta.N_via_FISCAL__c = 4;
        cuenta.Pais_FISCAL__c = pais.Id;
        cuenta.Localidad_FISCAL__c = localidad.Id;
        cuenta.Escalera_FISCAL__c = 'a';
        cuenta.Codigo_postal_FISCAL__c = '23456';
        //Dirección de facturación
        cuenta.DF_Tipo_de_via__c = 'Calle';
        cuenta.DF_Puerta__c = 'a';
        cuenta.DF_Nombre_via__c = 'via';
        cuenta.DF_N_via__c = 4;
        cuenta.DF_Pais__c = pais.Id;
        cuenta.DF_Localidad__c = localidad.Id;
        cuenta.DF_Escalera__c = 'a';
        cuenta.DF_Codigo_postal__c = '23456';
        //Dirección de facturación
        cuenta.DP_Tipo_de_via__c = 'Calle';
        cuenta.DP_Puerta__c = 'a';
        cuenta.DP_Nombre_via__c = 'via';
        cuenta.DP_N_via__c = 4;
        cuenta.DP_Pais__c = pais.Id;
        cuenta.DP_Localidad__c = localidad.Id;
        cuenta.DP_Escalera__c = 'a';
        cuenta.DP_Codigo_postal__c = '23456';
        cuenta.CNO__c = cnoObj.Id;
        
        //
        cuenta.tomo__c = '1';
        cuenta.Seccion__c ='2';
        cuenta.Folio__c ='3';
        cuenta.N_Hoja__c ='4';
        
        AccountTriggerHandler.bypass('AccountTriggerHandler');
        insert cuenta;
        TriggerHandler.clearBypass('AccountTriggerHandler');

        PropiedadesIntegracion__c propiedades = new PropiedadesIntegracion__c(
            UsuarioAMLCHECK__c = 'AVINTIA',
            PasswordAMLCHECK__c = 'Qn5sv8gZ',
            URL_AMLCHECK__c = 'http://test.test.com',
            ILC_IDEALISTA__c = 'ilc1f58c0cc5ad3dd64528c6ae121a8de8a11a8a4f7'
        );
        insert propiedades;
    }

    @IsTest
    private static void testOnboardingOK() {
        Test.StartTest();
        AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
        params.orisys = 'ADI-CRM';
		params.persnume = '001n000000WRzgOAAT';
		params.perscodi = 'F';
		params.persiden = '00000001A';
		params.apellido1 = 'TESTING';
		params.apellido2 = 'TESTING2';
		params.nombre = 'Test';
		params.gender = 'H';
		params.persnaci = 'ESP';
		params.persnaci2 = '';
		params.persnac = 'ESP';
		params.perspais = 'ESP';
		params.perspais2 = '';
		params.persfiju = 'F';
		params.persfnac = '1973-05-17';
		params.usertokenid = '';

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AmlCheckOnboardRequestOK');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'text/xml');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);

        AmlCheckClienteWS service = new AmlCheckClienteWS();
        AmlCheckClienteWS.Respuesta respuesta = service.onboarding(params);

        System.assert(respuesta.returnCode == '0');
        System.assert(respuesta.returnCodeDescription == '');
        System.assert(respuesta.persiden == '11031001');
        System.assert(respuesta.idalerta == '0');
        System.assert(respuesta.idevidencia == '0');
        Test.StopTest();
    }

    @IsTest
    private static void testOnboardingKO() {
        Test.StartTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AmlCheckOnboardRequestOK');
        mock.setStatusCode(500);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);

        AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
        params.orisys = 'ADI-CRM';
		params.persnume = '001n000000WRzgOAAT';
		params.perscodi = 'F';
		params.persiden = '00000001A';
		params.apellido1 = 'TESTING';
		params.apellido2 = 'TESTING2';
		params.nombre = 'Test';
		params.gender = 'H';
		params.persnaci = 'ESP';
		params.persnaci2 = '';
		params.persnac = 'ESP';
		params.perspais = 'ESP';
		params.perspais2 = '';
		params.persfiju = 'F';
		params.persfnac = '1973-05-17';
		params.usertokenid = '';

        AmlCheckClienteWS service = new AmlCheckClienteWS();
        AmlCheckClienteWS.Respuesta respuesta = service.onboarding(params);
        System.assert(respuesta == null);
        Test.StopTest();
    }

    @IsTest
    private static void testOnboadingRBAOK() {
        Test.StartTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AmlCheckOnboardRBARequestOK');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);

        AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
        params.orisys = 'ADI-CRM';
		params.persnume = '001n000000WRzgOAAT';
		params.perscodi = 'F';
		params.persiden = '0000001G';
		params.apellido1 = 'TESTING';
		params.apellido2 = 'TESTING2';
		params.nombre = 'Test';
		params.gender = 'H';
		params.persnaci = 'ESP';
		params.persnaci2 = '';
		params.persnac = 'ESP';
		params.perspais = 'ESP';
		params.perspais2 = '';
		params.persfiju = 'F';
		params.persfnac = '1973-05-17';
		params.usertokenid = '';

        AmlCheckClienteWS service = new AmlCheckClienteWS();
        AmlCheckClienteWS.Respuesta respuesta = service.onboardingRBA(params, true);
        System.assert(respuesta.returnCode == '0');
        System.assert(respuesta.returnCodeDescription == '');
        System.assert(respuesta.persiden == '0000001G');
        System.assert(respuesta.idalerta == '0');
        System.assert(respuesta.idevidencia == '0');
        System.assert(respuesta.rbalevel == 'risk.2.medium');
        Test.StopTest();
    }

    @IsTest
    private static void testOnboadingRBAKO() {
        Test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AmlCheckOnboardRBARequestOK');
        mock.setStatusCode(500);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);

        AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
        params.orisys = 'ADI-CRM';
		params.persnume = '001n000000WRzgOAAT';
		params.perscodi = 'F';
		params.persiden = '0000001G';
		params.apellido1 = 'TESTING';
		params.apellido2 = 'TESTING2';
		params.nombre = 'Test';
		params.gender = 'H';
		params.persnaci = 'ESP';
		params.persnaci2 = '';
		params.persnac = 'ESP';
		params.perspais = 'ESP';
		params.perspais2 = '';
		params.persfiju = 'F';
		params.persfnac = '1973-05-17';
		params.usertokenid = '';

        AmlCheckClienteWS service = new AmlCheckClienteWS();
        AmlCheckClienteWS.Respuesta respuesta = service.onboardingRBA(params, true);
        System.assert(respuesta == null);
        Test.stopTest();
    }

    @IsTest
    private static void testGetClientOK() {
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HttpCalloutMockGetClientOKImpl());
            AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
            params.orisys = 'ADI-CRM';
            params.persnume = '001n000000WRzgOAAT';
            params.perscodi = 'F';
            params.persiden = '0000001G';
            params.apellido1 = 'TESTING';
            params.apellido2 = 'TESTING2';
            params.nombre = 'Test';
            params.gender = 'H';
            params.persnaci = 'ESP';
            params.persnaci2 = '';
            params.persnac = 'ESP';
            params.perspais = 'ESP';
            params.perspais2 = '';
            params.persfiju = 'F';
            params.persfnac = '1973-05-17';
            params.usertokenid = '';
            AmlCheckClienteWS.Respuesta respuesta = AmlCheckClienteWS.getClient(params);
        Test.stopTest();
        System.assert(respuesta.returnCode == '1');
        System.assert(respuesta.returnCodeDescription == 'Screening alert found : 20285');
        System.assert(respuesta.idalerta == '20285');
        System.assert(respuesta.idevidencia == '69083');
        System.assert(respuesta.rbalevel == 'risk.1.low');
    }

    @IsTest
    private static void testGetClientKO() {
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HttpCalloutMockGetClientNoExistKOImpl());
            AmlCheckClienteWS.AmlCheckParams params = new AmlCheckClienteWS.AmlCheckParams();
            params.orisys = 'ADI-CRM';
            params.persnume = '001n000000WRzgOAAT';
            params.perscodi = 'F';
            params.persiden = '0000001G';
            params.apellido1 = 'TESTING';
            params.apellido2 = 'TESTING2';
            params.nombre = 'Test';
            params.gender = 'H';
            params.persnaci = 'ESP';
            params.persnaci2 = '';
            params.persnac = 'ESP';
            params.perspais = 'ESP';
            params.perspais2 = '';
            params.persfiju = 'F';
            params.persfnac = '1973-05-17';
            params.usertokenid = '';
            AmlCheckClienteWS.Respuesta respuesta = AmlCheckClienteWS.getClient(params);
        Test.stopTest();
        System.assert(respuesta.returnCode == '78');
        System.assert(respuesta.returnCodeDescription == 'Error, client does not exit.');
    }

    @IsTest
    public static void testInsertarLog() {
        Id accId = [SELECT Id FROM Account WHERE Name = 'Cuenta test1'].Id;

        String nombreMetodo = 'AltaClientesOnboarding';
        String idCuenta = accId;
        String mensajeEnviado = 'TEST';
        String resultado = 'OK';
        AmlCheckClienteWS.insertarLog(nombreMetodo, idCuenta, mensajeEnviado, resultado);

        Log__c log = [SELECT Id, Aplicacion__c, Name, Identificador__c, MensajeEnviado__c, MensajeRecibido__c FROM Log__c LIMIT 1];
        System.assertEquals('AMLCHECK', log.Aplicacion__c);
        System.assertEquals(nombreMetodo, log.Name);
        System.assertEquals(accId, log.Identificador__c);
        System.assertEquals(mensajeEnviado, log.MensajeEnviado__c);
        System.assertEquals(resultado, log.MensajeRecibido__c);
    }

    @IsTest
    public static void testDocTypeMapping() {
        String type;

        type = AmlCheckClienteWS.docTypeMapping('NIF');
        System.assert(type == 'F');

        type = AmlCheckClienteWS.docTypeMapping('CIF');
        System.assert(type == 'C');

        type = AmlCheckClienteWS.docTypeMapping('NIE');
        System.assert(type == 'N');

        type = AmlCheckClienteWS.docTypeMapping('Pasaporte');
        System.assert(type == 'P');

        type = AmlCheckClienteWS.docTypeMapping('Otro');
        System.assert(type == 'O');
    }

    @IsTest
    public static void testGenderMapping() {
        String gender;
        gender = AmlCheckClienteWS.genderMapping('Hombre');
        System.assert(gender == 'H');

        gender = AmlCheckClienteWS.genderMapping('Mujer');
        System.assert(gender == 'M');

        gender = AmlCheckClienteWS.genderMapping('asdas');
        System.assert(gender == null);
    }

    public class HttpCalloutMockGetClientOKImpl implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String responseBody = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">'+
                                    '<SOAP-ENV:Header/>'+
                                        '<SOAP-ENV:Body>'+
                                            '<ns3:getClientResponse xmlns:ns2="http://www.amlcheck.es/ws/clientbase/v1" xmlns:ns3="http://www.amlcheck.es/ws/client/v1">'+
                                                '<ns2:returnCode>1</ns2:returnCode>'+
                                                '<ns2:returnCodeDescription>Screening alert found : 20285</ns2:returnCodeDescription>'+
                                                '<ns2:persnume>001M000001CbCVQIA3</ns2:persnume>'+
                                                '<ns2:perscodi>P</ns2:perscodi>'+
                                                '<ns2:persiden>5464921</ns2:persiden>'+
                                                '<ns2:idalerta>20285</ns2:idalerta>'+
                                                '<ns2:idevidencia>69083</ns2:idevidencia>'+
                                                '<ns2:rbalevel>risk.1.low</ns2:rbalevel>'+
                                                '<ns2:rbarulecode/>' +
                                                '<ns2:rbarulecodedesc/>' +
                                                '<ns3:pendingScrAlerts>1</ns3:pendingScrAlerts>'+
                                                '<ns3:manualGlobalRisk>risk.1.low</ns3:manualGlobalRisk>'+
                                                '<ns3:higherReasonGroup>1</ns3:higherReasonGroup>'+
                                            '</ns3:getClientResponse>'+
                                        '</SOAP-ENV:Body>'+
                                    '</SOAP-ENV:Envelope>';

            HttpResponse res = new HttpResponse();
            res.setBody(responseBody);
            res.setHeader('Content-Type', 'text/xml');
            res.setStatusCode(200);
            return res;
        }
    }

    public class HttpCalloutMockGetClientNoExistKOImpl implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String responseBody = '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">'+
                                    '<SOAP-ENV:Header/>'+
                                        '<SOAP-ENV:Body>'+
                                            '<ns3:getClientResponse xmlns:ns2="http://www.amlcheck.es/ws/clientbase/v1" xmlns:ns3="http://www.amlcheck.es/ws/client/v1">'+
                                                '<ns2:returnCode>78</ns2:returnCode>'+
                                                '<ns2:returnCodeDescription>Error, client does not exit.</ns2:returnCodeDescription>'+
                                                '<ns2:idalerta>0</ns2:idalerta>'+
                                                '<ns2:idevidencia>0</ns2:idevidencia>'+
                                            '</ns3:getClientResponse>'+
                                        '</SOAP-ENV:Body>'+
                                    '</SOAP-ENV:Envelope>';

            HttpResponse res = new HttpResponse();
            res.setBody(responseBody);
            res.setHeader('Content-Type', 'text/xml');
            res.setStatusCode(200);
            return res;
        }
    }

    public class HttpCalloutMockGetClientKOImpl implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            String responseBody = '';

            HttpResponse res = new HttpResponse();
            res.setBody(responseBody);
            res.setHeader('Content-Type', 'text/xml');
            res.setStatusCode(400);
            return res;
        }
    }*/
}