force-app/main/default/objects/Account/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_postal_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal_FISCAL__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DF_Codigo_postal__c</fullName>
    <label>Código postal_2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DF_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_2</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (DF - Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Nombre_via__c</fullName>
    <label>Nombre vía_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Pais__c.field-meta.xml
<CustomField>
    <fullName>DF_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_2</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DF - País)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Tipo_de_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Tipo_de_via__c</fullName>
    <label>Tipo de vía_2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Pais__c.field-meta.xml
<CustomField>
    <fullName>DP_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_1</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DP - País)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Correo electrónico</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_comercial__c.field-meta.xml
<CustomField>
    <fullName>Estado_comercial__c</fullName>
    <defaultValue>&quot;Cliente Gestión&quot;</defaultValue>
    <label>Estado comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente Gestión</fullName>
                <default>true</default>
                <label>Cliente Gestión</label>
            </value>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Localidad_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Localidad_FISCAL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (Localidad)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Movil_empresa__c.field-meta.xml
<CustomField>
    <fullName>Movil_empresa__c</fullName>
    <label>Móvil Empresa</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>N_via_FISCAL__c</fullName>
    <label>Nº vía</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre_de_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_via_FISCAL__c</fullName>
    <label>Nombre de vía</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroVia2Text__c.field-meta.xml
<CustomField>
    <fullName>NumeroVia2Text__c</fullName>
    <label>Numero Via 2</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroViaFiscalText__c.field-meta.xml
<CustomField>
    <fullName>NumeroViaFiscalText__c</fullName>
    <label>Nº Vía</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Pais_FISCAL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_sociedad__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_sociedad__c</fullName>
    <label>Tipo de sociedad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_sociedad</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tipo_de_via_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_via_FISCAL__c</fullName>
    <label>Tipo de vía</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/Comunidad_Autonoma__c.object-meta.xml
<CustomObject>
    <label>Comunidad autónoma</label>
    <nameField>
        <label>Nombre de Comunidad Autónoma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunidades autónomas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Comunidades autónomas</relationshipLabel>
    <relationshipName>Comunidades_autonomas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Municipio__c/fields/OLDID__c.field-meta.xml
<CustomField>
    <fullName>OLDID__c</fullName>
    <label>OLDID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <referenceTo>Provincia__c</referenceTo>
    <relationshipName>Municipios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO2__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO2__c</fullName>
    <label>Código ISO 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3_num__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3_num__c</fullName>
    <label>Código ISO 3 num</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/OLDID__c.field-meta.xml
<CustomField>
    <fullName>OLDID__c</fullName>
    <label>OLDID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <formula>Promocion__r.Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>País</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Comunidad_autonoma__c.field-meta.xml
<CustomField>
    <fullName>Comunidad_autonoma__c</fullName>
    <formula>Localidad__r.Provincia__r.Comunidad_autonoma__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comunidad autónoma</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/OLDID__c.field-meta.xml
<CustomField>
    <fullName>OLDID__c</fullName>
    <label>OLDID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Promociones</relationshipLabel>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <formula>Localidad__r.Provincia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Provincia__c/Provincia__c.object-meta.xml
<CustomObject>
    <label>Provincia</label>
    <nameField>
        <label>Nombre de Provincia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provincias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Provincia__c/fields/Comunidad_autonoma__c.field-meta.xml
<CustomField>
    <fullName>Comunidad_autonoma__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comunidad autónoma</label>
    <referenceTo>Comunidad_Autonoma__c</referenceTo>
    <relationshipLabel>Provincias</relationshipLabel>
    <relationshipName>Provincias</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_sociedad.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TS01</fullName>
        <label>A. Sociedades anónimas</label>
    </customValue>
    <customValue>
        <fullName>TS02</fullName>
        <label>B. Sociedades de responsabilidad limitada</label>
    </customValue>
    <customValue>
        <fullName>TS03</fullName>
        <label>C. Sociedades colectivas</label>
    </customValue>
    <customValue>
        <fullName>TS04</fullName>
        <label>D. Sociedades comanditarias</label>
    </customValue>
    <customValue>
        <fullName>TS05</fullName>
        <label>E. Comunidades de bienes, herencias yacentes y demás entidades carentes de personalidad jurídica no incluidas expresamente en otras claves</label>
    </customValue>
    <customValue>
        <fullName>TS06</fullName>
        <label>F. Sociedades cooperativas</label>
    </customValue>
    <customValue>
        <fullName>TS07</fullName>
        <label>G. Asociaciones</label>
    </customValue>
    <customValue>
        <fullName>TS08</fullName>
        <label>H. Comunidades de propietarios en régimen de propiedad horizontal</label>
    </customValue>
    <customValue>
        <fullName>TS09</fullName>
        <label>J. Sociedades civiles</label>
    </customValue>
    <customValue>
        <fullName>TS10</fullName>
        <label>P. Corporaciones Locales</label>
    </customValue>
    <customValue>
        <fullName>TS11</fullName>
        <label>Q. Organismos públicos</label>
    </customValue>
    <customValue>
        <fullName>TS12</fullName>
        <label>R. Congregaciones e instituciones religiosas</label>
    </customValue>
    <customValue>
        <fullName>TS13</fullName>
        <label>S. Órganos de la Administración del Estado y de las Comunidades Autónomas</label>
    </customValue>
    <customValue>
        <fullName>TS14</fullName>
        <label>U. Uniones Temporales de Empresas</label>
    </customValue>
    <customValue>
        <fullName>TS15</fullName>
        <label>V. Otros tipos no definidos en el resto de claves registradas en España</label>
    </customValue>
    <customValue>
        <fullName>TS16</fullName>
        <label>N. Entidades extranjeras registradas en España</label>
    </customValue>
    <customValue>
        <fullName>TS17</fullName>
        <label>W. Establecimientos permanentes de entidades no residentes en territorio español.</label>
    </customValue>
    <customValue>
        <fullName>TS18</fullName>
        <label>Otras Entidades europeas registradas en España</label>
    </customValue>
    <customValue>
        <fullName>TS19</fullName>
        <label>Otras Entidades europeas NO registradas en España</label>
    </customValue>
    <customValue>
        <fullName>TS20</fullName>
        <label>Entidades Financieras</label>
    </customValue>
    <masterLabel>Tipo de sociedad</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_de_via.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avenida</fullName>
    </customValue>
    <customValue>
        <fullName>Calle</fullName>
    </customValue>
    <customValue>
        <fullName>Glorieta</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>Bulevar</fullName>
    </customValue>
    <customValue>
        <fullName>Paseo</fullName>
    </customValue>
    <customValue>
        <fullName>Camino</fullName>
    </customValue>
    <customValue>
        <fullName>Carretera</fullName>
    </customValue>
    <masterLabel>Tipo de vía</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GeneradorPDFMejorasControllerTest.cls
@IsTest
public class GeneradorPDFMejorasControllerTest {
    @TestSetup
    public static void makeData(){
        /*CNO__c cnoObj = new CNO__c(
                Codigo__c = '1212',
                Name = 'CNO TEST',
                FullName__c = 'CNO TEST'
        );
        insert cnoObj;*/
        Profile pf1 = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1]; 
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
        Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+RandomId; 
        User user1 =new User(firstname = 'ABC', 
                         lastName = 'XYZ', 
                         email = uniqueName + '@test' + orgId + '.org', 
                         Username = uniqueName + '@test' + orgId + '.org', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = uniqueName.substring(18, 23), 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US', 
                         ProfileId = pf1.Id
                        ); 
        /*Pais__c pais = new Pais__c(Name = 'España', Codigo_ISO2__c = 'ES', Codigo_ISO3__c = 'ESP', OLDID__c = '170', Codigo_ISO3_num__c = 123);
        insert pais;
        Account a = new Account(Name = 'Test', Tipo_de_documento__c = 'NIF', N_Documento__c = '12345678P', 
        AccountSource='PUNTO DE VENTA', Estado_comercial__c='Cliente Gestión', Nacionalidad__c=pais.Id, 
         Tipo_de_sociedad__c='TS01', DP_Pais__c=pais.Id, Tipo_de_via_FISCAL__c='Calle', 
         Nombre_de_via_FISCAL__c='TEST ', N_via_FISCAL__c=1, localidad);*/

         Pais__c pais = new Pais__c(Name = 'España', Codigo_ISO3__c = 'ESP');
        insert pais;

        Comunidad_autonoma__c cAutonoma = new Comunidad_autonoma__c(Name = 'Madrid', Pais__c = pais.Id);
        insert cAutonoma;

        Provincia__c provincia = new Provincia__c(Name = 'Madrid', Comunidad_autonoma__c = cAutonoma.Id);
        insert provincia;

        Municipio__c municipio = new Municipio__c(Name = 'Madrid', Provincia__c = provincia.Id);
        insert municipio;
         Account cuenta = new Account(Name = 'Pepe', Movil_empresa__c = '666666666', Email__c = 'pepeoror@gmail.com', Tipo_de_documento__c = 'NIF', N_Documento__c = '12345678A',
                Tipo_de_via_FISCAL__c = 'Calle', Nombre_de_via_FISCAL__c = 'siefnoerfr', NumeroViaFiscalText__c = '3', Pais_FISCAL__c = pais.Id,
                Localidad_FISCAL__c = municipio.Id, Codigo_postal_FISCAL__c = '12345', DF_Tipo_de_via__c = 'Calle',
                DF_Nombre_via__c = 'siefnoerfr', NumeroVia2Text__c = '3', DF_Pais__c = pais.Id,
                DF_Localidad__c = municipio.Id, DF_Codigo_postal__c = '12345', DP_Tipo_de_via__c = 'Calle',
                DP_Nombre_via__c = 'siefnoerfr', NumeroViaText__c = '3',
                DP_Localidad__c = municipio.Id, DP_Codigo_postal__c = '12345', Nacionalidad__c = pais.Id,
                AccountSource = 'PUNTO DE VENTA', Estado_comercial__c='Cliente Gestión', Tipo_de_sociedad__c='TS01',
                DP_Pais__c = pais.Id);
        insert cuenta;

        PriceBook2 pb = new PriceBook2(Name = 'Pricebook Test', IsActive = true);
        insert pb; 

        

        Tipo_de_inmueble__c tipoInmueble1 = new Tipo_de_inmueble__c(Name = 'Tipo de Inmueble Vivienda Test', Tipo__c = 'Vivienda');
        insert tipoInmueble1;

        Promocion__c promocion2 = TestUtil.getPromocion(date.today(), date.today()+30);

        Opportunity o = new Opportunity(Name = 'Test', Promocion__c = promocion2.Id, StageName = 'Closed Won', CloseDate = Date.today(), AccountId = cuenta.Id, Pricebook2Id = pb.Id);
        insert o;


        Product2 p = new Product2();
        p.Name = 'Vivienda Test';
        p.Estado__c = 'Libre';
        p.Tipo_de_inmueble__c = tipoInmueble1.Id;
        p.Precio__c = 45000;
        p.Promocion__c = promocion2.Id;
        p.Oportunidad__c = o.Id;
        //p.Tipologia_Vivienda_Garaje_Trastero_Local__c = 'Vivienda';
        insert p;  

        PriceBookEntry pbe = new PriceBookEntry();
        pbe.IsActive = true;
        pbe.Pricebook2Id = pb.Id;
        pbe.Product2Id = p.Id;
        pbe.UnitPrice = 1000;
        insert pbe;

        OpportunityLineItem productoOpp = new OpportunityLineItem();
        productoOpp.OpportunityId = o.Id;
        productoOpp.Product2Id = p.Id;
        productoOpp.UnitPrice = 1500;
        productoOpp.Quantity = 1;
        productoOpp.Description = 'Producto 5';
        insert productoOpp;
        
        Mejora__c c = new Mejora__c(Name = 'Test1', Precio__c = 1, MejoraPadre__c=NULL, DescripcionMejora__c='Test Descripcion 1', FechaLimiteContratacion__c = Date.today()+20, Activa__c=TRUE, Promocion__c = promocion2.Id);
        Mejora__c c2 = new Mejora__c(Name = 'Test2', Precio__c = 2, MejoraPadre__c=c.Id, DescripcionMejora__c='Test Descripcion 2', FechaLimiteContratacion__c = Date.today()+20, Activa__c=TRUE, Promocion__c = promocion2.Id);
        Mejora__c c3 = new Mejora__c(Name = 'Test3', Precio__c = 3, MejoraPadre__c=NULL, DescripcionMejora__c='Test Descripcion 33', FechaLimiteContratacion__c = Date.today()+20, Activa__c=TRUE, Promocion__c = promocion2.Id);
        Mejora__c c4 = new Mejora__c(Name = 'Test4', Precio__c = 4, MejoraPadre__c=c3.Id, DescripcionMejora__c='Test Descripcion 4', FechaLimiteContratacion__c = Date.today()+20, Activa__c=TRUE, Promocion__c = promocion2.Id);
        Mejora__c c5 = new Mejora__c(Name = 'Test5', Precio__c = 5, MejoraPadre__c=c4.Id, DescripcionMejora__c='Test Descripcion 5', FechaLimiteContratacion__c = Date.today()+20, Activa__c=TRUE, Promocion__c = promocion2.Id);
        List<Mejora__c> mejorasLst = new List<Mejora__c>{c, c2, c3, c4, c5};
        insert mejorasLst;
        c2.MejoraPadre__c = c.Id;
        c4.MejoraPadre__c = c3.Id;
        c5.MejoraPadre__c = c4.Id;
        update mejorasLst;

        System.debug('c: ' + c);
        System.debug('c2: ' + c2);
        System.debug('c3: ' + c3);
        System.debug('c4: ' + c4);
        System.debug('c5: ' + c5);
        
        
        MejorasViviendas__c mv = new MejorasViviendas__c(Name = 'Test 1', Precio__c = 1, Vivienda__c = p.Id, Mejora__c = c.Id);
        MejorasViviendas__c mv2 = new MejorasViviendas__c(Name = 'Test 2', Precio__c = 1, Vivienda__c = p.Id, Mejora__c = c2.Id);
        MejorasViviendas__c mv3 = new MejorasViviendas__c(Name = 'Test 3', Precio__c = 1, Vivienda__c = p.Id, Mejora__c = c3.Id);
        MejorasViviendas__c mv4 = new MejorasViviendas__c(Name = 'Test 4', Precio__c = 1, Vivienda__c = p.Id, Mejora__c = c4.Id);
        MejorasViviendas__c mv5 = new MejorasViviendas__c(Name = 'Test 5', Precio__c = 1, Vivienda__c = p.Id, Mejora__c = c5.Id);
        List<MejorasViviendas__c> mvLst = new List<MejorasViviendas__c>{mv, mv2, mv3, mv4, mv5};
        insert mvLst;

        MejorasTiposInmueble__c mti = new MejorasTiposInmueble__c(Mejora__c = c.Id, TipoInmueble__c = tipoInmueble1.Id);
        MejorasTiposInmueble__c mti2 = new MejorasTiposInmueble__c(Mejora__c = c2.Id, TipoInmueble__c = tipoInmueble1.Id);
        MejorasTiposInmueble__c mti3 = new MejorasTiposInmueble__c(Mejora__c = c3.Id, TipoInmueble__c = tipoInmueble1.Id);
        MejorasTiposInmueble__c mti4 = new MejorasTiposInmueble__c(Mejora__c = c4.Id, TipoInmueble__c = tipoInmueble1.Id);
        MejorasTiposInmueble__c mti5 = new MejorasTiposInmueble__c(Mejora__c = c5.Id, TipoInmueble__c = tipoInmueble1.Id);
        List<MejorasTiposInmueble__c> mtiLst = new List<MejorasTiposInmueble__c>{mti, mti2, mti3, mti4, mti5};
        insert mtiLst;
        

    }
    @IsTest
    public static void GeneradorPDFMejorasControllerTest(){
        Opportunity o = [SELECT Id, Promocion__c FROM Opportunity LIMIT 1];

        PageReference pageRef = Page.GeneradorPDFMejoras;
        Test.setCurrentPage(pageRef);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(o);
        ApexPages.currentPage().getParameters().put('Id',o.id);

        GeneradorPDFMejorasController controller = new GeneradorPDFMejorasController();
        
    }
}