force-app/main/default/objects/Account/fields/CNO__c.field-meta.xml
<CustomField>
    <fullName>CNO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNO</label>
    <referenceTo>CNO__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Copiar_direccion_2__c.field-meta.xml
<CustomField>
    <fullName>Copiar_direccion_2__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Desmarcar el campo si la domiciliación es diferente a la primera sección</inlineHelpText>
    <label>Copiar dirección</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DF_Codigo_postal__c</fullName>
    <label>Código postal_2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DF_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_2</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (DF - Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_N_piso__c.field-meta.xml
<CustomField>
    <fullName>DF_N_piso__c</fullName>
    <label>Nº piso_2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_N_via__c.field-meta.xml
<CustomField>
    <fullName>DF_N_via__c</fullName>
    <label>Nº vía_2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Nombre_via__c</fullName>
    <label>Nombre vía_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Pais__c.field-meta.xml
<CustomField>
    <fullName>DF_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_2</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DF - País)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Puerta__c.field-meta.xml
<CustomField>
    <fullName>DF_Puerta__c</fullName>
    <label>Puerta_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Tipo_de_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Tipo_de_via__c</fullName>
    <label>Tipo de vía_2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Direcciones_iguales__c.field-meta.xml
<CustomField>
    <fullName>Direcciones_iguales__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Desmarcar el campo si la domiciliación es diferente a la primera sección</inlineHelpText>
    <label>Copiar Dirección</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DP_Codigo_postal__c</fullName>
    <label>Código postal_1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DP_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_1</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_N_piso__c.field-meta.xml
<CustomField>
    <fullName>DP_N_piso__c</fullName>
    <label>Nº piso_1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_N_via__c.field-meta.xml
<CustomField>
    <fullName>DP_N_via__c</fullName>
    <label>Nº vía_1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DP_Nombre_via__c</fullName>
    <label>Nombre vía_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Pais__c.field-meta.xml
<CustomField>
    <fullName>DP_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_1</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DP - País)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Puerta__c.field-meta.xml
<CustomField>
    <fullName>DP_Puerta__c</fullName>
    <label>Puerta_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Tipo_de_vIa__c.field-meta.xml
<CustomField>
    <fullName>DP_Tipo_de_vIa__c</fullName>
    <label>Tipo de vía_1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EnviadoAmlCheck__c.field-meta.xml
<CustomField>
    <fullName>EnviadoAmlCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que permite distinguir los registros que se han enviado correctamente a AMLCHECK</description>
    <label>EnviadoAmlCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_comercial__c.field-meta.xml
<CustomField>
    <fullName>Estado_comercial__c</fullName>
    <defaultValue>&quot;Cliente Gestión&quot;</defaultValue>
    <label>Estado comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente Gestión</fullName>
                <default>true</default>
                <label>Cliente Gestión</label>
            </value>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fecha_constitucion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_constitucion__c</fullName>
    <label>Fecha constitución</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/N_cuenta_corriente__c.field-meta.xml
<CustomField>
    <fullName>N_cuenta_corriente__c</fullName>
    <inlineHelpText>El formato permitido es XX00 0000 0000 00 0000000000</inlineHelpText>
    <label>Nº cuenta corriente</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Sociedad.recordType-meta.xml
<RecordType>
    <fullName>Sociedad</fullName>
    <active>true</active>
    <label>Sociedad Promotora</label>
</RecordType>

force-app/main/default/objects/CNO__c/CNO__c.object-meta.xml
<CustomObject>
    <label>CNO</label>
    <nameField>
        <label>CNO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNOs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CNO__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNO__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Nombre completo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/Comunidad_Autonoma__c.object-meta.xml
<CustomObject>
    <label>Comunidad autónoma</label>
    <nameField>
        <label>Nombre de Comunidad Autónoma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunidades autónomas</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Comunidad_Autonoma__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Comunidades autónomas</relationshipLabel>
    <relationshipName>Comunidades_autonomas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Municipio__c/fields/Codigo_municipio__c.field-meta.xml
<CustomField>
    <fullName>Codigo_municipio__c</fullName>
    <label>Código municipio</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Digito_control__c.field-meta.xml
<CustomField>
    <fullName>Digito_control__c</fullName>
    <label>Dígito de control</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Municipio__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <referenceTo>Provincia__c</referenceTo>
    <relationshipName>Municipios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO2__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO2__c</fullName>
    <label>Código ISO 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3_num__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3_num__c</fullName>
    <label>Código ISO 3 num</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cliente Personal</label>
</RecordType>

force-app/main/default/objects/Provincia__c/Provincia__c.object-meta.xml
<CustomObject>
    <label>Provincia</label>
    <nameField>
        <label>Nombre de Provincia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provincias</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Provincia__c/fields/Comunidad_autonoma__c.field-meta.xml
<CustomField>
    <fullName>Comunidad_autonoma__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comunidad autónoma</label>
    <referenceTo>Comunidad_Autonoma__c</referenceTo>
    <relationshipLabel>Provincias</relationshipLabel>
    <relationshipName>Provincias</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_via.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avenida</fullName>
    </customValue>
    <customValue>
        <fullName>Calle</fullName>
    </customValue>
    <customValue>
        <fullName>Glorieta</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>Bulevar</fullName>
    </customValue>
    <customValue>
        <fullName>Paseo</fullName>
    </customValue>
    <customValue>
        <fullName>Camino</fullName>
    </customValue>
    <customValue>
        <fullName>Carretera</fullName>
    </customValue>
    <masterLabel>Tipo de vía</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TEST_AMLCheckBatch.cls
@isTest
public class TEST_AMLCheckBatch {
    
    private static final Id CUENTA_PERSONAL = SObjectUtils.getRecordTypeId(Account.sObjectType, 'PersonAccount');
    private static final Id CUENTA_EMPRESA = SObjectUtils.getRecordTypeId(Account.sObjectType, 'Cuenta');
    private static final Id CUENTA_SOCIEDAD = SObjectUtils.getRecordTypeId(Account.sObjectType, 'Sociedad');
        
    @isTest
    static void testAltaAccount() {
        System.debug('!!! CUENTA_PERSONAL: ' + CUENTA_PERSONAL);
        System.debug('!!! CUENTA_EMPRESA: ' + CUENTA_EMPRESA);
        
        CNO__c cnoObj = new CNO__c(
                Codigo__c = '1212',
                Name = 'CNO TEST',
                FullName__c = 'CNO TEST'
        );
        insert cnoObj;
        
        Pais__c pais = new Pais__c();
        pais.Name = 'España';
        pais.Codigo_ISO2__c = 'ES';
        pais.Codigo_ISO3__c = 'ESP';
        pais.Codigo_ISO3_num__c = 724;
        insert pais;

        Comunidad_Autonoma__c comunidad = new Comunidad_Autonoma__c();
        comunidad.Codigo__c = 13;
        comunidad.Name = 'Comunidad de Madrid';
        comunidad.Pais__c = pais.ID;
        insert comunidad;
        
        Provincia__c provincia = new Provincia__c ();
        provincia.Codigo__c = 28;
        provincia.Name = 'Madrid';
        provincia.Comunidad_autonoma__c = comunidad.ID;
        insert provincia;
        
        Municipio__c municipio = new Municipio__c();
        municipio.Codigo_municipio__c = 79;
        municipio.Digito_control__c = 6;
        municipio.Name = 'Madrid';
        municipio.Provincia__c = provincia.ID;
        insert municipio;

        //Insertamos la cuenta que vamos testear
        Account account = new Account();
        Account accountPersonaFisica = new Account();
        Account accountPersonaFisicaNIF = new Account();
        Account accountSociedad = new Account();
        //Cuenta de empresa
        account.Name = 'account';
        account.RecordTypeId = CUENTA_EMPRESA;
        account.Tipo_de_documento__c = 'CIF';
        account.N_Documento__c = 'W55968944';
        account.Nacionalidad__c = pais.ID;
        account.DP_Codigo_postal__c = '2800';
        account.CNO__c = cnoObj.Id;
        account.DP_Localidad__c = municipio.id;
        account.DP_N_via__c = 1;
        account.DP_Nombre_via__c = 'prueba';
        account.DP_Pais__c = pais.ID;
        account.DP_Tipo_de_vIa__c = 'Avenida';
        account.Copiar_direccion_2__c = true;
        account.Direcciones_iguales__c = true;
        account.Fecha_constitucion__c = datetime.now().date();
        account.EnviadoAmlCheck__c = false;


        //Cuenta personal con un NIE
        accountPersonaFisica.FirstName = 'accountPersonaFisica';
        accountPersonaFisica.RecordTypeId = CUENTA_PERSONAL;
        accountPersonaFisica.LastName = 'apellidos';
        accountPersonaFisica.PersonEmail = 'correoprueba@correo.es';
        accountPersonaFisica.Tipo_de_documento__c = 'NIE';
        accountPersonaFisica.N_Documento__c = 'X88197732';
        accountPersonaFisica.PersonEmail = 'correo@correo12.es';
        accountPersonaFisica.Profesion__pc = 'profesion';
        accountPersonaFisica.Estado_Civil__pc = 'Soltero/a';
        accountPersonaFisica.PersonMobilePhone = '619282929';
        accountPersonaFisica.Sexo__pc = 'Hombre';
        accountPersonaFisica.Nacionalidad__pc = pais.ID;
        accountPersonaFisica.Pais_nacimiento__pc = pais.ID;
        accountPersonaFisica.AccountSource = 'Web corporativa';
        accountPersonaFisica.PersonBirthdate = datetime.now().date();
        accountPersonaFisica.DF_Tipo_de_via__c = 'Avenida';
        accountPersonaFisica.DF_Pais__c = pais.ID;
        accountPersonaFisica.DF_Nombre_via__c = 'paseo la castellana';
        accountPersonaFisica.DF_Localidad__c = municipio.id;
        accountPersonaFisica.DF_N_via__c = 20;
        accountPersonaFisica.DF_N_piso__c = 5;
        accountPersonaFisica.DF_Puerta__c = 'A';
        accountPersonaFisica.N_cuenta_corriente__c = 'ES66 2100 0418 40 1234567891';
        accountPersonaFisica.DF_Codigo_postal__c = '28044';
        //Domicilio principal
        accountPersonaFisica.DP_Tipo_de_via__c = 'Avenida';
        accountPersonaFisica.DP_Pais__c = pais.ID;
        accountPersonaFisica.DP_Nombre_via__c = 'paseo la castellana';
        accountPersonaFisica.DP_Localidad__c = municipio.id;
        accountPersonaFisica.DP_N_via__c = 20;
        accountPersonaFisica.DP_N_piso__c = 5;
        accountPersonaFisica.DP_Puerta__c = 'A';
        accountPersonaFisica.DP_Codigo_postal__c = '28044';
        //accountPersonaFisica.CNO__C = cnoObj.Id;
        accountPersonaFisica.EnviadoAmlCheck__c = false;


        //Cuenta personal con un NIF
        accountPersonaFisicaNIF.FirstName = 'accountPersonaFisicaNIF';
        accountPersonaFisicaNIF.RecordTypeId = CUENTA_PERSONAL;
        accountPersonaFisicaNIF.LastName = 'apellidos2';
        accountPersonaFisicaNIF.PersonEmail = 'correoprueba2@correo.es';
        accountPersonaFisicaNIF.Tipo_de_documento__c = 'NIF';
        accountPersonaFisicaNIF.N_Documento__c = '98853536L';
        accountPersonaFisicaNIF.PersonEmail = 'correo1@correo12.es';
        accountPersonaFisicaNIF.Profesion__pc = 'profesion';
        accountPersonaFisicaNIF.Estado_Civil__pc = 'Soltero/a';
        accountPersonaFisicaNIF.PersonMobilePhone = '619282929';
        accountPersonaFisicaNIF.Sexo__pc = 'Mujer';
        accountPersonaFisicaNIF.Nacionalidad__pc = pais.ID;
        accountPersonaFisicaNIF.Pais_nacimiento__pc = pais.ID;
        accountPersonaFisicaNIF.AccountSource = 'Web corporativa';
        accountPersonaFisicaNIF.PersonBirthdate = datetime.now().date();
        accountPersonaFisicaNIF.DF_Tipo_de_via__c = 'Avenida';
        accountPersonaFisicaNIF.DF_Pais__c = pais.ID;
        accountPersonaFisicaNIF.DF_Nombre_via__c = 'paseo la castellana';
        accountPersonaFisicaNIF.DF_Localidad__c = municipio.id;
        accountPersonaFisicaNIF.DF_N_via__c = 20;
        accountPersonaFisicaNIF.DF_N_piso__c = 5;
        accountPersonaFisicaNIF.DF_Puerta__c = 'A';
        accountPersonaFisicaNIF.DF_Codigo_postal__c = '28044';
        //Domicilio principal
        accountPersonaFisicaNIF.DP_Tipo_de_via__c = 'Avenida';
        accountPersonaFisicaNIF.DP_Pais__c = pais.ID;
        accountPersonaFisicaNIF.DP_Nombre_via__c = 'paseo la castellana';
        accountPersonaFisicaNIF.DP_Localidad__c = municipio.id;
        accountPersonaFisicaNIF.DP_N_via__c = 20;
        accountPersonaFisicaNIF.DP_N_piso__c = 5;
        accountPersonaFisicaNIF.DP_Puerta__c = 'A';
        accountPersonaFisicaNIF.DP_Codigo_postal__c = '28044';
        accountPersonaFisicaNIF.CNO__c = cnoObj.Id;
        accountPersonaFisicaNIF.EnviadoAmlCheck__c = false;

        //Cuenta Sociedad
        accountSociedad.Name = 'accountSociedad';
        accountSociedad.RecordTypeId = CUENTA_SOCIEDAD;
        accountSociedad.Tipo_de_documento__c = 'NIE';
        accountSociedad.N_Documento__c = 'X92194653';
        accountSociedad.Estado_comercial__c = 'Cliente Gestión';
        //Domicilio principal
        accountSociedad.DP_Tipo_de_via__c = 'Avenida';
        accountSociedad.DP_Pais__c = pais.ID;
        accountSociedad.DP_Nombre_via__c = 'paseo la castellana';
        accountSociedad.DP_Localidad__c = municipio.id;
        accountSociedad.DP_N_via__c = 23;
        accountSociedad.DP_N_piso__c = 5;
        accountSociedad.DP_Puerta__c = 'A';
        accountSociedad.DP_Codigo_postal__c = '28044';
        accountSociedad.EnviadoAmlCheck__c = false;
        
        insert account;
        insert accountPersonaFisica;
        insert accountPersonaFisicaNIF;
        insert accountSociedad;
        
        Test.startTest();

        AMLCheckBatch btch = new AMLCheckBatch();
        Id batchId = Database.executeBatch(btch);

        // Test schedulable
        String sch = '0 0 23 * * ?'; 
        System.schedule('Test Signaturit Templates', sch, btch);

        Test.stopTest();
    }
    
}