force-app/main/default/objects/Account/fields/Codigo_de_sociedad__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_sociedad__c</fullName>
    <label>Código de sociedad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comision__c/Comision__c.object-meta.xml
<CustomObject>
    <label>Comisión</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Nombre de Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comision__c/fields/ImporteReserva__c.field-meta.xml
<CustomField>
    <fullName>ImporteReserva__c</fullName>
    <description>Importe comisiones por Reserva hasta el momento</description>
    <label>Importe Reserva</label>
    <summarizedField>DetalleComision__c.ImporteReserva__c</summarizedField>
    <summaryFilterItems>
        <field>DetalleComision__c.Tipo__c</field>
        <operation>equals</operation>
        <value>Fija</value>
    </summaryFilterItems>
    <summaryForeignKey>DetalleComision__c.Comision__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Comision__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Mes al que corresponde la comisión</description>
    <label>Mes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que se le concede la comisión</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Comisiones</relationshipLabel>
    <relationshipName>Comisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comision__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Año al que corresponde la comisión</description>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DetalleComision__c/DetalleComision__c.object-meta.xml
<CustomObject>
    <label>Detalle Comisión</label>
    <nameField>
        <displayFormat>DETC-{0000}</displayFormat>
        <label>Nombre de Detalle Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles comisión</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DetalleComision__c/fields/Comision__c.field-meta.xml
<CustomField>
    <fullName>Comision__c</fullName>
    <description>Comisión en la que se engloba cada registro</description>
    <label>Comisión</label>
    <referenceTo>Comision__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <description>Mes en el que se da la comisión</description>
    <label>Mes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Producto de Oportunidad al que está asociada la comisión Fija</description>
    <label>Producto Oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Producto de Oportunidad</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Promoción relacionada</description>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Promoción</relationshipLabel>
    <relationshipName>DetallesComisionPromocion</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Tipo de comisión, Fija (por hito) o Extra (manual)</description>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fija</fullName>
            </value>
            <value>
                <fullName>Extra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que aplica el registro</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Año en el que se da la comisión</description>
    <label>Año</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Years</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Motivo de pérdida</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Proyecto</fullName>
            </value>
            <value>
                <fullName>Ubicación</fullName>
            </value>
            <value>
                <fullName>Financiación</fullName>
            </value>
            <value>
                <fullName>Precio</fullName>
            </value>
            <value>
                <fullName>Fecha de Entrega</fullName>
            </value>
            <value>
                <fullName>Tipología</fullName>
            </value>
            <value>
                <fullName>Tamaño</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <formula>PricebookEntry.Product2.Promocion__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promoción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Apalabrado</fullName>
                <label>Pre-Reservado</label>
            </value>
            <value>
                <fullName>Bloqueado temporalmente</fullName>
                <label>Reserva en gestión</label>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
            <value>
                <fullName>Canje</fullName>
            </value>
            <value>
                <fullName>Apartado</fullName>
            </value>
            <value>
                <fullName>Asociado</fullName>
                <isActive>false</isActive>
                <label>Asociado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/DiasPosventa__c.field-meta.xml
<CustomField>
    <fullName>DiasPosventa__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Días de duración del hito Posventa tras la Fecha Escrituración Real de la oportunidad</description>
    <label>Días Posventa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Socio_Empresa_Promotora__c.field-meta.xml
<CustomField>
    <fullName>Socio_Empresa_Promotora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Socio/Empresa Promotora</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promociones Comercializadas</relationshipLabel>
    <relationshipName>PromocionesComercializadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/RelacionVendedorProductoOportunidad__c.object-meta.xml
<CustomObject>
    <label>Relación Vendedor-Producto Oportunidad</label>
    <nameField>
        <label>Nombre de Relación Vendedor-Producto Opo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relaciones Vendedor-Producto Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/PorcentajeComision__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeComision__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje a aplicar sobre el importe de este producto para este vendedor. Sobre el importe resultante, se aplicará el porcentaje de comisión a conceder</description>
    <label>Porcentaje comisión</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto de oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProductoOportunidad</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/Titular__c.field-meta.xml
<CustomField>
    <fullName>Titular__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si este producto contabiliza en los objetivos de este Vendedor</description>
    <label>Titular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProducto_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendedor__c/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <description>Apellidos del vendedor</description>
    <label>Apellidos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Meses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Enero</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Febrero</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Marzo</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Abril</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Mayo</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Junio</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Julio</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Agosto</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Septiembre</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Octubre</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Noviembre</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>Diciembre</label>
    </customValue>
    <masterLabel>Meses</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Years.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2.022</fullName>
        <label>2022</label>
    </customValue>
    <customValue>
        <fullName>2.023</fullName>
        <label>2023</label>
    </customValue>
    <customValue>
        <fullName>2.024</fullName>
        <label>2024</label>
    </customValue>
    <customValue>
        <fullName>2.025</fullName>
        <label>2025</label>
    </customValue>
    <customValue>
        <fullName>2.026</fullName>
        <label>2026</label>
    </customValue>
    <customValue>
        <fullName>2.027</fullName>
        <label>2027</label>
    </customValue>
    <customValue>
        <fullName>2.028</fullName>
        <label>2028</label>
    </customValue>
    <customValue>
        <fullName>2.029</fullName>
        <label>2029</label>
    </customValue>
    <customValue>
        <fullName>2.030</fullName>
        <label>2030</label>
    </customValue>
    <customValue>
        <fullName>2.021</fullName>
        <label>2021</label>
    </customValue>
    <masterLabel>Años</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TEST_Opportunity.cls
/**
 * Clase test de la clase HL_Opportunity
 *
 * Historial
 * ------------------------------------------------------------------------------------------------------
 *
 *	v1.0		
 */
@isTest
public class TEST_Opportunity {
    
     
    /*@isTest
    static void cambiarEstadoOportunidadInmuebleApartado(){
        TestUtil.getProductoOportunidad();
        Product2 inmueble = [SELECT id, estado__c FROM Product2 WHERE name = 'Inmueble Test' LIMIT 1];
        inmueble.estado__c = 'Apalabrado';
        update inmueble;
        
        //obtener oportunidad
        Test.startTest();
        Opportunity oportunidad = [SELECT Id, StageName, Promocion__r.Socio_Empresa_Promotora__c, Promocion__r.Socio_Empresa_Promotora__r.Codigo_de_sociedad__c FROM Opportunity WHERE name = 'Oportunidad Test' LIMIT 1];
        oportunidad.StageName = 'Cancelada';
		oportunidad.Loss_Reason__c = 'Other';
        update oportunidad;
        
        Product2 inmuebleCambiado = [SELECT id, estado__c FROM Product2 WHERE name = 'Inmueble Test' LIMIT 1];
        System.assertEquals('Libre', inmuebleCambiado.estado__c); 
  		Test.stopTest();
    }*/ //Comentado el metodo
    
    /*
    @isTest
    static void cambiarEstadoOportunidadInmuebleBloqueado(){
        
        Opportunity oportunidad = new Opportunity();
        
        //Generar datos
        TestUtil.getProductoOportunidad();
        
        Product2 inmueble = [SELECT id, estado__c FROM Product2 WHERE name = 'Inmueble Test' LIMIT 1];
        
        inmueble.estado__c = 'Bloqueado';

        update inmueble;
        
        //obtener oportunidad
        Oportunidad = [SELECT id FROM Opportunity WHERE name = 'Oportunidad Test' LIMIT 1];
        
        oportunidad.StageName = 'Cancelada';
		oportunidad.Loss_Reason__c = 'Other';
        
        update oportunidad;
        
        Product2 inmuebleCambiado = [SELECT id, estado__c FROM Product2 WHERE name = 'Inmueble Test' LIMIT 1];
        
        System.assertEquals('Cancelado', inmuebleCambiado.estado__c); 
 
    }
    */
    
    @isTest
    static void recalculoComisionesOpp1(){
        //Promocion
        Promocion__c promocion = TestUtil.getPromocion(date.today(), date.today()+30);
        promocion.DiasPosventa__c = 2;

        //Prodcuto de oportunidad
        OpportunityLineItem producto1 = TestUtil.getProductoOportunidad();
        Product2 prod1 = [SELECT Id, Promocion__c FROM Product2 WHERE Id = :producto1.Product2Id];
        Id opp1 = producto1.OpportunityId;
        prod1.Promocion__c = promocion.Id;
        update prod1;
        
        //Vendedores
        Vendedor__c vendedor = new Vendedor__c();
        vendedor.Name = 'Test';
        vendedor.Apellidos__c = 'Test';
        
        insert vendedor;
        
        //Relacion Vendedor ProductoOportunidad
        RelacionVendedorProductoOportunidad__c productoVendedor = new RelacionVendedorProductoOportunidad__c();
        productoVendedor.Vendedor__c = vendedor.Id;
        productoVendedor.ProductoOportunidad__c = producto1.Id;
        productoVendedor.PorcentajeComision__c = 10;
        productoVendedor.Titular__c = true;
    
        insert productoVendedor;
        
        //comisiones
        Comision__c comision = new Comision__c();
        comision.Vendedor__c = vendedor.Id;
        comision.Mes__c = Date.today().month().format();
        comision.Year__c = '2.021';
        
        insert comision;
        
        Comision__c comision2 = new Comision__c();
        comision2.Vendedor__c = vendedor.Id;
        comision2.Mes__c = Date.today().month().format();
        comision2.Year__c = Date.today().year().format();
        
        insert comision2;
        
        //Detalle comision
        DetalleComision__c detalle1 = new DetalleComision__c();
        detalle1.Vendedor__c = vendedor.Id;
        detalle1.Promocion__c = promocion.Id;
        detalle1.Mes__c = Date.today().month().format();
        detalle1.Year__c = '2.021';
        detalle1.Tipo__c = 'Fija';
        detalle1.ProductoOportunidad__c = producto1.Id;
        detalle1.Comision__c = comision.Id;
        detalle1.ImporteReserva__c = 1000;
        detalle1.ImporteContrato__c = 1000;
        detalle1.ImporteEscrituracion__c = 1000;
        detalle1.ImportePosventa__c = 1000;
        
        insert detalle1;
        
        //Oportunidades
        Opportunity oportunidad1 = [SELECT Id, Name, StageName, Promocion__c, Loss_Reason__c, Fecha_firma_Contrato_Reserva__c, Fecha_firma_Contrato_Compraventa__c, FechaEscrituracionReal__c FROM Opportunity WHERE Id = :opp1 LIMIT 1];
        oportunidad1.Promocion__c = promocion.Id;
        oportunidad1.Fecha_firma_Contrato_Reserva__c = Date.today() - 365;
        oportunidad1.Fecha_firma_Contrato_Compraventa__c = Date.today() - 365;
        oportunidad1.FechaEscrituracionReal__c = Date.today() - 365;
        update oportunidad1;
        
        Test.startTest();
        oportunidad1.StageName = 'Cancelada';
		oportunidad1.Loss_Reason__c = 'Other';
        update oportunidad1;
        Test.stopTest();
        
        List<DetalleComision__c> lDetallesPromo1 = [SELECT Id, Vendedor__c, Promocion__c, Importe__C, Concepto__c, Tipo__c, Mes__c, Year__c, Comision__c 
                                                    FROM DetalleComision__c 
                                                    WHERE Importe__c < 0 AND Mes__c = :Date.today().month().format() AND Year__c = :Date.today().year().format()];
        
        for(DetalleComision__c det : lDetallesPromo1){
            if(det.Vendedor__c == vendedor.Id){
                System.assertEquals(det.Importe__c, -4000);
                System.assertEquals(det.Tipo__c, 'Extra');
                System.assertEquals(det.Concepto__c, 'Cancelación de la oportunidad ' + oportunidad1.Name);
                System.assertEquals(det.Vendedor__c, vendedor.Id);
                System.assertEquals(det.Promocion__c, promocion.Id);
                System.assertEquals(det.Comision__c, comision2.Id);
            }
        }        
           
    }
    
    @isTest
    static void recalculoComisionesOpp2(){
        //Promocion
        Promocion__c promocion = TestUtil.getPromocion(date.today(), date.today()+30);
        
        //Producto de oportunidad
        OpportunityLineItem producto = TestUtil.getProductoOportunidad();
        Product2 prod = [SELECT Id, Promocion__c FROM Product2 WHERE Id = :producto.Product2Id];
        Id opp = producto.OpportunityId;
        prod.Promocion__c = promocion.Id;
		update prod;  
        
        //Vendedores
        Vendedor__c vendedor = new Vendedor__c();
        vendedor.Name = 'Test';
        vendedor.Apellidos__c = 'Test';
        
        insert vendedor;
        
        Vendedor__c vendedor2 = new Vendedor__c();
        vendedor2.Name = 'Test';
        vendedor2.Apellidos__c = 'Test';
        
        insert vendedor2;
        
        //Relacion Vendedor ProductoOportunidad
        RelacionVendedorProductoOportunidad__c productoVendedor1 = new RelacionVendedorProductoOportunidad__c();
        productoVendedor1.Vendedor__c = vendedor.Id;
        productoVendedor1.ProductoOportunidad__c = producto.Id;
        productoVendedor1.PorcentajeComision__c = 10;
        productoVendedor1.Titular__c = true;
        
        insert productoVendedor1;
        
        RelacionVendedorProductoOportunidad__c productoVendedor2 = new RelacionVendedorProductoOportunidad__c();
        productoVendedor2.Vendedor__c = vendedor2.Id;
        productoVendedor2.ProductoOportunidad__c = producto.Id;
        productoVendedor2.PorcentajeComision__c = 10;
        productoVendedor2.Titular__c = true;
        
        insert productoVendedor2;

        //comisiones
        Comision__c comision = new Comision__c();
        comision.Vendedor__c = vendedor.Id;
        comision.Mes__c = Date.today().month().format();
        comision.Year__c = '2.021';
        
        insert comision;
        
        Comision__c comision2 = new Comision__c();
        comision2.Vendedor__c = vendedor2.Id;
        comision2.Mes__c = Date.today().month().format();
        comision2.Year__c = '2.021';
        
        insert comision2;
        
        Comision__c comision3 = new Comision__c();
        comision3.Vendedor__c = vendedor.Id;
        comision3.Mes__c = Date.today().month().format();
        comision3.Year__c = Date.today().year().format();
        
        insert comision3;
        
        Comision__c comision4 = new Comision__c();
        comision4.Vendedor__c = vendedor2.Id;
        comision4.Mes__c = Date.today().month().format();
        comision4.Year__c = Date.today().year().format();
        
        insert comision4;
        
        //Detalles Comision
        DetalleComision__c detalle1 = new DetalleComision__c();
        detalle1.Vendedor__c = vendedor.Id;
        detalle1.Promocion__c = promocion.Id;
        detalle1.Mes__c = Date.today().month().format();
        detalle1.Year__c = '2.021';
        detalle1.Tipo__c = 'Fija';
        detalle1.ProductoOportunidad__c = producto.Id;
        detalle1.Comision__c = comision.Id;
        detalle1.ImporteReserva__c = 1000;
        detalle1.ImporteContrato__c = 1000;
        detalle1.ImporteEscrituracion__c = 0;
        detalle1.ImportePosventa__c = 0;
        
        insert detalle1;  
        
        DetalleComision__c detalle2 = new DetalleComision__c();
        detalle2.Vendedor__c = vendedor2.Id;
        detalle2.Promocion__c = promocion.Id;
        detalle2.Mes__c = Date.today().month().format();
        detalle2.Year__c = '2.021';
        detalle2.Tipo__c = 'Fija';
        detalle2.ProductoOportunidad__c = producto.Id;
        detalle2.Comision__c = comision2.Id;
        detalle2.ImporteReserva__c = 1000;
        detalle2.ImporteContrato__c = 1000;
        detalle2.ImporteEscrituracion__c = 0;
        detalle2.ImportePosventa__c = 0;
        
        insert detalle2;    
        
        //oportunidad
        Opportunity oportunidad= [SELECT Id, Name, StageName, Promocion__c, Loss_Reason__c, Fecha_firma_Contrato_Reserva__c, Fecha_firma_Contrato_Compraventa__c, FechaEscrituracionReal__c FROM Opportunity WHERE Id = :opp LIMIT 1];
        oportunidad.Promocion__c = promocion.Id;
        oportunidad.Fecha_firma_Contrato_Reserva__c = Date.today() - 365;
        oportunidad.Fecha_firma_Contrato_Compraventa__c = Date.today() - 365;
        update oportunidad;
        
        Test.startTest();
        oportunidad.StageName = 'Cancelada';
		oportunidad.Loss_Reason__c = 'Other';
        update oportunidad;
        Test.stopTest();
        
        List<DetalleComision__c> lDetallesPromo2 = [SELECT Id, Vendedor__c, Promocion__c, Importe__C, Concepto__c, Tipo__c, Mes__c, Year__c, Comision__c
                                                    FROM DetalleComision__c 
                                                    WHERE Importe__c < 0 AND Mes__c = :Date.today().month().format() AND Year__c = :Date.today().year().format()];
        
        for(DetalleComision__c det : lDetallesPromo2){
            if(det.Vendedor__c == vendedor.Id){
                System.assertEquals(det.Importe__c, -2000);
                System.assertEquals(det.Tipo__c, 'Extra');
                System.assertEquals(det.Concepto__c, 'Cancelación de la oportunidad ' + oportunidad.Name);
                System.assertEquals(det.Vendedor__c, vendedor.Id);
                System.assertEquals(det.Promocion__c, promocion.Id);
                System.assertEquals(det.Comision__c, comision3.Id);
            
            }else if(det.Vendedor__c == vendedor2.Id){
                System.assertEquals(det.Importe__c, -2000);
                System.assertEquals(det.Tipo__c, 'Extra');
                System.assertEquals(det.Concepto__c, 'Cancelación de la oportunidad ' + oportunidad.Name);
                System.assertEquals(det.Vendedor__c, vendedor2.Id);
                System.assertEquals(det.Promocion__c, promocion.Id);
                System.assertEquals(det.Comision__c, comision4.Id);
            }
        }
    }
}