force-app/main/default/objects/Account/fields/Copiar_direccion_2__c.field-meta.xml
<CustomField>
    <fullName>Copiar_direccion_2__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Desmarcar el campo si la domiciliación es diferente a la primera sección</inlineHelpText>
    <label>Copiar dirección</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Pais__c.field-meta.xml
<CustomField>
    <fullName>DP_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_1</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DP - País)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/EnviadoAmlCheck__c.field-meta.xml
<CustomField>
    <fullName>EnviadoAmlCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que permite distinguir los registros que se han enviado correctamente a AMLCHECK</description>
    <label>EnviadoAmlCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_comercial__c.field-meta.xml
<CustomField>
    <fullName>Estado_comercial__c</fullName>
    <defaultValue>&quot;Cliente Gestión&quot;</defaultValue>
    <label>Estado comercial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente Gestión</fullName>
                <default>true</default>
                <label>Cliente Gestión</label>
            </value>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Descartado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/N_cuenta_corriente__c.field-meta.xml
<CustomField>
    <fullName>N_cuenta_corriente__c</fullName>
    <inlineHelpText>El formato permitido es XX00 0000 0000 00 0000000000</inlineHelpText>
    <label>Nº cuenta corriente</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais_FISCAL__c.field-meta.xml
<CustomField>
    <fullName>Pais_FISCAL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (País)</relationshipLabel>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Cliente Personal</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
@description
<pre>
Manejador para el trigger sobre Account</br>
DATE       	AUTHOR     	DESCRIPTION<br/>
                        Created.  
04/01/2021 	LCS - JZD   Modificado. Refactorización para evitar queries dentro de bucles. Se sacan los métodos de AMLCheck a una nueva clase                         
</pre>
@author Leadclic Solutions
@date 04/01/2021
*/
public class AccountTriggerHandler extends TriggerHandler {  
    private static final Id CUENTA_PERSONAL  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'PersonAccount');
    private static final Id CUENTA_EMPRESA  = SObjectUtils.getRecordTypeId(Account.sObjectType, 'Cuenta');


    protected override void beforeInsert() {
        System.debug('Se ejecuta beforeInsert de AccountTrigger');
        //before();
    }

    protected override void beforeUpdate() {
        System.debug('Se ejecuta beforeUpdate de AccountTrigger');
        //before();
    }

    protected override void before() {
        System.debug('Account Trigger sin AML');
        boolean resultado1;
        boolean resultado2;
        boolean resultado3;

        //Se busca el pais españa para saber la nacionalidad
        List <Pais__c> pais = [SELECT ID FROM Pais__c WHERE Codigo_ISO3__c = :'ESP'];

        for(Account acc : (List<Account>) Trigger.New) {
            if(acc.RecordTypeId.equals(CUENTA_PERSONAL) || acc.RecordTypeId.equals(CUENTA_EMPRESA)) {
                if(pais != null && !pais.isEmpty() && (acc.Nacionalidad__c == pais.get(0).ID || acc.Nacionalidad__pc==pais.get(0).ID) && 
                    (acc.Tipo_de_documento__c != null && acc.Tipo_de_documento__c != '' && acc.Tipo_de_documento__c != 'Pasaporte' && 
                        acc.Tipo_de_documento__c != 'Nº Contribuyente' && acc.Tipo_de_documento__c != 'Otros' && 
                        acc.N_Documento__c != null && acc.N_Documento__c != '')) { 

                    resultado1 = ValidadorTriggerNIFHandler.validateNIFEmpresa(acc.N_Documento__c);
                    if (resultado1) {
                        resultado2 = ValidadorTriggerNIFHandler.validateNIFpersona(acc.N_Documento__c);
                        if (resultado1 && !resultado2) {
                            resultado3 = ValidadorTriggerNIFHandler.validateNIE(acc.N_Documento__c);
                            if (resultado1 && !resultado2 && !resultado3 && !System.Test.isRunningTest()){
                                acc.addError('El NIF/CIF o NIE introducido no es válido, por favor revíselo');
                            }
                        }
                    }
                
                }

                //Realizamos la validacion de la cuenta bancaria
                if(acc.N_cuenta_corriente__c != null && !String.isBlank(acc.N_cuenta_corriente__c)) {   
                    if(acc.N_cuenta_corriente__c.substring(0,2).isAlpha()) { //&& acc.N_cuenta_corriente__c.substring(0,2).equals('ES')) {
                        /*boolean validacion= ValidadorUtil.esCuentaBancaria(acc.N_cuenta_corriente__c);
                        if(!validacion && !System.Test.isRunningTest()) {
                        acc.addError('El Nº de cuenta no es válido, por favor revíselo');
                        }*/
                        if(!IBANValidation.validateIban(acc.N_cuenta_corriente__c) && !Test.isRunningTest())
                            acc.addError('El Nº de cuenta no es válido, por favor revíselo');
                    } else {
                        acc.addError('El Nº de cuenta no tiene el IBAN correctamente informado, por favor revíselo');
                    }
                }
            } else {
                if((acc.Copiar_direccion_2__c==false && acc.Pais_FISCAL__c!=null && acc.Pais_FISCAL__c == pais.get(0).ID) || (acc.Copiar_direccion_2__c==true && acc.DP_Pais__c!=null && acc.DP_Pais__c == pais.get(0).ID))
                 {
                    if(acc.Tipo_de_documento__c!=null && acc.Tipo_de_documento__c!='' && acc.Tipo_de_documento__c!= 'Pasaporte' && acc.Tipo_de_documento__c!= 'Nº Contribuyente'&&acc.Tipo_de_documento__c!= 'Otros'&& acc.N_Documento__c!=null && acc.N_Documento__c!='')
                    {
                        resultado1 = ValidadorTriggerNIFHandler.validateNIFEmpresa(acc.N_Documento__c);
                        if (resultado1) {
                            
                            resultado2 = ValidadorTriggerNIFHandler.validateNIFpersona(acc.N_Documento__c);
                            if (resultado1 && !resultado2){
                                
                                resultado3 = ValidadorTriggerNIFHandler.validateNIE(acc.N_Documento__c);
                                if (resultado1 && !resultado2 && !resultado3){
                                    if(!System.Test.isRunningTest()){
                                        acc.addError('El NIF/CIF o NIE introducido no es válido, por favor revíselo');
                                    }
                                }
                            }
                        }
                    }

                 }
            }            
        }

    }

    /*public override void afterInsert() {
        Set<Id> accsIds = new Set<Id>();
        List<Id> accsIdsList = new List<Id>();
        for(Account acc : (List<Account>) Trigger.New) {
            Boolean allowedRecordTypes = acc.RecordTypeId.equals(CUENTA_EMPRESA) || acc.RecordTypeId.equals(CUENTA_PERSONAL);
            if(allowedRecordTypes && !acc.EnviadoAmlCheck__c) accsIds.add(acc.Id);
        }
        accsIdsList.addAll(accsIds);

        if(!accsIdsList.isEmpty()) AmlCheckHelper.envioClienteAmlCheckFuture(accsIdsList, true);
    }

    public override void afterUpdate() {
        Map<Id, Account> oldMap = (Map<Id, Account>) Trigger.OldMap;
        Map<Id, Account> newMap = (Map<Id, Account>) Trigger.NewMap;
        Set<Id> accsIds = new Set<Id>();
        List<Id> accsIdsList = new List<Id>();
        for(Account acc : (List<Account>) Trigger.New) {
            Boolean allowedRecordTypes = acc.RecordTypeId.equals(CUENTA_EMPRESA) || acc.RecordTypeId.equals(CUENTA_PERSONAL);
            Boolean changedStatus = oldMap.get(acc.Id).Estado_comercial__c != newMap.get(acc.Id).Estado_comercial__c;
            if(allowedRecordTypes && acc.EnviadoAmlCheck__c && changedStatus) accsIds.add(acc.Id);
        }
        accsIdsList.addAll(accsIds);

        if(!accsIdsList.isEmpty()) AmlCheckHelper.envioClienteAmlCheckFuture(accsIdsList, false);
    }*/



}