force-app/main/default/objects/Account/fields/DF_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DF_Codigo_postal__c</fullName>
    <label>Código postal_2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Escalera__c.field-meta.xml
<CustomField>
    <fullName>DF_Escalera__c</fullName>
    <label>Escalera_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DF_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_2</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas (DF - Municipio)</relationshipLabel>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_N_piso__c.field-meta.xml
<CustomField>
    <fullName>DF_N_piso__c</fullName>
    <label>Nº piso_2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_N_via__c.field-meta.xml
<CustomField>
    <fullName>DF_N_via__c</fullName>
    <label>Nº vía_2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Nombre_via__c</fullName>
    <label>Nombre vía_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Pais__c.field-meta.xml
<CustomField>
    <fullName>DF_Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País_2</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas (DF - País)</relationshipLabel>
    <relationshipName>Cuentas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Provincia__c.field-meta.xml
<CustomField>
    <fullName>DF_Provincia__c</fullName>
    <formula>DF_Localidad__r.Provincia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Puerta__c.field-meta.xml
<CustomField>
    <fullName>DF_Puerta__c</fullName>
    <label>Puerta_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DF_Tipo_de_via__c.field-meta.xml
<CustomField>
    <fullName>DF_Tipo_de_via__c</fullName>
    <label>Tipo de vía_2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion_Extranjera_F__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Extranjera_F__c</fullName>
    <inlineHelpText>Indique la Dirección Extranjera COMPLETA en este campo.</inlineHelpText>
    <label>Dirección Extranjera_2</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Sociedad.recordType-meta.xml
<RecordType>
    <fullName>Sociedad</fullName>
    <active>true</active>
    <label>Sociedad Promotora</label>
</RecordType>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente Empresa, Cliente Personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas (Cliente)</relationshipLabel>
    <relationshipName>FacturasCliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Codigo_Impuesto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Impuesto__c</fullName>
    <label>Código Impuesto</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_de_emision__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emision__c</fullName>
    <label>Fecha factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Numero_de_factura__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_factura__c</fullName>
    <label>Número de factura</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Participante__c.field-meta.xml
<CustomField>
    <fullName>Participante__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participante</label>
    <referenceTo>Participante__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Porcentaje_de_participacion__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_participacion__c</fullName>
    <label>Porcentaje de participación</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sociedad</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad Cooperativa</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad Promotora</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Tipo_de_linea__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_linea__c</fullName>
    <label>Tipo de línea</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venta de Inmueble</fullName>
            </value>
            <value>
                <fullName>Reserva de Inmueble</fullName>
            </value>
            <value>
                <fullName>Depósito</fullName>
            </value>
            <value>
                <fullName>Entrega a cuenta</fullName>
            </value>
            <value>
                <fullName>Aportaciones Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_factura__c/Linea_de_factura__c.object-meta.xml
<CustomObject>
    <label>Línea de factura</label>
    <nameField>
        <label>Línea de factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Líneas de factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_factura__c/fields/DescripcionLinea__c.field-meta.xml
<CustomField>
    <fullName>DescripcionLinea__c</fullName>
    <label>DescripcionLinea</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Linea_de_factura__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Líneas de factura</relationshipLabel>
    <relationshipName>Lineas_de_factura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_factura__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Acumulado_de_Importe_Pagado__c.field-meta.xml
<CustomField>
    <fullName>Acumulado_de_Importe_Pagado__c</fullName>
    <inlineHelpText>Los depósitos (Reserva sin IVA) no se contabilizan en este campo</inlineHelpText>
    <label>Acumulado de Importe Pagado</label>
    <summarizedField>Factura__c.Importe__c</summarizedField>
    <summaryFilterItems>
        <field>Factura__c.Tipo_de_factura__c</field>
        <operation>equals</operation>
        <value>RESERVAS, FACTURA DE VENTA, ENTREGAS A CUENTA, MEJORAS</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Factura__c.Estado_de_la_factura__c</field>
        <operation>equals</operation>
        <value>Cobrada</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Factura__c.ImpagoAsociado__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Factura__c.Oportunidad__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participante__c/Participante__c.object-meta.xml
<CustomObject>
    <label>Participante</label>
    <nameField>
        <label>Nombre de Participante de la compra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participante__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Participantes (Opportunity)</relationshipLabel>
    <relationshipName>Participantes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participante__c/fields/Porcentaje_de_participacion__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_participacion__c</fullName>
    <label>Porcentaje de participación</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Promociones</relationshipLabel>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_via.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avenida</fullName>
    </customValue>
    <customValue>
        <fullName>Calle</fullName>
    </customValue>
    <customValue>
        <fullName>Glorieta</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>Bulevar</fullName>
    </customValue>
    <customValue>
        <fullName>Paseo</fullName>
    </customValue>
    <customValue>
        <fullName>Camino</fullName>
    </customValue>
    <customValue>
        <fullName>Carretera</fullName>
    </customValue>
    <masterLabel>Tipo de vía</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Documento_factura_controller.cls
/*
 * 		Date 		Author		Description
 * 14/07/2021 		LCS-GMC		Modified.Add method "getEntregaCuenta" line 267, modify line 64.
*/

public class Documento_factura_controller {

	public Map <id, String>				MapaParticipantesOpp{get; set;}
	public List<Account>				listaClientes {get; set;}
	public List<Linea_de_factura__c>	lineasFacturaList {get;set;}

	public Account						cliente {get; set;}
	public Account						sociedad {get; set;}
	public Opportunity					oportunidad {get; set;}
	public Factura__c					factura {get; set;}

	public String						NombreLocalidad {get; set;}
	public String						NombrePais {get; set;}
	public String						fechaCreacion {get; set;}

	public Decimal						importeConIva {get; set;}
	public Decimal						IVA {get;set;}
	public Decimal						importeIVA {get;set;}
    
    public Boolean 						isFacturaEscrituracion {get; set;}
    public String 						TotalImporteEscr {get;set;}
    public String 						TotalCobradoImporteEscr {get;set;}
    
    //Variables importe formateadas
    public String StrFacturaImporte {get;set;}
    public String StrDescripcion {get;set;}
    public String StrImporte {get;set;}
    public String StrCodigoImpuesto {get;set;}
    public String StrFacturaImporteIVA {get;set;}
    public String StrFacturaImporteConIVA {get;set;}
    public Map<Id, List<String>> MapFacturas {get;set;}
    

	public Documento_factura_controller(){

		Id idFactura = ApexPages.currentPage().getParameters().get('id'); system.debug('TEST idFactura ' +idFactura);

		factura = [ SELECT  id,
							name,
							sociedad__c, 
							cliente__c, 
							Numero_de_factura__c, 
							CreatedDate, 
							descripcion__c,
							Codigo_Impuesto__c, 
                   			Fecha_de_emision__c,
							Importe__c,
							Oportunidad__r.Promocion__r.Name,
                   			Oportunidad__r.Amount,
                   			Oportunidad__r.Acumulado_de_Importe_Pagado__c
					FROM Factura__c 
					WHERE id =: idFactura];
        
        List <String> formateo = new String[]{'0', 'number', '###.###.##0,00'};
        
        if(factura.name != null && factura.name.contains('Escrituración')){
            isFacturaEscrituracion = true;
            TotalImporteEscr = String.format(factura.Oportunidad__r.Amount.format(), formateo) + ' €';
            TotalCobradoImporteEscr = String.format(getEntregaCuenta(idFactura).format(), formateo) + ' €';
            //TotalCobradoImporteEscr = String.format(factura.Oportunidad__r.Acumulado_de_Importe_Pagado__c.format(), formateo) + ' €';
        } 
        
        getListaClientes();
		getLineasFacturaList();
		getSociedad();
		getLocalidad();
		getPais();
		getFechaCreacion();
		getImporteIVA();
		getImporteConIVA();
        
        //Formateamos campos de importe
        //
        if(factura.Importe__c != null){
           		StrFacturaImporte = String.format(factura.Importe__c.format(), formateo) + ' €' ;
           	}
        if(factura.Codigo_Impuesto__c != null){
            StrCodigoImpuesto = String.format(factura.Codigo_Impuesto__c.format(), formateo) + ' %' ;
        }

	}

	public void getListaClientes(){

		List <Participante__c> listaParticipantes = [SELECT Id, 
															Cliente__c, 
															Porcentaje_de_participacion__c 
													FROM Participante__c 
													WHERE Opportunity__r.Id =: factura.Oportunidad__r.Id];

		MapaParticipantesOpp = new Map <id, String>();
        
		List <String> formateo = new String[]{'0', 'number', '###.###.##0,00'};
    
		for(Participante__c participante : listaParticipantes){
            if(participante.Porcentaje_de_participacion__c != null){
           	String Strparticipacion = String.format(participante.Porcentaje_de_participacion__c.format(), formateo) + ' %' ;
			MapaParticipantesOpp.put(participante.Cliente__c, Strparticipacion);
            }
		}

		Set<Id> accsIds = new Set<Id>();
		for(Participante__c participante : listaParticipantes){
			accsIds.add(participante.Cliente__c);
		}

		listaClientes = [SELECT Id,
								Name,  
								PersonTitle, 
								Tipo_de_documento__c, 
								N_Documento__c, 
								DF_N_piso__c, 
								DF_Puerta__c, 
								DF_Escalera__c, 
								DF_Codigo_postal__c, 
								DF_Provincia__c, 
								DF_Pais__r.Name,
								DF_Pais__r.Codigo_ISO3__c, 
								DF_Tipo_de_via__c, 
								DF_Nombre_via__c, 
								DF_N_via__c, 
								Phone, 
								DF_Localidad__c, 
								Direccion_Extranjera_F__c 
						FROM Account
						WHERE Id IN :accsIds];
        
	}

	public void getLineasFacturaList(){
		
		lineasFacturaList = [SELECT id, 
									Importe__c, 
									DescripcionLinea__c
							 FROM Linea_de_factura__c 
							 WHERE Factura__c =: factura.Id];

		//system.debug('Entra en getLineasFactura ' + lineasFacturaList);
		
		List <String> formateo = new String[]{'0', 'number', '###.###.##0,00'};
          	//Formateamos campos de importe
           	        
        List<String> FacturaAux= new List <String>();
        MapFacturas = new Map<Id, List<String>>();
        
        for(integer i = 0; i < lineasFacturaList.size() ; i++){
            StrDescripcion =  '#@#VACIO#@#';
            StrImporte = '#@#VACIO#@#';
            
            FacturaAux = new List <String>();
            if(lineasFacturaList[i].DescripcionLinea__c!=null){
            	StrDescripcion = lineasFacturaList[i].DescripcionLinea__c;
            }
            if(lineasFacturaList[i].Importe__c!=null){
            	StrImporte = String.format(lineasFacturaList[i].Importe__c.format(), formateo);
            }
            
           	FacturaAux.add(StrDescripcion);
            FacturaAux.add(StrImporte);
            MapFacturas.put(lineasFacturaList[i].Id, FacturaAux);
        }
        
	}

	public void getSociedad(){
		
		 sociedad = [SELECT id, 
							name, 
							Tipo_de_documento__c,
							N_Documento__c , 
							DF_Tipo_de_via__c, 
							DF_Nombre_via__c, 
							DF_N_via__c, Phone, 
							DF_Codigo_postal__c,
							DF_Localidad__c, 
							DF_Provincia__c, 
							DF_Pais__c
					 FROM Account 
					 WHERE Id =: factura.sociedad__c];

		//system.debug('Entra en getSociedad ' + sociedad);
	}

	public void getLocalidad(){

		Municipio__c localidad = [  SELECT name 
									FROM Municipio__c 
									WHERE id =: sociedad.DF_Localidad__c LIMIT 1];        
		NombreLocalidad = localidad.name;

		//system.debug('Entra en getLocalidad '+ localidad);
	}

	public void getPais(){

		Pais__c pais = [SELECT  name, 
								Codigo_ISO3__c 
						FROM Pais__c 
						WHERE id =: sociedad.DF_Pais__c LIMIT 1];
		NombrePais = pais.name;

		//system.debug('Entra en getPais ' + pais);
	}

	public void getFechaCreacion(){
        if(factura != null && factura.Fecha_de_emision__c  != null) {
            fechaCreacion = factura.Fecha_de_emision__c.day()+' de '+getMes(factura.Fecha_de_emision__c.month())+' del año '+factura.Fecha_de_emision__c.year();
        } else {
            fechaCreacion = datetime.now().day()+' de '+getMes(datetime.now().month())+' del año '+datetime.now().year();
        }
	}

	public String getMes(Integer mes){
		
		String nombreMes;
		if(mes == 1){nombreMes = 'Enero'; }
		else if(mes == 2){nombreMes = 'Febrero';}
		else if(mes == 3){nombreMes = 'Marzo';}
		else if(mes == 4){nombreMes = 'Abril';}
		else if(mes == 5){nombreMes = 'Mayo';}
		else if(mes == 6){nombreMes = 'Junio';}
		else if(mes == 7){nombreMes = 'Julio';}
		else if(mes == 8){nombreMes = 'Agosto';}
		else if(mes == 9){nombreMes = 'Septiembre';}
		else if(mes == 10){nombreMes = 'Octubre';}
		else if(mes == 11){nombreMes = 'Noviembre';}
		else if(mes == 12){nombreMes = 'Diciembre';}
		return nombreMes;
	}
	
	public void getImporteIVA(){
		
		if(factura.Codigo_Impuesto__c != null){
			IVA = factura.Codigo_Impuesto__c;
		}else{
			IVA = 0;
		} 
		
		importeIVA = factura.Importe__c * iva*0.01;
        
        
        List <String> formateo = new String[]{'0', 'number', '###.###.##0,00'};
        //Formateamos campos de importe
        if(importeIVA != null){
       			StrFacturaImporteIVA = String.format(importeIVA.format(), formateo) + ' €';
       		}
        System.debug('Prueba StrFacturaImporteIVA:::'+StrFacturaImporteIVA);
        //System.debug('Codigo Impuesto' + factura.Codigo_Impuesto__c);
	}

	Public void getImporteConIVA(){
		importeConIVA = factura.Importe__c + importeIVA;
        List <String> formateo = new String[]{'0', 'number', '###.###.##0,00'};
        //Formateamos campos de importe
        if(importeConIVA != null){
       			StrFacturaImporteConIVA = String.format(importeConIVA.format(), formateo) + ' €';
       		}
        System.debug('Prueba StrFacturaImporteConIVA:::'+StrFacturaImporteConIVA);
	}
    
    
        Public Double getEntregaCuenta(Id idFactura){
        Double entregaCuenta = 0;
        list<Linea_de_factura__c> listaLineasFactura = [SELECT Id, Importe__c FROM Linea_de_factura__c where Factura__c =: idFactura AND Tipo_de_linea__c = 'Entrega a cuenta'];
        if (listaLineasFactura.size()>0){
            for (Integer i =0; i<listaLineasFactura.size(); i++){
                if (listaLineasFactura[i].Importe__c!=null){
                    entregaCuenta += listaLineasFactura[i].Importe__c;
                }
            }
        }
        if (entregaCuenta<0){
        	entregaCuenta = entregaCuenta *(-1);
        }
        return entregaCuenta;
    }
}