force-app/main/default/objects/Account/fields/DP_Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>DP_Codigo_postal__c</fullName>
    <label>Código postal_1</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Localidad__c.field-meta.xml
<CustomField>
    <fullName>DP_Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad_1</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_N_via__c.field-meta.xml
<CustomField>
    <fullName>DP_N_via__c</fullName>
    <label>Nº vía_1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Nombre_via__c.field-meta.xml
<CustomField>
    <fullName>DP_Nombre_via__c</fullName>
    <label>Nombre vía_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Provincia__c.field-meta.xml
<CustomField>
    <fullName>DP_Provincia__c</fullName>
    <formula>DP_Localidad__r.Provincia__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provincia</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DP_Tipo_de_vIa__c.field-meta.xml
<CustomField>
    <fullName>DP_Tipo_de_vIa__c</fullName>
    <label>Tipo de vía_1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_via</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Necesita_Financiacion__c.field-meta.xml
<CustomField>
    <fullName>Necesita_Financiacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necesita Financiación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferencia_Dormitorios__c.field-meta.xml
<CustomField>
    <fullName>Preferencia_Dormitorios__c</fullName>
    <label>Preferencia Dormitorios</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Uso_de_Inmueble__c.field-meta.xml
<CustomField>
    <fullName>Uso_de_Inmueble__c</fullName>
    <label>Uso de Inmueble</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª Residencia (Primer acceso)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Reposición)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Uso propio)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>Actividad profesional/empesarial</fullName>
                <isActive>false</isActive>
                <label>Actividad profesional/empesarial</label>
            </value>
            <value>
                <fullName>Inversión</fullName>
                <isActive>false</isActive>
                <label>Inversión</label>
            </value>
            <value>
                <fullName>Otros (especificar)</fullName>
                <isActive>false</isActive>
                <label>Otros (especificar)</label>
            </value>
            <value>
                <fullName>Primera Vivienda</fullName>
                <isActive>false</isActive>
                <label>Primera Vivienda</label>
            </value>
            <value>
                <fullName>Residencial</fullName>
                <isActive>false</isActive>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>Segunda Vivienda</fullName>
                <isActive>false</isActive>
                <label>Segunda Vivienda</label>
            </value>
            <value>
                <fullName>Vacacional</fullName>
                <isActive>false</isActive>
                <label>Vacacional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Altura_de_vivienda_interes__c.field-meta.xml
<CustomField>
    <fullName>Altura_de_vivienda_interes__c</fullName>
    <label>Altura de vivienda interés</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Altura_vivienda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Candidatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Preferencia_Dormitorios__c.field-meta.xml
<CustomField>
    <fullName>Preferencia_Dormitorios__c</fullName>
    <label>Preferencia Dormitorios</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>Más de 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Candidatos</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Uso_de_Inmueble__c.field-meta.xml
<CustomField>
    <fullName>Uso_de_Inmueble__c</fullName>
    <label>Uso de Inmueble</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª Residencia (Primer acceso)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Reposición)</fullName>
            </value>
            <value>
                <fullName>1ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Uso propio)</fullName>
            </value>
            <value>
                <fullName>2ª Residencia (Inversión)</fullName>
            </value>
            <value>
                <fullName>Inversión</fullName>
                <isActive>false</isActive>
                <label>Inversión</label>
            </value>
            <value>
                <fullName>Residencial</fullName>
                <isActive>false</isActive>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>Vacacional</fullName>
                <isActive>false</isActive>
                <label>Vacacional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Localidad</label>
    <nameField>
        <label>Nombre de Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Codigo_postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_postal__c</fullName>
    <label>Código postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Localidad__c.field-meta.xml
<CustomField>
    <fullName>Localidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Localidad</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Promociones</relationshipLabel>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Socio_Empresa_Promotora__c.field-meta.xml
<CustomField>
    <fullName>Socio_Empresa_Promotora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Socio/Empresa Promotora</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promociones Comercializadas</relationshipLabel>
    <relationshipName>PromocionesComercializadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Altura_vivienda.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bajo</fullName>
    </customValue>
    <customValue>
        <fullName>Plantas intermedias</fullName>
    </customValue>
    <customValue>
        <fullName>Ático</fullName>
    </customValue>
    <customValue>
        <fullName>Más3</fullName>
        <isActive>false</isActive>
        <label>Más3</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <isActive>false</isActive>
        <label>2</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <isActive>false</isActive>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>+3</fullName>
        <isActive>false</isActive>
        <label>+3</label>
    </customValue>
    <masterLabel>Altura vivienda</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_de_via.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Avenida</fullName>
    </customValue>
    <customValue>
        <fullName>Calle</fullName>
    </customValue>
    <customValue>
        <fullName>Glorieta</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>Bulevar</fullName>
    </customValue>
    <customValue>
        <fullName>Paseo</fullName>
    </customValue>
    <customValue>
        <fullName>Camino</fullName>
    </customValue>
    <customValue>
        <fullName>Carretera</fullName>
    </customValue>
    <masterLabel>Tipo de vía</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ControllerFichaCliente.cls
public class ControllerFichaCliente {

    private final Lead ld;
    public Lead candidato {get; set;}
	public Promocion__c promocion {get; set;}
    public boolean undormitorio {get; set;}
    public boolean dosdormitorios  {get; set;}
    public boolean tresdormitorios  {get; set;}
    public boolean cuatrodormitorios  {get; set;}
    public boolean baja  {get; set;} 
    public boolean plantasIntermedias  {get; set;}
    public boolean atico  {get; set;}
    //public boolean otros  {get; set;}
    public boolean primeraResidenciaPrimerAcceso  {get; set;}
    public boolean primeraResidenciaReposicion  {get; set;}
    public boolean primeraResidenciaInversion  {get; set;}
    public boolean segundaResidenciaUsoPropio  {get; set;}
    public boolean segundaResidenciaInversion  {get; set;}
    public boolean residencial  {get; set;}
    public boolean vacacional  {get; set;}
    public boolean inversion  {get; set;}

    public ControllerFichaCliente(ApexPages.StandardController stdController){
        this.ld=(Lead)stdController.getRecord();
		//Id idLead = ApexPages.currentPage().getParameters().get('id');
		//Obtiene los datos del candidato
		candidato = [SELECT FirstName,LastName,MobilePhone,Email,Localidad__r.Name,Codigo_postal__c,LeadSource,Preferencia_Dormitorios__c,Uso_de_Inmueble__c,Necesita_Financiacion__c,Altura_de_vivienda_interes__c,Promocion__c FROM Lead WHERE id=:ld.Id];
		System.debug(candidato);
        undormitorio=false;
        dosdormitorios=false;
        tresdormitorios=false;
        cuatrodormitorios=false;
        if(candidato.Preferencia_Dormitorios__c!=null){
        IF(candidato.Preferencia_Dormitorios__c.contains('1'))undormitorio=true;
        IF(candidato.Preferencia_Dormitorios__c.contains('2'))dosdormitorios=true;
        IF(candidato.Preferencia_Dormitorios__c.contains('3'))tresdormitorios=true;
        IF(candidato.Preferencia_Dormitorios__c.contains('4'))cuatrodormitorios=true;
        }
        
       
        baja=false;
        plantasIntermedias=false;
        atico=false;
        //otros=false;
        if(candidato.Altura_de_vivienda_interes__c!=null){
        IF(candidato.Altura_de_vivienda_interes__c.contains('Bajo'))baja=true;
        IF(candidato.Altura_de_vivienda_interes__c.contains('Plantas intermedias'))plantasIntermedias=true;
        IF(candidato.Altura_de_vivienda_interes__c.contains('Ático'))atico=true;
        //IF(candidato.Altura_de_vivienda_interes__c.contains('2')||candidato.Altura_de_vivienda_interes__c.contains('3')||candidato.Altura_de_vivienda_interes__c.contains('+3'))otros=true;
        }
        
        
        residencial=false;
        vacacional=false;
        inversion=false;
        if(candidato.Uso_de_Inmueble__c!=null){
        IF(candidato.Uso_de_Inmueble__c.contains('1ª Residencia (Primer acceso)'))primeraResidenciaPrimerAcceso=true;
        IF(candidato.Uso_de_Inmueble__c.contains('1ª Residencia (Reposición)'))primeraResidenciaReposicion=true;
        IF(candidato.Uso_de_Inmueble__c.contains('1ª Residencia (Inversión)'))primeraResidenciaInversion=true;
        IF(candidato.Uso_de_Inmueble__c.contains('2ª Residencia (Uso propio)'))segundaResidenciaUsoPropio=true;
        IF(candidato.Uso_de_Inmueble__c.contains('2ª Residencia (Inversión)'))segundaResidenciaInversion=true;
        }
        
		if(candidato.Promocion__c !=null){
			//Obtiene los datos de la promoción
			promocion = [SELECT Socio_Empresa_Promotora__r.Name, Socio_Empresa_Promotora__r.DP_Tipo_de_vIa__c, Socio_Empresa_Promotora__r.DP_Nombre_via__c, Socio_Empresa_Promotora__r.DP_N_via__c, Socio_Empresa_Promotora__r.DP_Localidad__r.Name, Socio_Empresa_Promotora__r.DP_Provincia__c, Socio_Empresa_Promotora__r.DP_Codigo_postal__c FROM Promocion__c WHERE id=:candidato.Promocion__c];
			System.debug(promocion);
		}
    }
}