force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Correo electrónico</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente Empresa, Cliente Personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas (Cliente)</relationshipLabel>
    <relationshipName>FacturasCliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Plan_de_pagos__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_pagos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de pagos</label>
    <referenceTo>Plan_de_pagos__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>Pdte de Aprobación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AttachmentTriggerHandler.cls
public class AttachmentTriggerHandler extends TriggerHandler {

    protected override void afterInsert() {
    	Map<Id, Attachment> news = (Map<Id, Attachment>) Trigger.newMap;
        List<Attachment> attachs = news.values();
        Id ParentId;
        String sParentObject = '';
        String fileNameKey = '';
        String fileName = '';
        
        for(Attachment att : attachs){
            ParentId = att.ParentId;
            sParentObject = ParentId.getSObjectType().getDescribe().getName();
            
            SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
            String parentDir = spCustomSettings.spParentDir__c;
            String baseDirPath = spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '');            

            Attachment attach = [SELECT Id, Body, BodyLength, Name, ParentId, Description, ContentType FROM Attachment
                                WHERE ParentId = :ParentId ORDER BY CreatedDate DESC LIMIT 1];	
            /*
            //Decisión del tipo de objeto para realizar cada operación.
            if(sParentObject == 'Opportunity'){
                //obtener Adjunto
                ContentDocumentLink cdl = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :ParentId LIMIT 1];
                ContentVersion cv = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE ContentDocumentId = :cdl.ContentDocumentId LIMIT 1];
				fileName = cv.Title;
                
                // Obtenemos las categorías para ese tipo de archivo    
                List<String> fileCats = SharePointConnectorMappings.getCatsByFileType(fileName);
                if(fileCats == null) fileCats = new List<String>();
        
                // Obtenemos los datos de la oportunidad
                Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :ParentId];
                
                // Obtenemos la promoción mediante la oportunidad
                String promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(ParentId.getSObjectType()).replace('$value$', ':oportunidadId');
                Promocion__c promotion = Database.query(promotionQuery);
        
                // Preparamos subida a Sharepoint:
                Map<String, String> metaDataMap = new Map<String, String>();
                metaDataMap.put('IdPromocion', promotion.Id);
                metaDataMap.put('IdOportunidad', ParentId);
                metaDataMap.put('TipoDocumento', 'Contrato'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
                metaDataMap.put('IdCuenta', opp.AccountId);
                Integer i = 1;
                for(String cat : fileCats) {
                    metaDataMap.put('Categoria' + i, cat);
                    i++;
                }
                metaDataMap.put('IdUsuario', UserInfo.getUserId());
                metaDataMap.put('Usuario', UserInfo.getUserEmail());
        
                DocumentCategory__c customDocCategory = null;
                String dirPath = baseDirPath + parentDir + '/' + promotion.Name;
                if(fileCats.size() > 0) {
                    customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
                    dirPath += '/' + customDocCategory.ParentDirectoryName__c;
                }
                
                fileName = SharePointConnectorMappings.getNameByCats(fileCats);*/
                /*if(!Test.isRunningTest()) {
                    SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
                    spConnector.login();
                    spConnector.createFile(EncodingUtil.base64Encode(pagePdf.getContentAsPdf()));
                    spConnector.updateFileMetaData();            
                }*//*
                SharePointConnect(fileName, dirPath, metaDataMap, att.body);
                SharePointConnector.commitDocumentNumber();
            }
            
            if(sParentObject == 'Facutra__c'){
            	Factura__c factura = [SELECT Id, Name, Cliente__c,Oportunidad__r.Promocion__c FROM Factura__c WHERE id = :ParentId LIMIT 1];
            	fileName = factura.Name;
                String email;
                
                // Obtenemos las categorías para ese tipo de archivo    
                List<String> fileCats = SharePointConnectorMappings.getCatsByFileType('Factura');
                if(fileCats == null) fileCats = new List<String>();
                
                // Obtenemos la promoción mediante la oportunidad
                Promocion__c promotion = [SELECT Id, Name FROM Promocion__c WHERE Id = :factura.Oportunidad__r.Promocion__c];
                
                // Preparamos subida a Sharepoint:
                Map<String, String> metaDataMap = new Map<String, String>();
                metaDataMap.put('IdPromocion', promotion.Id);
                metaDataMap.put('TipoDocumento', 'Archivo'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
                Integer i = 1;
                for(String cat : fileCats) {
                    metaDataMap.put('Categoria' + i, cat);
                    i++;
                }
                metaDataMap.put('IdUsuario', UserInfo.getUserId());
                metaDataMap.put('Usuario', UserInfo.getUserEmail());
        
                DocumentCategory__c customDocCategory = null;
                String dirPath = baseDirPath + parentDir + '/' + promotion.Name;
                System.debug('dirPath: ' + dirPath);
                if(fileCats.size() > 0) {
                    customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
                    dirPath += '/' + customDocCategory.ParentDirectoryName__c;
                }
                
                fileName = SharePointConnectorMappings.getNameByCats(fileCats);*/
                /*if(!Test.isRunningTest()) {
                    SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
                    spConnector.login();
                    spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
                    spConnector.updateFileMetaData();
                }*//*
                SharePointConnect(fileName, dirPath, metaDataMap, att.body);
                SharePointConnector.commitDocumentNumber();
                
                //Enviar la factura por email
                //obtener Adjunto
                ContentDocumentLink cdl = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :factura.Id LIMIT 1];
                ContentVersion cv = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE ContentDocumentId = :cdl.ContentDocumentId LIMIT 1];

                //Obtener email del destinarario (Cliente)
                Account cliente = [SELECT id, Email__c,PersonEmail, name FROM Account WHERE id =: factura.cliente__c LIMIT 1];
                System.debug(cliente);
                if(cliente.Email__c!=null){
                    email=cliente.Email__c;
                }else{
                    email=cliente.PersonEmail;
                }
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.toAddresses = new String[] {email};
                message.optOutPolicy = 'FILTER';
                message.subject = 'Factura ' + Factura.name;
                message.plainTextBody = 'Se ha adjuntado su factura a este email';
                
                Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                            efa.setFileName(cv.Title+'.pdf');
                            efa.setBody(cv.VersionData);
                            efa.setContentType('application/pdf');
                
                message.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                
                System.debug(message);
                Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
                        
                if (results[0].success) {
                    System.debug('El email se ha enviado correctamente');
                } else {
                    System.debug('Ha habido un problema al enviar el email: ' + results[0].errors[0].message);
                }
                
            }
            
            if(sParentObject == 'Plan_de_pagos__c'){
                Plan_de_pagos__c planPagos = [SELECT Id, Oportunidad__c FROM Plan_de_pagos__c WHERE Id =: ParentId AND Estado__c = 'Activo' LIMIT 1];
                Id oportunidadId = planPagos.Oportunidad__c;
                
                fileNameKey = 'Adenda';
        		fileName += ' ' + oportunidadId;
                
                // Obtenemos las categorías para ese tipo de archivo    
                List<String> fileCats = SharePointConnectorMappings.getCatsByFileType(fileNameKey);
                if(fileCats == null) fileCats = new List<String>();
        
                // Obtenemos los datos de la oportunidad
                Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :oportunidadId];

                // Obtenemos la promoción mediante la oportunidad
                String promotionQuery = SharePointConnectorMappings.getPromotionQueryByType(oportunidadId.getSObjectType()).replace('$value$', ':oportunidadId');
                Promocion__c promotion = Database.query(promotionQuery);                

				// Preparamos subida a Sharepoint:
                Map<String, String> metaDataMap = new Map<String, String>();
                metaDataMap.put('IdPromocion', promotion.Id);
                metaDataMap.put('IdOportunidad', oportunidadId);
                metaDataMap.put('TipoDocumento', 'Contrato'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
                metaDataMap.put('IdCuenta', opp.AccountId);
                Integer i = 1;
                for(String cat : fileCats) {
                    metaDataMap.put('Categoria' + i, cat);
                    i++;
                }
                metaDataMap.put('IdUsuario', UserInfo.getUserId());
                metaDataMap.put('Usuario', UserInfo.getUserEmail());

                DocumentCategory__c customDocCategory = null;
                String dirPath = baseDirPath + parentDir + '/' + promotion.Name;
                if(fileCats.size() > 0) {
                    customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
                    dirPath += '/' + customDocCategory.ParentDirectoryName__c;
                }

                fileName = SharePointConnectorMappings.getNameByCats(fileCats);*/
                /*if(!Test.isRunningTest()) {
                    SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
                    spConnector.login();
                    spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
                    spConnector.updateFileMetaData();
                }*//*
                SharePointConnect(fileName, dirPath, metaDataMap, att.body);
                SharePointConnector.commitDocumentNumber();
            }*/
            
            if(sParentObject == 'Quote'){
                fileNameKey = 'FichaPreReserva';
        		fileName = fileNameKey + ' ' + ParentId;
                
                // Obtenemos las categorías para ese tipo de archivo    
                List<String> fileCats = SharePointConnectorMappings.getCatsByFileType(fileNameKey);
                if(fileCats == null) fileCats = new List<String>();
                
                List<Quote> qs = [SELECT Opportunity.Promocion__c FROM Quote WHERE Id = :ParentId];
                if(qs.size() == 1) {
                    Promocion__c promo = [SELECT Id,Name FROM Promocion__c WHERE Id = :qs.get(0).Opportunity.Promocion__c];
        
                    // Preparamos subida a Sharepoint:
                    Map<String, String> metaDataMap = new Map<String, String>();
                    metaDataMap.put('IdPromocion', promo.Id);
                    metaDataMap.put('TipoDocumento', 'Archivo'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
                    Integer i = 1;
                    for(String cat : fileCats) {
                        metaDataMap.put('Categoria' + i, cat);
                        i++;
                    }
                    metaDataMap.put('IdUsuario', UserInfo.getUserId());
                    metaDataMap.put('Usuario', UserInfo.getUserEmail());
    
                    DocumentCategory__c customDocCategory = null;
                    String dirPath = baseDirPath + parentDir + '/' + promo.Name;
                    if(fileCats.size() > 0) {
                        customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
                        dirPath += '/' + customDocCategory.ParentDirectoryName__c;
                    }
    
                    fileName = SharePointConnectorMappings.getNameByCats(fileCats);
                    if(!Test.isRunningTest()) {
                        SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
                        spConnector.login();
                        //spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
                        spConnector.createFile(EncodingUtil.base64Encode(att.body));
                        spConnector.updateFileMetaData();
                    }
                    //SharePointConnect(fileName, dirPath, metaDataMap, att.body);
                    fileName = SharePointConnectorMappings.getNameByCats(fileCats);            
                }
            }
        }

    }
    
 /*    @future (callout=true)
     Public static void SharePointConnect(String fileName, String dirPath, Map<String, String> metaDataMap, Blob attBody)
     {
         if(!Test.isRunningTest()) {
         	SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
            spConnector.login();
            //spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
            spConnector.createFile(EncodingUtil.base64Encode(attBody));
            spConnector.updateFileMetaData();
         }
     }*/
    
}