force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Correo electrónico</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentCategory__c/DocumentCategory__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentCategory__c/fields/ParentDirectoryName__c.field-meta.xml
<CustomField>
    <fullName>ParentDirectoryName__c</fullName>
    <label>Directorio padre</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente Empresa, Cliente Personal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas (Cliente)</relationshipLabel>
    <relationshipName>FacturasCliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Codigo_Impuesto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Impuesto__c</fullName>
    <label>Código Impuesto</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Condicion_Cobro__c.field-meta.xml
<CustomField>
    <fullName>Condicion_Cobro__c</fullName>
    <label>Condición Cobro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Estado_de_la_factura__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_la_factura__c</fullName>
    <label>Estado de la factura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proforma</fullName>
            </value>
            <value>
                <fullName>Pendiente de emisión</fullName>
                <label>Pdte.Envío a Oracle</label>
            </value>
            <value>
                <fullName>Volcada a Oracle</fullName>
            </value>
            <value>
                <fullName>Conciliada SF</fullName>
            </value>
            <value>
                <fullName>Emitida</fullName>
            </value>
            <value>
                <fullName>Cobrada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Volcada y Emitida</fullName>
            </value>
            <value>
                <fullName>Impagada</fullName>
            </value>
            <value>
                <fullName>Abonada</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
                <isActive>false</isActive>
                <label>Anulada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_Contable__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Contable__c</fullName>
    <label>Fecha Contable</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Fecha_de_emision__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emision__c</fullName>
    <label>Fecha factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Numero_de_factura__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_factura__c</fullName>
    <label>Número de factura</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Entrada</fullName>
            </value>
            <value>
                <fullName>Aplazado</fullName>
            </value>
            <value>
                <fullName>Escritura</fullName>
            </value>
            <value>
                <fullName>Abonos</fullName>
            </value>
            <value>
                <fullName>Aportación capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <label>Referencia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sociedad</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad Cooperativa</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad Promotora</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_factura__c/Linea_de_factura__c.object-meta.xml
<CustomObject>
    <label>Línea de factura</label>
    <nameField>
        <label>Línea de factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Líneas de factura</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_factura__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <label>Factura</label>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Líneas de factura</relationshipLabel>
    <relationshipName>Lineas_de_factura</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Importe Reserva</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/SharePointConnector__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SharePointConnector</label>
</CustomObject>

force-app/main/default/objects/SharePointConnector__c/fields/spParentDir__c.field-meta.xml
<CustomField>
    <fullName>spParentDir__c</fullName>
    <description>Directorio padre donde estarán todas las subcarpetas y archivos</description>
    <inlineHelpText>Directorio padre donde estarán todas las subcarpetas y archivos</inlineHelpText>
    <label>Parent Directory</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteDomain__c.field-meta.xml
<CustomField>
    <fullName>spSiteDomain__c</fullName>
    <description>Dominio del sitio Sharepoint</description>
    <label>Site Domain</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharePointConnector__c/fields/spSiteUrl__c.field-meta.xml
<CustomField>
    <fullName>spSiteUrl__c</fullName>
    <description>Url del sitio SharePoint</description>
    <label>Url del sitio</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BotonEnviarFacturaControllerApex.cls
/*
FECHA         AUTOR       DESCRIPCIÓN
??			  ??		  Created.
21/09/2021	  LCS - HPS   Modification. LineaFactura and Factura descriptions get substringed for correct oracle integration.
*/

public class BotonEnviarFacturaControllerApex {
     @auraEnabled
     public static String getUrl(){
        String dominio = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/'; 
        return (dominio);
    }

     @auraEnabled
     public static String getCongaURL(String RecordId){ 
         
        APXTConga4__Conga_Solution__c CongaSol = [SELECT Id, APXTConga4__Button_body_field__c FROM APXTConga4__Conga_Solution__c WHERE Name = 'Generar Documento Factura' LIMIT 1];
         
        String dominio = CongaSol.APXTConga4__Button_body_field__c;
        dominio = dominio.replace('{!Factura__c.Id}', RecordId);
        
         return dominio;
    }             
    
	@auraEnabled
    public static Boolean generarFactura(Id facturaId){
    	System.debug('generarFactura');
    	List<ContentDocumentLink> listaDocumentos = [SELECT id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: facturaId];
        Set<id> setIdDocumentos = new Set<id>();
        
        //Si se pueden añadir más documentos en una factura se tiene que mirar el tipo del contentVersion
        //Obtener ids de documentos
        for(integer i = 0; i < listaDocumentos.size(); i++){
            setIdDocumentos.add(listaDocumentos[i].ContentDocumentId);
        }
        
        List<ContentVersion> listaContenidoDocumentos = [SELECT id FROM ContentVersion WHERE ContentDocumentId IN : setIdDocumentos AND tipo__c = 'factura'];
        System.debug('listaContenidoDocumentos: ' + listaContenidoDocumentos);
        if(listaContenidoDocumentos.size() == 0){
            guardarFacturaSharePoint(facturaId);
            guardarFactura(facturaId);
            return true;
        }

        return false;
    }
    
    public static void guardarFactura(Id facturaId){
        System.debug('guardarFactura');
        Factura__c factura = [SELECT id, name, cliente__c FROM Factura__c WHERE id = :facturaId LIMIT 1];
        
        PageReference pdfPage = new PageReference('/apex/VF_Documento_factura');
        pdfPage.getParameters().put('Id', facturaId);
        
        ContentVersion cv = new ContentVersion();
        cv.title = factura.name;
        cv.tipo__c = 'Factura';
        cv.PathOnClient = 'file.pdf';
        if(Test.isRunningTest()){
            cv.VersionData = blob.valueOf('Unit.Test');
        } else {
            cv.VersionData = pdfPage.getContentAsPdf();
        }
        cv.Origin = 'H';
    
        insert cv;
        
        ContentVersion cv2 = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE id = :cv.id LIMIT 1];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv2.ContentDocumentId;
        cdl.LinkedEntityId = facturaId;
        cdl.ShareType = 'V';
        
        //REVISAR PERMISOS -- QUIEN PUEDE VER LAS FACTURAS??
        cdl.Visibility = 'AllUsers';
        
        insert cdl;
        
        enviarEmail(factura.id);
        
    }

    private static void guardarFacturaSharePoint(Id facturaId) {
        SharePointConnector__c spCustomSettings = SharePointConnector__c.getOrgDefaults();
        String parentDir = spCustomSettings.spParentDir__c;
        String baseDirPath = spCustomSettings.spSiteUrl__c.replace(spCustomSettings.spSiteDomain__c, '');
        
        Factura__c factura = [SELECT Id, Name, Cliente__c,Oportunidad__r.Promocion__c FROM Factura__c WHERE id = :facturaId LIMIT 1];
        String fileName = factura.Name;
        PageReference pdfPage = new PageReference('/apex/VF_Documento_factura');
        pdfPage.getParameters().put('Id', facturaId);

        // Obtenemos las categorías para ese tipo de archivo    
        List<String> fileCats = SharePointConnectorMappings.getCatsByFileType('Factura');
        if(fileCats == null) fileCats = new List<String>();
        
        // Obtenemos la promoción mediante la oportunidad
        Promocion__c promotion = [SELECT Id, Name FROM Promocion__c WHERE Id = :factura.Oportunidad__r.Promocion__c];

        // Preparamos subida a Sharepoint:
        Map<String, String> metaDataMap = new Map<String, String>();
        metaDataMap.put('IdPromocion', promotion.Id);
        metaDataMap.put('TipoDocumento', 'Archivo'); // FIXME -> SEGURAMENTE TAMBIÉN CON MAPEO
        Integer i = 1;
        for(String cat : fileCats) {
            metaDataMap.put('Categoria' + i, cat);
            i++;
        }
        metaDataMap.put('IdUsuario', UserInfo.getUserId());
        metaDataMap.put('Usuario', UserInfo.getUserEmail());

        DocumentCategory__c customDocCategory = null;
        String dirPath = baseDirPath + parentDir + '/' + promotion.Name;
        System.debug('dirPath: ' + dirPath);
        if(fileCats.size() > 0) {
        	customDocCategory = [SELECT ParentDirectoryName__c FROM DocumentCategory__c WHERE Name = :fileCats.get(0)];                                
            dirPath += '/' + customDocCategory.ParentDirectoryName__c;
        }

        fileName = SharePointConnectorMappings.getNameByCats(fileCats);
        if(!Test.isRunningTest()) {
            SharePointConnector spConnector = new SharePointConnector(fileName + '.pdf', dirPath, metaDataMap);
            spConnector.login();
            spConnector.createFile(EncodingUtil.base64Encode(pdfPage.getContentAsPdf()));
            spConnector.updateFileMetaData();
        }
        SharePointConnector.commitDocumentNumber();
    }
    
    @AuraEnabled
    public static void enviarEmail(Id facturaId){
        String email;
        System.debug('enviarEmail');
        //Obtener factura
        Factura__c factura = [SELECT name, cliente__c FROM Factura__c WHERE id =: facturaId LIMIT 1];
		//obtener Adjunto
        ContentDocumentLink cdl = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :facturaId LIMIT 1];
        ContentVersion cv = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE ContentDocumentId = :cdl.ContentDocumentId LIMIT 1];
        
        //Obtener email del destinarario (Cliente)
        Account cliente = [SELECT id, Email__c,PersonEmail, name FROM Account WHERE id =: factura.cliente__c LIMIT 1];
        System.debug(cliente);
        if(cliente.Email__c!=null){
            email=cliente.Email__c;
        }else{
            email=cliente.PersonEmail;
        }
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = new String[] {email};
        message.optOutPolicy = 'FILTER';
        message.subject = 'Factura ' + Factura.name;
        message.plainTextBody = 'Se ha adjuntado su factura a este email';
        
        
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setFileName(cv.Title+'.pdf');
            efa.setBody(cv.VersionData);
            efa.setContentType('application/pdf');
        
        message.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        
        System.debug(message);
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'comercial@avintiainmobiliaria.com'];
		if ( owea.size() > 0 ) {
    		message.setOrgWideEmailAddressId(owea.get(0).Id);
		}
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        
        
        if (results[0].success) {
            System.debug('El email se ha enviado correctamente');
        } else {
            System.debug('Ha habido un problema al enviar el email: ' + results[0].errors[0].message);
        }
        
        
    }
    
    @AuraEnabled
    public static id generarFacturaAnulacion(Id facturaId){
        
        String description;
        //Opportunity oportunidad = [SELECT id,Reserva__c, Description FROM Opportunity WHERE id =: oportunidadId LIMIT 1];
        
        List<Factura__c> facturaOldList = [SELECT Id, Numero_de_factura__c, Referencia__c, Descripcion__c, Codigo_Impuesto__c, Origen__c, Cliente__c, Sociedad__c , Fecha_Contable__c, Fecha_de_emision__c,
                             		       Estado_de_la_factura__c, Condicion_Cobro__c, Metodo_de_cobro__c, Pago_o_Cuota__c, Importe__c, Oportunidad__c, Plan_de_pagos__c, Estado_plan_de_pagos__c, Name
                             		       FROM Factura__c
                             		       WHERE Id =: facturaId];
        
     
        if(!facturaOldList.isEmpty()){
            Factura__c facturaOld = facturaOldList[0];
            Factura__c fac = new Factura__c();
            
            fac.name = 'Anulación de ' + facturaOld.name;
            fac.Numero_de_factura__c = null;
            fac.Tipo_de_factura__c = 'FACTURA RECTIFICATIVA';
            if(facturaOld.Importe__c != null){
            	fac.Importe__c = -1 * facturaOld.Importe__c ;    
            }
            fac.Tipologia__c = 'Abono';
            if(facturaOld.Referencia__c != null){
            	fac.Referencia__c = facturaOld.Referencia__c.substringBeforeLast('-')+'-09';
            }
            description = 'Anulación factura número '+ (facturaOld.Numero_de_factura__c);
            fac.Descripcion__c = description.length() > 80 ? description.substring(0, 80) : description; 
            fac.Codigo_Impuesto__c = facturaOld.Codigo_Impuesto__c;
            fac.Origen__c = 'Abonos';
            fac.Cliente__c = facturaOld.Cliente__c;
            fac.Sociedad__c = facturaOld.Sociedad__c;
            fac.Fecha_Contable__c = date.today() + 1;
            fac.Fecha_de_emision__c = date.today() + 1;
            fac.Estado_de_la_factura__c = 'Pendiente de emisión';
            fac.Condicion_Cobro__c = facturaOld.Condicion_Cobro__c; //cambiar
            fac.Metodo_de_cobro__c = facturaOld.Metodo_de_cobro__c;
            fac.Pago_o_Cuota__c = 'Abono';
            fac.Oportunidad__c = facturaOld.Oportunidad__c;
            fac.Plan_de_pagos__c = facturaOld.Plan_de_pagos__c;
            fac.Estado_plan_de_pagos__c = facturaOld.Estado_plan_de_pagos__c;
            //fac.Tipo_de_linea__c = 'Depósito';
            //fac.Fecha cobro 
            
            if(facturaOld.Estado_de_la_factura__c != 'Cancelada' && facturaOld.Estado_de_la_factura__c != 'Volcada y Emitida' && facturaOld.Estado_de_la_factura__c != 'Cobrada') facturaOld.Estado_de_la_factura__c = 'Cancelada';
            
            try{
                system.debug('fac:::'+fac);
                update facturaOld;
                insert fac;
                
                List<Linea_de_factura__c> lineaFacturaOldList = [SELECT Name, Numero_de_linea__c, Tipo_de_linea__c, Factura__c, Importe__c, DescripcionLinea__c
                                                       FROM Linea_de_factura__c
                                                       WHERE Factura__c =: facturaOld.Id];
                
                if(!lineaFacturaOldList.isEmpty()){
                    List<Linea_de_factura__c> lineaFacturaList = new List<Linea_de_factura__c>();
                    for(Integer i = 0; i < lineaFacturaOldList.size(); i++){
                        Linea_de_factura__c lineaFactura = new Linea_de_factura__c(); 
                        if(lineaFacturaOldList[i].Name.length() > 66){
                            String nombre = 'Anulación de ' + lineaFacturaOldList[i].Name;
                            lineaFactura.Name = nombre.length() > 80 ? nombre.substring(0, 80) : nombre;                                  
                        }else{
                            lineaFactura.Name = 'Anulación de ' + lineaFacturaOldList[i].Name;
                        }
                        lineaFactura.Numero_de_linea__c = lineaFacturaOldList[i].Numero_de_linea__c;
                        lineaFactura.Tipo_de_linea__c = lineaFacturaOldList[i].Tipo_de_linea__c;
                        lineaFactura.Factura__c = fac.Id;
                        if(lineaFacturaOldList[i].Importe__c != null){
                            lineaFactura.Importe__c = -1 * lineaFacturaOldList[i].Importe__c;    
                        }
                        
                        lineaFactura.DescripcionLinea__c = (lineaFacturaOldList[i].DescripcionLinea__c).length() > 80 ? (lineaFacturaOldList[i].DescripcionLinea__c).substring(0, 80) : lineaFacturaOldList[i].DescripcionLinea__c;
                        lineaFacturaList.add(lineaFactura);
                    }
                        try{
                            system.debug('lineaFactura:::'+lineaFacturaList);	
                            insert lineaFacturaList;
                            /*String dominio = System.URL.getSalesforceBaseUrl().toExternalForm() + '/';
                            PageReference retUrl = new PageReference(dominio+fac.id);
                            retURL.setRedirect(true);*/
                            system.debug('fac.id:::'+fac.id);
                            return fac.id;
                        }catch(System.DmlException e){
                            System.debug('BotonReservaController | generarFacturaAbono() - DmlException: ' + e.getMessage());
                        }
                	
                }
            }catch(System.DmlException e){
                System.debug('BotonReservaController | generarFacturaAbono() - DmlException: ' + e.getMessage());
            }    
        
        }

   		return null;
    }

}