force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Concepto_transferencia__c.field-meta.xml
<CustomField>
    <fullName>Concepto_transferencia__c</fullName>
    <label>Concepto transferencia</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Descripcion_Viviendas__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Viviendas__c</fullName>
    <label>Descripción Viviendas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Porcentaje_IVA__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_IVA__c</fullName>
    <label>Porcentaje impuesto</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verificando_PBC__c.field-meta.xml
<CustomField>
    <fullName>Verificando_PBC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verificando PBC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <formula>PricebookEntry.Product2.Promocion__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promoción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Apalabrado</fullName>
                <label>Pre-Reservado</label>
            </value>
            <value>
                <fullName>Bloqueado temporalmente</fullName>
                <label>Reserva en gestión</label>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
            <value>
                <fullName>Canje</fullName>
            </value>
            <value>
                <fullName>Apartado</fullName>
            </value>
            <value>
                <fullName>Asociado</fullName>
                <isActive>false</isActive>
                <label>Asociado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/N_Vivienda_Garaje_Trastero_Local__c.field-meta.xml
<CustomField>
    <fullName>N_Vivienda_Garaje_Trastero_Local__c</fullName>
    <label>Nº Vivienda/Garaje/Trastero/Local</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_de_inmueble__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_inmueble__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de inmueble</label>
    <referenceTo>Tipo_de_inmueble__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Codigo_de_la_promocion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_la_promocion__c</fullName>
    <label>Código de la promoción contable</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Porcentaje_IVA__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_IVA__c</fullName>
    <defaultValue>0.1</defaultValue>
    <label>Porcentaje impuesto</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/Tipo_de_inmueble__c.object-meta.xml
<CustomObject>
    <label>Tipo de inmueble</label>
    <nameField>
        <label>Nombre de Tipo de inmueble</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipo de inmueble</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Tipo de inmueble</relationshipLabel>
    <relationshipName>Tipo_de_inmueble</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tipo_de_inmueble__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garaje</fullName>
            </value>
            <value>
                <fullName>Trastero</fullName>
            </value>
            <value>
                <fullName>Vivienda</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Mejoras</fullName>
            </value>
            <value>
                <fullName>Personalizacion</fullName>
                <label>Personalización</label>
            </value>
            <value>
                <fullName>Descuento</fullName>
                <isActive>false</isActive>
                <label>Descuento</label>
            </value>
            <value>
                <fullName>Mobiliario</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityLineItemTriggerHandler.cls
/****************************************************************
 * Class Name: OpportunityLineItemTriggerHandler                *
 * Test Name: OpportunityLineItemTriggerHandler_Test            *
 * Date: 25/09/2018                                             *
 * Author: Deloitte                                             *
 * Description: handler class for product2 trigger              *
 * *************************************************************/
public class OpportunityLineItemTriggerHandler {

     /*******************************************************************************************************************
     * Method Name: anadirEstadoDescripcion                                                                             *
     * Description: Actualiza la entrada en la lista de precios estándar si ya existe, o crea la entrada si no existe . *
     * Author: Deloitte                                                                                                 *
     * *****************************************************************************************************************/  
    
    public static void anadirEstadoDescripcion (List<OpportunityLineItem> newList){ 

        //Recuperamos los Id de las oportunidades a las que están asociados los productos de oportunidad que hacen saltar el trigger
        Set<Id> opportunityIdSet = new Set<Id>();
        for(OpportunityLineItem opportunityLineItem : newList){
            opportunityIdSet.add(opportunityLineItem.OpportunityId);
        }
        
        //Recuperamos los productos de presupuesto asociados a una oferta que a su vez este asociada a las oportunidades anteriores
        List<QuoteLineItem> quoteLineItemList = [SELECT Product2.Name, Product2.Estado__c, Product2.Tipo_de_inmueble__r.Tipo__c ,Quote.OpportunityId, Product2.N_Vivienda_Garaje_Trastero_Local__c 
                                                 FROM QuoteLineItem 
                                                 WHERE Quote.OpportunityId IN: opportunityIdSet ORDER BY Product2.Name];
        system.debug('quoteLineItemList:::'+quoteLineItemList);
        
        
        //Hacemos algunas comprobaciones sobre los productos del presupuesto
        Boolean marcadorVivienda = False;
        for(QuoteLineItem quoteLineItem : quoteLineItemList){
            /*if(quoteLineItem.Product2.Estado__c != 'Libre' && quoteLineItem.Product2.Estado__c != 'Bloqueado temporalmente' && quoteLineItem.Product2.Estado__c != 'Asociado'){
                Trigger.new[0].addError('Alguno de los inmuebles que se está intentando sincronizar ya están Apalabrados', true);
            }*/
            if(quoteLineItem.Product2.Tipo_de_inmueble__r.Tipo__c == 'Vivienda'){
                marcadorVivienda = True;
            }
        }
        

        if(!quoteLineItemList.isEmpty()){
            //Creamos un map que relacione el id de una oportunidad con la concantenación del nombre de los inmuebles
            Map<Id, String> opportunityIdMap = new Map<Id, String>(); 
            Map<Id, QuoteLineItem> opportunityIdViviendaMap = new Map<Id, QuoteLineItem>(); 
            Map<Id, QuoteLineItem> oppIdViviendaMap = new Map<Id, QuoteLineItem>(); //Mapa para guardar solo las viviendas de una oportunidad
            Map<Id, String> oppIdViviendaDesc = new Map<Id, String>(); //Mapa para guardar solo las viviendas de una oportunidad
            for(Id opportunityId : opportunityIdSet){
                for(QuoteLineItem quoteLineItem : quoteLineItemList){
                    //Primero guardamos el inmueble, si hay vivienda, se guarda vivienda.
                    if(opportunityIdViviendaMap.get(opportunityId)!= null && quoteLineItem.Product2.Tipo_de_inmueble__r.Tipo__c == 'Vivienda' && opportunityIdViviendaMap.get(opportunityId).Product2.Tipo_de_inmueble__r.Tipo__c != 'Vivienda'){
                        opportunityIdViviendaMap.put(opportunityId, quoteLineItem);
                        oppIdViviendaMap.put(opportunityId, quoteLineItem);
                    }else if(opportunityIdViviendaMap.get(opportunityId)== null){
                        opportunityIdViviendaMap.put(opportunityId, quoteLineItem);
                    }
                    //Concantenamos los nombres de los productos
                    if(opportunityId == quoteLineItem.Quote.OpportunityId && !opportunityIdMap.keySet().contains(opportunityId)){
                        String descripcion = quoteLineItem.Product2.Name;
                        opportunityIdMap.put(opportunityId, descripcion);
                        oppIdViviendaDesc.put(opportunityId, descripcion);
                    }else if(opportunityId == quoteLineItem.Quote.OpportunityId && opportunityIdMap.keySet().contains(opportunityId)){
                        String descripcion = opportunityIdMap.get(opportunityId) + ', ' +quoteLineItem.Product2.Name;
                        opportunityIdMap.put(opportunityId, descripcion);
                    }
                }
            }
            
            //Recuperamos las oportunidades e iteramos la lista para poder sobreescribir los campos Description y StageName
            List<Opportunity> opportunityList = [SELECT Id, Description, Descripcion_Viviendas__c, StageName, Concepto_transferencia__c, Account.N_Documento__c, Promocion__r.Codigo_de_la_promocion__c FROM Opportunity WHERE Id IN: opportunityIdSet];
            for(Opportunity opportunity : opportunityList){
                opportunity.Descripcion_Viviendas__c = oppIdViviendaDesc.get(opportunity.Id).trim();
                if(opportunityIdMap.get(opportunity.Id).contains(',')){
                	opportunity.Description = 'Inmuebles '+opportunityIdMap.get(opportunity.Id).trim();                    
                }else{
                    opportunity.Description = 'Inmueble '+opportunityIdMap.get(opportunity.Id).trim();  
                }
                
                String concepto = opportunity.Promocion__r.Codigo_de_la_promocion__c + ' ' + opportunityIdViviendaMap.get(opportunity.Id).Product2.N_Vivienda_Garaje_Trastero_Local__c + ' ' + opportunity.Account.N_Documento__c; 
                if(opportunity.Concepto_transferencia__c == null && concepto.length() < 140){
                		opportunity.Concepto_transferencia__c = concepto;   
                }else if(opportunity.Concepto_transferencia__c == null && concepto.length() >= 140){
                    	opportunity.Concepto_transferencia__c = concepto.substring(0, 140);
                }
                //opportunity.StageName = 'Pre-Reserva';
                if(opportunity.StageName != 'Presupuesto' && opportunity.StageName != 'Pre-Reserva'){
                	opportunity.Verificando_PBC__c = true; //BCF - no retrocede etapa de la oportunidad y se marca el check PBC
                }
                if(marcadorVivienda == False){
                    opportunity.Porcentaje_IVA__c = 21; 
                }
            }
            system.debug('opportunityList:::'+opportunityList);
            update opportunityList;               
        }
     
        
    }
    
    public static void validarEstadoInmuebles (List<OpportunityLineItem> newList){
        
        //Recuperamos los Ids de los productos
        List<Id> product2IdList = new List<Id>();
        for(OpportunityLineItem opportunityLineItem : newList){
            product2IdList.add(opportunityLineItem.Product2Id);
        }
        
        List<Product2> product2List = [SELECT Estado__c FROM Product2 WHERE Id IN: product2IdList AND Estado__c != 'Libre' AND Estado__c != 'Bloqueado temporalmente' AND Estado__c != 'Asociado'];
        
        if(product2List.size() > 0){
            Trigger.new[0].addError('Alguno de los inmuebles que se está intentando sincronizar ya están Apalabrados', true);
        }
    }
    
}