force-app/main/default/objects/Account/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Cuenta.recordType-meta.xml
<RecordType>
    <fullName>Cuenta</fullName>
    <active>true</active>
    <label>Cliente Empresa</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Relacionado con</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Posicion__c.field-meta.xml
<CustomField>
    <fullName>Posicion__c</fullName>
    <description>Posición de la imagen en el slide</description>
    <inlineHelpText>Posición de la imagen en el slide</inlineHelpText>
    <label>Posición</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Versiones de los contenidos</relationshipLabel>
    <relationshipName>Contenidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imagen</fullName>
            </value>
            <value>
                <fullName>Archivo</fullName>
            </value>
            <value>
                <fullName>Plano</fullName>
            </value>
            <value>
                <fullName>Pre-reserva</fullName>
            </value>
            <value>
                <fullName>Justificante de pago</fullName>
            </value>
            <value>
                <fullName>Reserva</fullName>
            </value>
            <value>
                <fullName>Borrador de contrato</fullName>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Imagen_carrusel</fullName>
                <label>Imagen carrusel</label>
            </value>
            <value>
                <fullName>Carrusel_lifestyle</fullName>
                <label>Carrusel Lifestyle</label>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Folleto</fullName>
            </value>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Planos_zonas_comunes</fullName>
                <label>Planos Zonas Comunes</label>
            </value>
            <value>
                <fullName>Carrusel_entorno</fullName>
                <label>Carrusel Entorno</label>
            </value>
            <value>
                <fullName>Pie_de_web</fullName>
                <label>Pie de web</label>
            </value>
            <value>
                <fullName>Imagen_financiera</fullName>
                <label>Imagen Financiera</label>
            </value>
            <value>
                <fullName>Logo Promoción</fullName>
            </value>
            <value>
                <fullName>Plano_PDF</fullName>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro superficies</label>
            </value>
            <value>
                <fullName>Video_Youtube</fullName>
                <label>Video Youtube</label>
            </value>
            <value>
                <fullName>Visita VR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/DocumentVersionHistory__c.object-meta.xml
<CustomObject>
    <label>Histórico Versiones Documento</label>
    <nameField>
        <displayFormat>DVH-{00000}</displayFormat>
        <label>Document Version History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos Versiones de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Document_Version_History_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Version_History_Name__c</fullName>
    <label>Document Version History Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente de Aprobación</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipName>Document_Versions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Memoria_calidades</fullName>
                <label>Memoria Calidades</label>
            </value>
            <value>
                <fullName>Cuadro_superficies</fullName>
                <label>Cuadro Superficies</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentVersionHistory__c/fields/VersionNumber__c.field-meta.xml
<CustomField>
    <fullName>VersionNumber__c</fullName>
    <label>VersionNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TEST_HL_ContentVersionTrigger.cls
@isTest
public class TEST_HL_ContentVersionTrigger {
    
    @isTest 
    public static void testaddURLPublica(){
        Test.startTest();
        ContentVersion imagen = TestUtil.getImagen();
        imagen.Title = 'Imagen prueba v2';
        update imagen;
        Test.stopTest();
        
        imagen = [SELECT id, Title,Tipo__c, URL__c FROM ContentVersion WHERE id =:Imagen.id LIMIT 1];

        System.assert(Imagen.URL__c != null);
        System.assertEquals('Imagen prueba v2', Imagen.Title);
    }
    
    @isTest
    public static void testRelateDocumentOpportunity(){
        Test.startTest();
        Promocion__c promocion = TestUtil.getPromocion(Date.today(), Date.today().addMonths(12));
        Account cuenta = [SELECT Id FROM Account WHERE Name = 'Cuenta test1']; 
        
        Opportunity oportunidad = new Opportunity();
        oportunidad.Promocion__c = promocion.Id;
        oportunidad.Name = 'Prueba';
        oportunidad.StageName = 'Pre-Reserva';
        oportunidad.CloseDate = Date.today();
        oportunidad.AccountId = cuenta.Id;
        insert oportunidad;
        
        ContentVersion memoriaCalidades = new ContentVersion();
        memoriaCalidades.Title = 'memoriaCalidades';
        memoriaCalidades.PathOnClient = 'memoriaCalidades.png';
        memoriaCalidades.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
        memoriaCalidades.Tipo__c = 'Memoria_calidades';
        memoriaCalidades.Posicion__c = 1;
        memoriaCalidades.ParentId__c = promocion.Id;
        insert memoriaCalidades;
        
        ContentVersion cv = [SELECT ContentDocumentId, Title, VersionData FROM ContentVersion WHERE Id = :memoriaCalidades.Id];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv.ContentDocumentId;
        cdl.LinkedEntityId = promocion.Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        Test.stopTest();

        Set<Id> linkedEntities = new Set<Id>();
        List<ContentDocumentLink> cdlOpps = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE ContentDocumentId = :cv.ContentDocumentId];
        for(ContentDocumentLink cdlOpp : cdlOpps) linkedEntities.add(cdlOpp.LinkedEntityId);
        
        System.assert(linkedEntities.contains(oportunidad.Id));
    }
    
    @isTest
    public static void testCreateDocumentVersionHistoryRecord(){
        Test.startTest();
        Promocion__c promocion = TestUtil.getPromocion(Date.today(), Date.today().addMonths(12));
        Account cuenta = [SELECT Id FROM Account WHERE Name = 'Cuenta test1']; 
        
        Opportunity oportunidad = new Opportunity();
        oportunidad.Promocion__c = promocion.Id;
        oportunidad.Name = 'Prueba';
        oportunidad.StageName = 'Pre-Reserva';
        oportunidad.CloseDate = Date.today();
        oportunidad.AccountId = cuenta.Id;
        insert oportunidad;
        
        ContentVersion memoriaCalidades = new ContentVersion();
        memoriaCalidades.Title = 'Test Memoria Calidades';
        memoriaCalidades.PathOnClient = 'Test Memoria Calidades.png';
        memoriaCalidades.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
        memoriaCalidades.Tipo__c = 'Memoria_calidades';
        memoriaCalidades.Posicion__c = 1;
        memoriaCalidades.ParentId__c = promocion.Id;
        memoriaCalidades.IsMajorVersion = false;
        insert memoriaCalidades;
        
        ContentVersion cv = [SELECT ContentDocumentId, PathOnClient, Title, VersionNumber, VersionData FROM ContentVersion WHERE Id = :memoriaCalidades.Id];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv.ContentDocumentId;
        cdl.LinkedEntityId = promocion.Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;

        Test.stopTest();
        
        DocumentVersionHistory__c dvh1 = [SELECT Id, Name, Document_Version_History_Name__c, Tipo__c, Estado__c, Promocion__c, VersionNumber__c FROM DocumentVersionHistory__c];
        
        System.assertEquals(cv.Title + ' - v1', dvh1.Document_Version_History_Name__c);
        System.assertEquals(1, dvh1.VersionNumber__c);
        System.assertEquals('Memoria_calidades', dvh1.Tipo__c);
        System.assertEquals('Pendiente de Aprobación', dvh1.Estado__c);
        
        for(Integer i = 0; i < 6; i++) approveProcess(dvh1.Id);
        
        dvh1 = [SELECT Id, Name, Document_Version_History_Name__c, Tipo__c, Estado__c, Promocion__c, VersionNumber__c FROM DocumentVersionHistory__c];
        
        System.assertEquals(cv.Title + ' - v1', dvh1.Document_Version_History_Name__c);
        System.assertEquals(1, dvh1.VersionNumber__c);
        System.assertEquals('Memoria_calidades', dvh1.Tipo__c);
        System.assertEquals('Aprobado', dvh1.Estado__c);
    }
    
    private static void approveProcess(Id parent) {
        List<ProcessInstanceWorkitem> workItems = [
             SELECT Id
               FROM ProcessInstanceWorkitem 
              WHERE ProcessInstance.TargetObjectId = :parent
                AND ProcessInstance.Status = 'Pending'];
                
        if(!workItems.isEmpty()){
            Approval.ProcessWorkitemRequest pwr = new Approval.ProcessWorkitemRequest();
            pwr.setWorkitemId(workItems.get(0).Id);
            pwr.setAction('Approve');
            pwr.setComments('Approved.');
            Approval.process(pwr);
        }
    }

}