force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Fecha_de_emision__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_emision__c</fullName>
    <label>Fecha factura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Numero_de_factura__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_factura__c</fullName>
    <label>Número de factura</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Permitir_borrado_con_numeracion__c.field-meta.xml
<CustomField>
    <fullName>Permitir_borrado_con_numeracion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permitir borrado con numeración</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/SecuencialFactura__c.field-meta.xml
<CustomField>
    <fullName>SecuencialFactura__c</fullName>
    <label>SecuencialFactura</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TEST_HL_FacturaTrigger.cls
@isTest
public class TEST_HL_FacturaTrigger {

    @isTest
    public static void testBeforeDelete() {
        Factura__c factura = TestUtil.getFactura();
        Factura__c f = [SELECT Id, IsDeleted, Numero_de_factura__c, Permitir_borrado_con_numeracion__c FROM Factura__c WHERE Id = :factura.Id];
        f.Numero_de_factura__c = '200100036';
        f.SecuencialFactura__c = 36;
        update f;
        
        Test.startTest();
        try{
            delete f;
        } catch(DmlException ex) {
            //System.assert(ex.getMessage().contains('La factura que se desea eliminar tiene número de factura y no está marcado el check'+
           //                   +' "Permitir borrado con numeración". Si desea eliminar la factura, recuerde marcar dicho check.')); 
        }
        
        f.Permitir_borrado_con_numeracion__c = true;
        update f;
        delete f;
        Test.stopTest();
    }
    
     public static void testBeforeUpdate() {
         
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
         
        Factura__c factura = TestUtil.getFactura();
        Factura__c f = TestUtil.getFactura();
        factura.Numero_de_factura__c = '1';
        factura.Fecha_de_emision__c = Date.newInstance(2018, 10, 03);
        factura.Oportunidad__c = opp.Id;
        update factura;
        
        f.Oportunidad__c = opp.Id;
        f.Numero_de_factura__c = '2';
        f.Fecha_de_emision__c = Date.newInstance(2017, 10, 03);
        
        Test.startTest();
        try{
            update f;
        } catch(DmlException ex) {}
        
        Test.stopTest();
    }
    
}