force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/IdPromocionBabonlab__c.field-meta.xml
<CustomField>
    <fullName>IdPromocionBabonlab__c</fullName>
    <externalId>true</externalId>
    <label>IdPromocionBabonlab</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/PropiedadesIntegracion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Propiedades integración</description>
    <label>PropiedadesIntegracion</label>
</CustomObject>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/API_KEY_BABONLAB__c.field-meta.xml
<CustomField>
    <fullName>API_KEY_BABONLAB__c</fullName>
    <label>API_KEY_BABONLAB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/ILC_IDEALISTA__c.field-meta.xml
<CustomField>
    <fullName>ILC_IDEALISTA__c</fullName>
    <label>ILC_IDEALISTA</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/URL_BABONLAB_PROMOCION__c.field-meta.xml
<CustomField>
    <fullName>URL_BABONLAB_PROMOCION__c</fullName>
    <label>URL_BABONLAB_PROMOCION</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/URL_BABONLAB_VIVIENDAS__c.field-meta.xml
<CustomField>
    <fullName>URL_BABONLAB_VIVIENDAS__c</fullName>
    <label>URL_BABONLAB_VIVIENDAS</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestPublicacionBabonLab.cls
@isTest
public class TestPublicacionBabonLab {
    
    private static PropiedadesIntegracion__c propiedades;
    
    static {
        propiedades = new PropiedadesIntegracion__c();
        propiedades.URL_BABONLAB_VIVIENDAS__c = 'http://prueba.com';
        propiedades.URL_BABONLAB_PROMOCION__c = 'http://prueba.com';
        propiedades.API_KEY_BABONLAB__c = '123456';
        propiedades.ILC_IDEALISTA__c = 'ilc1f58c0cc5ad3dd64528c6ae121a8de8a11a8a4f7';
        upsert propiedades;
    }

    @isTest
    static void testPublicacionBabonLab() {
        date fechaInicioComercializacionPrevista = date.newInstance(2018, 09, 20);
        date fechaFinComercializacionPrevista = date.newInstance(2018, 10, 03);
        Promocion__c promocion = TestUtil.getPromocion(fechaInicioComercializacionPrevista, fechaFinComercializacionPrevista);
        TestUtil.testCrearInmueblePromocion2(promocion.ID);
        TestUtil.getHitos(promocion.ID);
        Test.startTest();
        PublicacionBabonlab.enviarPromocion(promocion.ID);
        PublicacionBabonlab.actualizarPromocion(promocion.ID, promocion.idPromocionBabonlab__c);
        PublicacionBabonlab.enviarViviendas(promocion.ID);
        PublicacionBabonlab.generarPeticionAltaModifVivienda(promocion.ID);
        Test.stopTest();
    }
    
    @isTest
    static void testPublicacionBabonLab2() {
        date fechaInicioComercializacionPrevista = date.newInstance(2018, 09, 20);
        date fechaFinComercializacionPrevista = date.newInstance(2018, 10, 03);
        Promocion__c promocion = TestUtil.getPromocion(fechaInicioComercializacionPrevista, fechaFinComercializacionPrevista);
        TestUtil.testCrearInmueblePromocion2(promocion.ID);
        TestUtil.getHitos2(promocion.ID);
        Test.startTest();
        PublicacionBabonlab.enviarPromocion(promocion.ID);
        PublicacionBabonlab.actualizarPromocion(promocion.ID, promocion.idPromocionBabonlab__c);
        PublicacionBabonlab.enviarViviendas(promocion.ID);
        PublicacionBabonlab.generarPeticionAltaModifVivienda(promocion.ID);
        PublicacionBabonlab.actualizarViviendas(promocion.ID);
        Test.stopTest();
    }
    
    @isTest
    static void testPublicacionBabonLab3() {

        date fechaInicioComercializacionPrevista = date.newInstance(2018, 09, 20);
        date fechaFinComercializacionPrevista = date.newInstance(2018, 10, 03);
        Promocion__c promocion = TestUtil.getPromocion(fechaInicioComercializacionPrevista, fechaFinComercializacionPrevista);
        TestUtil.testCrearInmueblePromocion2(promocion.ID);
        TestUtil.getHitos3(promocion.ID);
        Test.startTest();
        TriggerHandler.bypass('PromocionTrigger');
        TriggerHandler.bypass('Product2Trigger');
        PublicacionBabonlab.enviarPromocion(promocion.ID);
        PublicacionBabonlab.actualizarPromocion(promocion.ID, promocion.idPromocionBabonlab__c);
        PublicacionBabonlab.enviarViviendas(promocion.ID);
        PublicacionBabonlab.generarPeticionAltaModifVivienda(promocion.ID);
        TriggerHandler.clearAllBypasses();
        Test.stopTest();

    }

}