force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PropiedadesIntegracion__c/PropiedadesIntegracion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Propiedades integración</description>
    <label>PropiedadesIntegracion</label>
</CustomObject>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/ILC_IDEALISTA__c.field-meta.xml
<CustomField>
    <fullName>ILC_IDEALISTA__c</fullName>
    <label>ILC_IDEALISTA</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/NumDiasLeadFotocasa__c.field-meta.xml
<CustomField>
    <fullName>NumDiasLeadFotocasa__c</fullName>
    <label>NumDiasLeadFotocasa</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/PasswordWSAvintia__c.field-meta.xml
<CustomField>
    <fullName>PasswordWSAvintia__c</fullName>
    <label>PasswordWSAvintia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/URL_LEAD_FOTOCASA__c.field-meta.xml
<CustomField>
    <fullName>URL_LEAD_FOTOCASA__c</fullName>
    <label>URL_LEAD_FOTOCASA</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PropiedadesIntegracion__c/fields/UsuarioLeadFotocasa__c.field-meta.xml
<CustomField>
    <fullName>UsuarioLeadFotocasa__c</fullName>
    <label>UsuarioLeadFotocasa</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCargaLeadFotocasa.cls
@isTest
public class TestCargaLeadFotocasa {
    private static PropiedadesIntegracion__c propiedades;
    static {

        propiedades = new PropiedadesIntegracion__c();

        propiedades.URL_LEAD_FOTOCASA__c = 'http://prueba.com';

        propiedades.UsuarioLeadFotocasa__c = 'usuario';
        propiedades.PasswordWSAvintia__c = '1234';
        propiedades.NumDiasLeadFotocasa__c = 1;
        propiedades.ILC_IDEALISTA__c = 'ilc1f58c0cc5ad3dd64528c6ae121a8de8a11a8a4f7';

        upsert propiedades;

    }
    @isTest
    static void testCaragarLead() {

        date fechaInicioComercializacionPrevista = date.newInstance(2018, 09, 20);
        date fechaFinComercializacionPrevista = date.newInstance(2018, 10, 03);
        Promocion__c promocion = TestUtil.getPromocion(fechaInicioComercializacionPrevista, fechaFinComercializacionPrevista);
        TestUtil.testCrearInmueblePromocion(promocion.ID);

        Test.startTest();
        CargaLeadFotocasa carga = new CargaLeadFotocasa();
        carga.execute(null);
        Test.stopTest();
    }
}