force-app/main/default/objects/Cobro__c/Cobro__c.object-meta.xml
<CustomObject>
    <label>Cobro</label>
    <nameField>
        <label>Cobro Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobros</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Cobro__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cobro__c/fields/Factura__c.field-meta.xml
<CustomField>
    <fullName>Factura__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Factura</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Factura__c.Name</field>
            <operation>notContain</operation>
            <value>Plan de pagos</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Factura__c</referenceTo>
    <relationshipLabel>Cobros</relationshipLabel>
    <relationshipName>Cobros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cobro__c/fields/Nombre_sociedad__c.field-meta.xml
<CustomField>
    <fullName>Nombre_sociedad__c</fullName>
    <label>Nombre de la sociedad</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cobro__c/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <label>Referencia</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Nombre de Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Concepto__c.field-meta.xml
<CustomField>
    <fullName>Concepto__c</fullName>
    <label>Concepto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factura__c/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <label>Referencia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCambioEstadoCobroTrigger.cls
@isTest
public class TestCambioEstadoCobroTrigger {

    @isTest
    static void testValidarCambioDeEstadoFactura() {
        Factura__c fact= TestUtil.getFactura();
        //Damos de alta el Cobro
        Cobro__c cobro= new Cobro__c();
        cobro.Name = 'prueba';
        cobro.Nombre_sociedad__c='nombre Sociedad';
        cobro.Factura__c= fact.Id;
        //cobro.Concepto__c= 'prueba0';
        cobro.Importe__c=6000;
        cobro.Referencia__c='0000';

    
        Test.startTest();
            insert cobro;
        Test.stopTest();
    }

}