force-app/main/default/objects/AML_Alerts__c/AML_Alerts__c.object-meta.xml
<CustomObject>
    <label>Alerta AML</label>
    <nameField>
        <label>Tipo de alerta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alertas AML</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AML_Alerts__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alertas AML</relationshipLabel>
    <relationshipName>Alertas_AML</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/AMLCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>AMLCreatedDate__c</fullName>
    <description>Fecha de creación en AML</description>
    <label>Fecha de creación en AML</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/AMLLastModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>AMLLastModifiedDate__c</fullName>
    <description>Fecha de última modificación en AML</description>
    <label>Fecha de modificación en AML</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Confirmed__c</fullName>
    <description>Estado de confirmación de la alerta</description>
    <label>Estado de confirmación de la alerta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
                <label>Sí</label>
            </value>
            <value>
                <fullName>NO</fullName>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/ExternalAccountNum__c.field-meta.xml
<CustomField>
    <fullName>ExternalAccountNum__c</fullName>
    <description>Numero identificador del cliente en los sistemas externos a AML</description>
    <externalId>true</externalId>
    <label>Nº Identificador externo cliente</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Número de identificador de la alerta en los sistemas internos de AML</description>
    <externalId>true</externalId>
    <inlineHelpText>Número de identificador de la alerta en los sistemas internos de AML</inlineHelpText>
    <label>Id Externo</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/OfficalAccountIdType__c.field-meta.xml
<CustomField>
    <fullName>OfficalAccountIdType__c</fullName>
    <description>Tipo de identificación oficial del cliente</description>
    <label>Tipo identificador oficial cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
                <default>true</default>
                <label>Documento Nacional de Identidad</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Número de Tarjeta de Residencia</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Número de Pasaporte</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>Código de Identificación Fiscal</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Número de Identidad del Extranjero</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Otros documentos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/OfficialAccountNum__c.field-meta.xml
<CustomField>
    <fullName>OfficialAccountNum__c</fullName>
    <description>Número de la identificación oficial del cliente</description>
    <externalId>true</externalId>
    <label>Nº Identificador cliente</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/PublicComments__c.field-meta.xml
<CustomField>
    <fullName>PublicComments__c</fullName>
    <description>Notas existentes dentro del detalle de la alerta.</description>
    <inlineHelpText>Notas existentes dentro del detalle de la alerta. Comentarios separados por el separador #</inlineHelpText>
    <label>Notas</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AML_Alerts__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EXPIRED</fullName>
                <label>Alerta Expirada</label>
            </value>
            <value>
                <fullName>OPEN</fullName>
                <default>true</default>
                <label>Alerta Abierta</label>
            </value>
            <value>
                <fullName>PROCESS</fullName>
                <label>Alerta En Proceso</label>
            </value>
            <value>
                <fullName>CLOSED</fullName>
                <label>Alerta Cerrada</label>
            </value>
            <value>
                <fullName>TRANSFERED</fullName>
                <label>Alerta Transferida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AmlAlertsManagerV1.cls
@RestResource(urlMapping = '/AmlAlerts/v1/*')
global with sharing class AmlAlertsManagerV1 {

    /*@HttpPost
    global static void createAlert() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        if(request.requestBody != null && request.requestBody.size() > 0) {
            String csvBody = request.requestBody.toString();
            List<String> csvRows = csvBody.split('\n');
            System.debug('csvRows: ' + csvRows);
            List<AML_Alerts__c> alertsList = new List<AML_Alerts__c>();
            Map<String, Account> accsMap = getAccountIds(csvRows);
            System.debug('   ' + accsMap);
            Boolean isFirstRow = true;
            Boolean isErr = false;
            for(String row : csvRows) {
                if(!isFirstRow) {
                    System.debug('row: ' + row);
                    List<String> csvColumns = row.split('\\|');
                    if(csvColumns.size() >= 9) {
                        Account acc = accsMap.get(csvColumns.get(6));
                        if(acc != null) {
                            String createdDateStr = csvColumns.get(3);
                            String stringDate = createdDateStr.substring(6,10) + '-' + 
                                            createdDateStr.substring(3,5) + '-' +
                                            createdDateStr.substring(0,2) + ' ' +
                                            createdDateStr.substring(11,19);
                            DateTime created = DateTime.valueOf(stringDate);

                            String modifiedDateStr = csvColumns.get(4);
                            stringDate = modifiedDateStr.substring(6,10) + '-' + 
                                            modifiedDateStr.substring(3,5) + '-' +
                                            modifiedDateStr.substring(0,2) + ' ' +
                                            modifiedDateStr.substring(11,19);
                            DateTime modified = DateTime.valueOf(stringDate);
                            AML_Alerts__c alert = new AML_Alerts__c(
                                AccountId__c = accsMap.get(csvColumns.get(6)).Id,
                                ExternalId__c = csvColumns.get(0),
                                Name = csvColumns.get(1),
                                Status__c = csvColumns.get(2),
                                AMLCreatedDate__c = created,
                                AMLLastModifiedDate__c = modified,
                                ExternalAccountNum__c = csvColumns.get(5),
                                OfficialAccountNum__c = csvColumns.get(6),
                                OfficalAccountIdType__c = csvColumns.get(7),
                                Confirmed__c = csvColumns.get(8),
                                PublicComments__c = csvColumns.size() == 10 ? csvColumns.get(9) : ''
                            );
                            alertsList.add(alert);
                        }
                    } else {
                        isErr = true;
                        response.statusCode = 404;
                        break;
                    }
                }

                isFirstRow = false;
            }

            if(!isErr) response.statusCode = 201;
            if(alertsList.size() > 0) {
                upsert alertsList ExternalId__c;                
            }
        } else response.statusCode = 404;
    }

    @TestVisible
    private static Map<String, Account> getAccountIds(List<String> csvRows) {
        System.debug('csvRows en getAccountsIds: ' + csvRows);
        Set<String> accountsIds = new Set<String>();
        Boolean isFirstRow = true;
        for(String row : csvRows) {
            if(!isFirstRow) {
                List<String> csvColumns = row.split('\\|');
                if(csvColumns.size() >= 9) {
                    accountsIds.add(csvColumns.get(6));
                }
            }
            isFirstRow = false;
        }
        System.debug('accountsIds: ' + accountsIds);

        List<Account> accounts = [SELECT Id,N_Documento__c,N_Documento__pc FROM Account WHERE (N_Documento__pc IN :accountsIds OR N_Documento__c IN :accountsIds)];
        Map<String, Account> accsMap = new Map<String, Account>();

        for(Account acc : accounts) {
            if(!String.isBlank(acc.N_Documento__c)) accsMap.put(acc.N_Documento__c, acc);
            if(!String.isBlank(acc.N_Documento__pc)) accsMap.put(acc.N_Documento__pc, acc);
        }

        return accsMap;
    }*/

}