force-app/main/default/objects/Opportunity/fields/Observaciones_Resultado_PBC__c.field-meta.xml
<CustomField>
    <fullName>Observaciones_Resultado_PBC__c</fullName>
    <label>Observaciones Resultado PBC</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNumber__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNumber__c</fullName>
    <description>Número de la oportunidad</description>
    <displayFormat>{000000}</displayFormat>
    <label>Número de oportunidad</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resultado_PBC__c.field-meta.xml
<CustomField>
    <fullName>Resultado_PBC__c</fullName>
    <label>Resultado PBC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Resultado_Oportunidad_PBC</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Riesgo_PBC_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Riesgo_PBC_Operacion__c</fullName>
    <label>Riesgo PBC Operación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
                <label>Prohibido</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Alto</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Medio</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Bajo</label>
            </value>
            <value>
                <fullName>ALTO</fullName>
                <isActive>false</isActive>
                <label>ALTO</label>
            </value>
            <value>
                <fullName>BAJO</fullName>
                <isActive>false</isActive>
                <label>BAJO</label>
            </value>
            <value>
                <fullName>MEDIO</fullName>
                <isActive>false</isActive>
                <label>MEDIO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Resultado_Oportunidad_PBC.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OK</fullName>
    </customValue>
    <customValue>
        <fullName>KO</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente Documentación</fullName>
    </customValue>
    <masterLabel>Resultado Oportunidad PBC</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AmlOpportunityRestV1.cls
/**
 * Implementa los servicios que serán consumidos por AML
 * para registrar datos de PBC en las Oportunidades
 *
 * @author Daniel González <dgonzalezantona@deloitte.es>
 */

@RestResource(urlMapping='/AML/v1/Opportunity')
global class AmlOpportunityRestV1 extends DTT_VersionedRestService {

    /* Recursos del Servicio */
   /* @HttpPost
    global static Response httpPost() {
        setHttpRequestContext();
        setHttpResponseContext();
        setHttpPostJSONParams();
        DTT_VersionedRestRequestParameters postParams = (DTT_VersionedRestRequestParameters) getHttpPostParams();

        if(postParams != null) {
            if(String.isBlank((String) postParams.get('proposalNumber'))) {
                setHttpResponseStatusCode(404);
                KOResponse koResp = new KOResponse();
                koResp.status = 'ERR';
                koResp.message = 'El parámetro proposalNumber es obligatorio';
                return koResp;
            }
            try {
                String proposalNumber = (String) postParams.get('proposalNumber');
                List<Opportunity> opps = [
                        SELECT Id, Resultado_PBC__c, Riesgo_PBC_Operacion__c, Observaciones_Resultado_PBC__c
                        FROM Opportunity
                        WHERE OpportunityNumber__c = :proposalNumber
                ];
                if(opps.size() == 0) {
                    setHttpResponseStatusCode(404);
                    KOResponse koResp = new KOResponse();
                    koResp.status = 'ERR';
                    koResp.message = 'No hay ninguna oportunidad con ese proposalNumber';
                    return koResp;
                }

                Opportunity opp = opps.get(0);
                opp.Resultado_PBC__c = (String) postParams.get('manualStatus');
                opp.Riesgo_PBC_Operacion__c = (String) postParams.get('manualRisk');
                opp.Observaciones_Resultado_PBC__c = (String) postParams.get('comments')+ '\n\n' +
                        (String) postParams.get('resolution')+ '\n\n' +
                        (String) postParams.get('conditions');
                update opp;

                setHttpResponseStatusCode(201);
                return null;
            } catch(CalloutException e) {
                setHttpResponseStatusCode(500);
                KOResponse koResp = new KOResponse();
                koResp.status = 'ERR';
                koResp.message = 'Se ha producido un error interno en el servidor. Por favor, contacta con la administración';
                return koResp;
            }
        } else {
            setHttpResponseStatusCode(404);
            KOResponse koResp = new KOResponse();
            koResp.status = 'ERR';
            koResp.message = 'No se ha encontrado párametros de entrada';
            return koResp;
        }
    }*/

}