force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/API_Comercial__c.field-meta.xml
<CustomField>
    <fullName>API_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>API Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_de_pagos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_de_pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Comercial__c.field-meta.xml
<CustomField>
    <fullName>Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <filterItems>
            <field>User.Id</field>
            <operation>equals</operation>
            <value>0055w00000CyTiQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_PlandePagosTrigger_TEST.cls
@IsTest
public class HL_PlandePagosTrigger_TEST {

    @IsTest
    public static void testBeforeInsert() {
    	Plan_de_pagos__c pdp = TestUtil.getPlan_de_Pagos_controller();
        
        Test.startTest();
        Plan_de_pagos__c pp = [SELECT Id, API_Comercial__C, Responsable_Comercial__c FROM Plan_de_pagos__c WHERE Id = :pdp.Id];
        Opportunity opp = [SELECT Id, Promocion__r.Comercial__c, OwnerId FROM Opportunity WHERE Id = :pdp.Oportunidad__c];
        
        System.assertEquals(pp.API_Comercial__c, opp.OwnerId);
        System.assertEquals(pp.Responsable_Comercial__c, opp.Promocion__r.Comercial__c);
        Test.stopTest();
    }
    
    @IsTest
    public static void testBeforeUpdate() {
        Plan_de_pagos__c pdp = TestUtil.getPlan_de_Pagos_controller();
        
        Test.startTest();
        Plan_de_pagos__c pp = [SELECT Id, API_Comercial__C, Responsable_Comercial__c FROM Plan_de_pagos__c WHERE Id = :pdp.Id];
        Opportunity opp = [SELECT Id, Promocion__c, OwnerId FROM Opportunity WHERE Id = :pdp.Oportunidad__c];
        Promocion__c pr = [SELECT Id, Comercial__c FROM Promocion__c WHERE Id = :opp.Promocion__c];
        
        System.assertEquals(pp.API_Comercial__c, opp.OwnerId);
        System.assertEquals(pp.Responsable_Comercial__c, pr.Comercial__c);
        
        Profile prof = [SELECT Id FROM Profile WHERE Name LIKE '%Comercial%' LIMIT 1];
        User u = new User(LastName = 'last',
             Email = 'puser000@amamama.com',
             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             ProfileId = prof.Id);
        insert u;
        
        pr.Comercial__c = u.Id;
        update pr;
        pr = [SELECT Id, Comercial__c FROM Promocion__c WHERE Id = :opp.Promocion__c];
        
        pp.API_Comercial__c = UserInfo.getUserId();
        update pp;
        pp = [SELECT Id, API_Comercial__C, Responsable_Comercial__c FROM Plan_de_pagos__c WHERE Id = :pdp.Id];
        
        System.assertEquals(pp.API_Comercial__c, opp.OwnerId);
        System.assertEquals(pp.Responsable_Comercial__c, pr.Comercial__c);
        Test.stopTest();
    }
    
}