force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/Plan_de_pagos__c.object-meta.xml
<CustomObject>
    <label>Plan de pago</label>
    <nameField>
        <label>Plan de pagos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan de pagos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_de_pagos__c/fields/API_Comercial__c.field-meta.xml
<CustomField>
    <fullName>API_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>API Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_de_pagos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de pagos</relationshipLabel>
    <relationshipName>Plan_de_pagos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plan_de_pagos__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plan_de_pagos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Comercial__c.field-meta.xml
<CustomField>
    <fullName>Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <filterItems>
            <field>User.Id</field>
            <operation>equals</operation>
            <value>0055w00000CyTiQ</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Promociones2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Responsable_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Comercial Aprobador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Comercial API</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>PromocionesDXqm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HL_PlandePagosTrigger.cls
public class HL_PlandePagosTrigger extends TriggerHandler{
    
    protected override void beforeInsert(){
     	List<Plan_de_pagos__c> news = (List<Plan_de_pagos__c>) Trigger.new;
        
        Set<Id> oppIds = new Set<Id>();
        for(Plan_de_pagos__c n : news) 
        	if(n.Oportunidad__c != null && !oppIds.contains(n.Oportunidad__c)) oppIds.add(n.Oportunidad__c);
            
        Map<Id, Opportunity> opps = new Map<Id, Opportunity>([SELECT Id, Promocion__r.Comercial__c, OwnerId FROM Opportunity WHERE Id IN :oppIds]);
        for(Plan_de_pagos__c n : news) {
            n.API_Comercial__c = opps.containsKey(n.Oportunidad__c) ? opps.get(n.Oportunidad__c).OwnerId : null;
            n.Responsable_Comercial__c = opps.containsKey(n.Oportunidad__c) ? opps.get(n.Oportunidad__c).Promocion__r.Comercial__c : null;
        }
    }
    
    protected override void beforeUpdate(){
     	List<Plan_de_pagos__c> news = (List<Plan_de_pagos__c>) Trigger.new;
        
        Set<Id> oppIds = new Set<Id>();
        for(Plan_de_pagos__c n : news) 
        	if(n.Oportunidad__c != null && !oppIds.contains(n.Oportunidad__c)) oppIds.add(n.Oportunidad__c);
            
        Map<Id, Opportunity> opps = new Map<Id, Opportunity>([SELECT Id, Promocion__r.Comercial__c, OwnerId FROM Opportunity WHERE Id IN :oppIds]);
        for(Plan_de_pagos__c n : news) {
            n.API_Comercial__c = opps.containsKey(n.Oportunidad__c) ? opps.get(n.Oportunidad__c).OwnerId : null;
            n.Responsable_Comercial__c = opps.containsKey(n.Oportunidad__c) ? opps.get(n.Oportunidad__c).Promocion__r.Comercial__c : null;
        }
    }
    
}