force-app/main/default/objects/Comision__c/Comision__c.object-meta.xml
<CustomObject>
    <label>Comisión</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Nombre de Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que se le concede la comisión</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Comisiones</relationshipLabel>
    <relationshipName>Comisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/DefinicionComision__c.object-meta.xml
<CustomObject>
    <label>Definición Comisión</label>
    <nameField>
        <displayFormat>DEFC-{0000}</displayFormat>
        <label>Nombre de Definición Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Definiciones comisión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DefinicionComision__c/fields/PorcentajeContrato__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeContrato__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje de comisión para hito de Contrato</description>
    <label>% Contrato</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/fields/PorcentajeEscrituracion__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeEscrituracion__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje de comisión para hito de Escrituración</description>
    <label>% Escrituración</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/fields/PorcentajePosventa__c.field-meta.xml
<CustomField>
    <fullName>PorcentajePosventa__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje de comisión para hito de Posventa</description>
    <label>% Posventa</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/fields/PorcentajeReserva__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeReserva__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje de comisión para hito de Reserva</description>
    <label>% Reserva</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Promoción para la que se establece la definición</description>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Definiciones comisión</relationshipLabel>
    <relationshipName>DefinicionesComisionPromocion</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DefinicionComision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que afecta la definición</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Definiciones comisión</relationshipLabel>
    <relationshipName>DefinicionesComision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/DetalleComision__c.object-meta.xml
<CustomObject>
    <label>Detalle Comisión</label>
    <nameField>
        <displayFormat>DETC-{0000}</displayFormat>
        <label>Nombre de Detalle Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles comisión</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DetalleComision__c/fields/Comision__c.field-meta.xml
<CustomField>
    <fullName>Comision__c</fullName>
    <description>Comisión en la que se engloba cada registro</description>
    <label>Comisión</label>
    <referenceTo>Comision__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Producto de Oportunidad al que está asociada la comisión Fija</description>
    <label>Producto Oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Producto de Oportunidad</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Promoción relacionada</description>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Promoción</relationshipLabel>
    <relationshipName>DetallesComisionPromocion</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que aplica el registro</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_firma_Contrato_Compraventa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Compraventa__c</fullName>
    <label>Fecha firma Contrato Compraventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_firma_Contrato_Reserva__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Reserva__c</fullName>
    <label>Fecha firma Contrato Reserva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaEscrituracionReal__c.field-meta.xml
<CustomField>
    <fullName>FechaEscrituracionReal__c</fullName>
    <label>Fecha escrituración real</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaPosventa__c.field-meta.xml
<CustomField>
    <fullName>FechaPosventa__c</fullName>
    <formula>FechaEscrituracionReal__c +  Promocion__r.DiasPosventa__c</formula>
    <label>Fecha posventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <formula>PricebookEntry.Product2.Promocion__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promoción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Apalabrado</fullName>
                <label>Pre-Reservado</label>
            </value>
            <value>
                <fullName>Bloqueado temporalmente</fullName>
                <label>Reserva en gestión</label>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
            <value>
                <fullName>Canje</fullName>
            </value>
            <value>
                <fullName>Apartado</fullName>
            </value>
            <value>
                <fullName>Asociado</fullName>
                <isActive>false</isActive>
                <label>Asociado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_firma_Contrato_Compraventa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Compraventa__c</fullName>
    <formula>Oportunidad__r.Fecha_firma_Contrato_Compraventa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha firma Contrato Compraventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_firma_Contrato_Reserva__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Reserva__c</fullName>
    <formula>Oportunidad__r.Fecha_firma_Contrato_Reserva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha firma Contrato Reserva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Precio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipologia_Vivienda_Garaje_Trastero_Local__c.field-meta.xml
<CustomField>
    <fullName>Tipologia_Vivienda_Garaje_Trastero_Local__c</fullName>
    <formula>TEXT(Tipo_de_inmueble__r.Tipo__c)</formula>
    <label>Tipología</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/DiasPosventa__c.field-meta.xml
<CustomField>
    <fullName>DiasPosventa__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Días de duración del hito Posventa tras la Fecha Escrituración Real de la oportunidad</description>
    <label>Días Posventa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/RelacionVendedorProductoOportunidad__c.object-meta.xml
<CustomObject>
    <label>Relación Vendedor-Producto Oportunidad</label>
    <nameField>
        <label>Nombre de Relación Vendedor-Producto Opo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relaciones Vendedor-Producto Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/PorcentajeComision__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeComision__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje a aplicar sobre el importe de este producto para este vendedor. Sobre el importe resultante, se aplicará el porcentaje de comisión a conceder</description>
    <label>Porcentaje comisión</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto de oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProductoOportunidad</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/Titular__c.field-meta.xml
<CustomField>
    <fullName>Titular__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si este producto contabiliza en los objetivos de este Vendedor</description>
    <label>Titular</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProducto_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchCalculoComisiones.cls
/**
@description
<pre>
Creación diaria de objetivos</br>
DATE       	AUTHOR     	DESCRIPTION<br/>                 
20/01/2021 	LCS - BCF   Created.                         
</pre>
@author Leadclic Solutions
@date 20/01/2021
*/
global class BatchCalculoComisiones implements Database.Batchable<sObject>, Schedulable{
    
    Map<Id, Set<RelacionVendedorProductoOportunidad__c>> mProductos = new Map<Id, Set<RelacionVendedorProductoOportunidad__c>>(); //Mapa Promocion, lista de productos 
    Map<DefinicionComision__c, Set<RelacionVendedorProductoOportunidad__c>> mProductosVendedor = new Map<DefinicionComision__c, Set<RelacionVendedorProductoOportunidad__c>>(); //Mapa Definicion Comision, lista de Productos
    Map<RelacionVendedorProductoOportunidad__c, DetalleComision__c> mComisiones = new Map<RelacionVendedorProductoOportunidad__c, DetalleComision__c>(); //Mapa Producto, Definicion Comision
    Map<Id, Comision__c> mComisionVendedor = new Map<Id, Comision__c>(); //Mapa Vendedor, Comision
    
    global void execute(SchedulableContext sc){
        BatchCalculoComisiones b = new BatchCalculoComisiones();
        Database.executebatch(b, 2000);
    }
    
    global List<sObject> start(Database.BatchableContext bc) {
        List<sObject> lScope = new List<sObject>();
        String mesActual = Date.today().month().format();
        String yearActual = Date.today().year().format();
        
        //Añadimos Productos Relacionados
        lScope.addAll([SELECT id, Titular__c, PorcentajeComision__c, vendedor__c, ProductoOportunidad__r.Product2.Estado__c, ProductoOportunidad__r.Product2.Tipologia_Vivienda_Garaje_Trastero_Local__c, 
                       ProductoOportunidad__r.Product2.Precio__c, ProductoOportunidad__r.Product2.Promocion__c, ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c, ProductoOportunidad__r.UnitPrice,
                       ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c, ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c, ProductoOportunidad__r.Opportunity.FechaPosventa__c, ProductoOportunidad__r.Opportunity.Promocion__r.DiasPosventa__c, ProductoOportunidad__r.Opportunity.StageName
                       FROM RelacionVendedorProductoOportunidad__c                       
                       WHERE vendedor__c != null AND ((ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c = THIS_MONTH AND ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c = THIS_YEAR) OR (ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c = THIS_MONTH 
                             AND ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c = THIS_YEAR) OR (ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c = THIS_MONTH AND ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c = THIS_YEAR) 
                             OR (ProductoOportunidad__r.Opportunity.FechaPosventa__c = THIS_MONTH AND ProductoOportunidad__r.Opportunity.FechaPosventa__c = THIS_YEAR))]);
        
        //Añadimos Definicion de Comisiones
        lScope.addAll([SELECT Id, PorcentajeReserva__c, PorcentajeContrato__c, PorcentajeEscrituracion__c, PorcentajePosventa__c, Vendedor__c, Promocion__c, Mes__c, Year__c
                       FROM DefinicionComision__c 
                       WHERE Mes__c = :mesActual AND Year__c = :yearActual AND Activo__c = true AND Vendedor__c != null AND Promocion__c != null AND Mes__c != null AND Year__c != null]);
        
        //Añadimos Detalle Comision
        lScope.addAll([SELECT id, Name, Vendedor__c, Mes__c, Year__c, Importe__c, ProductoOportunidad__c, Promocion__c, ImporteContrato__c, ImporteEscrituracion__c, ImportePosventa__c, ImporteReserva__c
                       FROM DetalleComision__c 
                       WHERE Mes__c = :mesActual AND Year__c = :yearActual AND Tipo__c = 'Fija' AND Vendedor__c != null AND Promocion__c != null AND Mes__c != null AND Year__c != null]);
        
        //Añadimos Comision
        lScope.addAll([SELECT id, Name, Vendedor__c, Mes__c, Year__c
                       FROM Comision__c 
                       WHERE Mes__c = :mesActual AND Year__c = :yearActual AND Vendedor__c != null AND Mes__c != null AND Year__c != null]);
        
        return lScope;
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
        
        Set<DefinicionComision__c> sDefinicionCom = new Set<DefinicionComision__c>();
        Set<DetalleComision__c> sDetalleCom = new Set<DetalleComision__c>();
        Set<Comision__c> sComisiones = new Set<Comision__c>();
        Set<RelacionVendedorProductoOportunidad__c> sProducto = new Set<RelacionVendedorProductoOportunidad__c>();
        
        for(sObject sco : scope){
            switch on sco{
                when RelacionVendedorProductoOportunidad__c prod{
                    sProducto.add(prod);
                }
                when DefinicionComision__c def{
                    sDefinicionCom.add(def);
                }
                when DetalleComision__c det{
                	sDetalleCom.add(det);
                }
                when Comision__c com{
                    sComisiones.add(com);
                }
            }
        }
        
        //Crear mapa <Promocion, lista de productos>
        for(RelacionVendedorProductoOportunidad__c producto : sProducto){
            
            if(mProductos.containsKey(producto.ProductoOportunidad__r.Product2.Promocion__c)){
                Set<RelacionVendedorProductoOportunidad__c> sProductos = mProductos.get(producto.ProductoOportunidad__r.Product2.Promocion__c);
                sProductos.add(producto);
                mProductos.put(producto.ProductoOportunidad__r.Product2.Promocion__c, sProductos);
                
            }else{
                Set<RelacionVendedorProductoOportunidad__c> sProductos = new Set<RelacionVendedorProductoOportunidad__c>();
                sProductos.add(producto);
                mProductos.put(producto.ProductoOportunidad__r.Product2.Promocion__c, sProductos);
            }
        }
        
        //Crear mapa <Definicion Comision, Lista de productos>
        for(DefinicionComision__c definicion : sDefinicionCom){
            
            if(mProductos.containsKey(definicion.Promocion__c)){
                for(RelacionVendedorProductoOportunidad__c producto : mProductos.get(definicion.Promocion__c)){
                    
                    if(producto.vendedor__c == definicion.vendedor__c){
                        
                        if(mProductosVendedor.containsKey(definicion)){
                            Set<RelacionVendedorProductoOportunidad__c> sProductosVendedor = mProductosVendedor.get(definicion);
                        	sProductosVendedor.add(producto);
                        	mProductosVendedor.put(definicion, sProductosVendedor);
                            
                        }else{
                            Set<RelacionVendedorProductoOportunidad__c> sProductosVendedor = new Set<RelacionVendedorProductoOportunidad__c>();
                        	sProductosVendedor.add(producto);
                        	mProductosVendedor.put(definicion, sProductosVendedor);
                        }
                    }
                }
                
            }else{ //No hay productos de la promocion de la comisión
                Set<RelacionVendedorProductoOportunidad__c> sProductosVendedor = new Set<RelacionVendedorProductoOportunidad__c>();
                mProductosVendedor.put(definicion, sProductosVendedor);
            }
        }
        
        //Crear mapa Vendedor, Comision
        for(Comision__c comision : sComisiones){
            mComisionVendedor.put(comision.Vendedor__c, comision);
        }
        
        //Crear mapa <Producto, Detalle de Comision>
        for(DetalleComision__c detalle : sDetalleCom){
            for(RelacionVendedorProductoOportunidad__c producto : sProducto){
                if(detalle.ProductoOportunidad__c == producto.ProductoOportunidad__c){
                    mComisiones.put(producto, detalle);
                }
            }
        }
        
        //Calculo Detalles de comisiones
        Set<DetalleComision__c> sNuevosDetallesComision = new Set<DetalleComision__c>(); //Nuevos Detalles
        
        for(DefinicionComision__c def : sDefinicionCom){
            
            if(mProductosVendedor.get(def) != null){
                for(RelacionVendedorProductoOportunidad__c producto : mProductosVendedor.get(def)){
                    
                    DetalleComision__c detalle = mComisiones.get(producto); 
                    
                    if(detalle == null){ //Si no existe un Detalle para ese producto se inicializa
                        DetalleComision__c nuevoDetalle = new DetalleComision__c();
                        nuevoDetalle.Vendedor__c = def.Vendedor__c;
                        nuevoDetalle.Promocion__c = def.Promocion__c;
                        nuevoDetalle.Mes__c = Date.today().month().format();
                        nuevoDetalle.Year__c = Date.today().year().format();
                        nuevoDetalle.Tipo__c = 'Fija';
                        nuevoDetalle.Comision__c = mComisionVendedor.get(producto.Vendedor__c).Id;
                        nuevoDetalle.ProductoOportunidad__c = producto.ProductoOportunidad__c;
                        
                        sNuevosDetallesComision.add(nuevoDetalle);
                        detalle = nuevoDetalle;
                    }
                    
                    detalle.ImporteReserva__c = 0;
                    detalle.ImporteContrato__c = 0;
                    detalle.ImporteEscrituracion__c = 0;
                    detalle.ImportePosventa__c = 0;
                    
                    //Recalculo para productos que no tengan la opp cancelada
                    if(producto.ProductoOportunidad__r.Opportunity.StageName != 'Cancelada'){
                        //Calculo para opp con fechas (reserva, contrato, escritura, posventa) en el mes actual
                        if(producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c != null && producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c.month() == Date.today().month() && producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Reserva__c.year() == Date.today().year()){
                            detalle.ImporteReserva__c = calculoImporte(producto.ProductoOportunidad__r.UnitPrice, producto.PorcentajeComision__c, def.PorcentajeReserva__c);
                            
                        }if(producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c != null && producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c.month() == Date.today().month() && producto.ProductoOportunidad__r.Opportunity.Fecha_firma_Contrato_Compraventa__c.year() == Date.today().year()){
                            detalle.ImporteContrato__c = calculoImporte(producto.ProductoOportunidad__r.UnitPrice, producto.PorcentajeComision__c, def.PorcentajeContrato__c);
                            
                        }if(producto.ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c != null && producto.ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c.month() == Date.today().month() && producto.ProductoOportunidad__r.Opportunity.FechaEscrituracionReal__c.year() == Date.today().year()){
                            detalle.ImporteEscrituracion__c = calculoImporte(producto.ProductoOportunidad__r.UnitPrice, producto.PorcentajeComision__c, def.PorcentajeEscrituracion__c);
                            
                        }if(producto.ProductoOportunidad__r.Opportunity.Promocion__r.DiasPosventa__c != null && producto.ProductoOportunidad__r.Opportunity.Promocion__r.DiasPosventa__c != 0 && 
                            producto.ProductoOportunidad__r.Opportunity.FechaPosventa__c != null && producto.ProductoOportunidad__r.Opportunity.FechaPosventa__c.month() == Date.today().month() && producto.ProductoOportunidad__r.Opportunity.FechaPosventa__c.year() == Date.today().year()){
                                
							detalle.ImportePosventa__c = calculoImporte(producto.ProductoOportunidad__r.UnitPrice, producto.PorcentajeComision__c, def.PorcentajePosventa__c);
                            
                        }
                    }
                    
                }
            }
        }
        
        List<DetalleComision__c> lUpdateDetalles = new List<DetalleComision__c>();
        lUpdateDetalles.addAll(sDetalleCom);
        
        List<DetalleComision__c> lInsertDetalles = new List<DetalleComision__c>();
        lInsertDetalles.addAll(sNuevosDetallesComision);
        
        insert lInsertDetalles;
        update lUpdateDetalles;
        
    }
    
    private Decimal calculoImporte(Decimal precio, Decimal porcentajeProductoOpp, Decimal porcentajeDefinicion){
        //Multiplicacion = precio del producto de opp * porcentaje comisión de RVPO * porcentaje Definicion de comision
        return precio * (porcentajeProductoOpp/100) * (porcentajeDefinicion/100);
    }
 
    global void finish(Database.BatchableContext bc){}
    
}