force-app/main/default/objects/Comision__c/Comision__c.object-meta.xml
<CustomObject>
    <label>Comisión</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Nombre de Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comisiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comision__c/fields/ImporteContrato__c.field-meta.xml
<CustomField>
    <fullName>ImporteContrato__c</fullName>
    <description>Importe comisiones por Contrato hasta el momento</description>
    <label>Importe Contrato</label>
    <summarizedField>DetalleComision__c.ImporteContrato__c</summarizedField>
    <summaryFilterItems>
        <field>DetalleComision__c.Tipo__c</field>
        <operation>equals</operation>
        <value>Fija</value>
    </summaryFilterItems>
    <summaryForeignKey>DetalleComision__c.Comision__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Comision__c/fields/ImporteReserva__c.field-meta.xml
<CustomField>
    <fullName>ImporteReserva__c</fullName>
    <description>Importe comisiones por Reserva hasta el momento</description>
    <label>Importe Reserva</label>
    <summarizedField>DetalleComision__c.ImporteReserva__c</summarizedField>
    <summaryFilterItems>
        <field>DetalleComision__c.Tipo__c</field>
        <operation>equals</operation>
        <value>Fija</value>
    </summaryFilterItems>
    <summaryForeignKey>DetalleComision__c.Comision__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Comision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que se le concede la comisión</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Comisiones</relationshipLabel>
    <relationshipName>Comisiones</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/DetalleComision__c.object-meta.xml
<CustomObject>
    <label>Detalle Comisión</label>
    <nameField>
        <displayFormat>DETC-{0000}</displayFormat>
        <label>Nombre de Detalle Comisión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles comisión</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DetalleComision__c/fields/Comision__c.field-meta.xml
<CustomField>
    <fullName>Comision__c</fullName>
    <description>Comisión en la que se engloba cada registro</description>
    <label>Comisión</label>
    <referenceTo>Comision__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/ImporteContrato__c.field-meta.xml
<CustomField>
    <fullName>ImporteContrato__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Comisión acumulada para el Producto Oportunidad en hito Contrato</description>
    <label>Importe Contrato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/ImporteReserva__c.field-meta.xml
<CustomField>
    <fullName>ImporteReserva__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Comisión acumulada para el Producto Oportunidad en hito Reserva</description>
    <label>Importe Reserva</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Producto de Oportunidad al que está asociada la comisión Fija</description>
    <label>Producto Oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Producto de Oportunidad</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Promoción relacionada</description>
    <label>Promoción</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Promoción</relationshipLabel>
    <relationshipName>DetallesComisionPromocion</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DetalleComision__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Vendedor al que aplica el registro</description>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Detalles comisión</relationshipLabel>
    <relationshipName>DetallesComision</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Asignacion_participantes__c.field-meta.xml
<CustomField>
    <fullName>Asignacion_participantes__c</fullName>
    <description>Suma de los porcentajes de asignación de todos los participantes de la oportunidad</description>
    <inlineHelpText>Suma de los porcentajes de asignación de todos los participantes de la oportunidad</inlineHelpText>
    <label>% Asignacion participantes</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cuenta_Bancaria_de_mandato__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Bancaria_de_mandato__c</fullName>
    <label>Cuenta Bancaria de mandato (IBAN)</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_firma_Contrato_Compraventa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Compraventa__c</fullName>
    <label>Fecha firma Contrato Compraventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_firma_Contrato_Reserva__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Reserva__c</fullName>
    <label>Fecha firma Contrato Reserva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaEscrituracionReal__c.field-meta.xml
<CustomField>
    <fullName>FechaEscrituracionReal__c</fullName>
    <label>Fecha escrituración real</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaPosventa__c.field-meta.xml
<CustomField>
    <fullName>FechaPosventa__c</fullName>
    <formula>FechaEscrituracionReal__c +  Promocion__r.DiasPosventa__c</formula>
    <label>Fecha posventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastStageName__c.field-meta.xml
<CustomField>
    <fullName>LastStageName__c</fullName>
    <label>LastStageName</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <formula>PricebookEntry.Product2.Promocion__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promoción</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participante__c/Participante__c.object-meta.xml
<CustomObject>
    <label>Participante</label>
    <nameField>
        <label>Nombre de Participante de la compra</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participante__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Participantes (Opportunity)</relationshipLabel>
    <relationshipName>Participantes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participante__c/fields/Porcentaje_de_participacion__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_de_participacion__c</fullName>
    <label>Porcentaje de participación</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Libre</fullName>
            </value>
            <value>
                <fullName>Apalabrado</fullName>
                <label>Pre-Reservado</label>
            </value>
            <value>
                <fullName>Bloqueado temporalmente</fullName>
                <label>Reserva en gestión</label>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
            <value>
                <fullName>Canje</fullName>
            </value>
            <value>
                <fullName>Apartado</fullName>
            </value>
            <value>
                <fullName>Asociado</fullName>
                <isActive>false</isActive>
                <label>Asociado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_firma_Contrato_Compraventa__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Compraventa__c</fullName>
    <formula>Oportunidad__r.Fecha_firma_Contrato_Compraventa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha firma Contrato Compraventa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_firma_Contrato_Reserva__c.field-meta.xml
<CustomField>
    <fullName>Fecha_firma_Contrato_Reserva__c</fullName>
    <formula>Oportunidad__r.Fecha_firma_Contrato_Reserva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha firma Contrato Reserva</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Promocion__c.field-meta.xml
<CustomField>
    <fullName>Promocion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promocion</label>
    <referenceTo>Promocion__c</referenceTo>
    <relationshipLabel>Inmuebles</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Inmueble.recordType-meta.xml
<RecordType>
    <fullName>Inmueble</fullName>
    <active>true</active>
    <label>Inmueble</label>
</RecordType>

force-app/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los datos de las promociones</description>
    <label>Promocion</label>
    <nameField>
        <label>Nombre comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promociones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Promocion__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Estados_de_promocion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/RelacionVendedorProductoOportunidad__c.object-meta.xml
<CustomObject>
    <label>Relación Vendedor-Producto Oportunidad</label>
    <nameField>
        <label>Nombre de Relación Vendedor-Producto Opo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relaciones Vendedor-Producto Oportunidad</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/PorcentajeComision__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeComision__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Porcentaje a aplicar sobre el importe de este producto para este vendedor. Sobre el importe resultante, se aplicará el porcentaje de comisión a conceder</description>
    <label>Porcentaje comisión</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/ProductoOportunidad__c.field-meta.xml
<CustomField>
    <fullName>ProductoOportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto de oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProductoOportunidad</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RelacionVendedorProductoOportunidad__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <referenceTo>Vendedor__c</referenceTo>
    <relationshipLabel>Relaciones Vendedor-Producto Oportunidad</relationshipLabel>
    <relationshipName>RelacionesVendedorProducto_Oportunidad</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Estados_de_promocion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alta promoción</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración técnica</fullName>
    </customValue>
    <customValue>
        <fullName>Configuración comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Documentación marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Aprobar comercializacion</fullName>
        <label>Aprobar comercialización</label>
    </customValue>
    <customValue>
        <fullName>Ejecución del proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Sin Iniciar</fullName>
    </customValue>
    <customValue>
        <fullName>Pre_Reservas</fullName>
        <label>Pre-Reservas</label>
    </customValue>
    <customValue>
        <fullName>Reservas</fullName>
    </customValue>
    <customValue>
        <fullName>Compra_Venta</fullName>
        <label>Compra-Venta</label>
    </customValue>
    <customValue>
        <fullName>100% Vendida</fullName>
    </customValue>
    <customValue>
        <fullName>Escriturada</fullName>
    </customValue>
    <customValue>
        <fullName>Proyecto desestimado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Últimas unidades</fullName>
    </customValue>
    <masterLabel>Estados de promoción</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HL_Opportunity.cls
public class HL_Opportunity extends TriggerHandler {

    protected override void before() {
        for (Opportunity opportunity : (List<Opportunity>) Trigger.New) {
            //Realizamos la validacion de la cuenta bancaria
            if (opportunity.Cuenta_Bancaria_de_mandato__c != null && !String.isBlank(opportunity.Cuenta_Bancaria_de_mandato__c)) {
                if (opportunity.Cuenta_Bancaria_de_mandato__c.substring(0, 1).isAlpha()) {
                    //Si el IBAN introducido cuenta con guiones o espacios en blanco, estos se suprimen
                        opportunity.Cuenta_Bancaria_de_mandato__c=opportunity.Cuenta_Bancaria_de_mandato__c.replace(' ' ,'');
    					opportunity.Cuenta_Bancaria_de_mandato__c=opportunity.Cuenta_Bancaria_de_mandato__c.replace('-' ,'');
                    if (opportunity.Cuenta_Bancaria_de_mandato__c.substring(0, 2).equals('ES')) {
                        boolean validacion = ValidadorUtil.esCuentaBancaria(opportunity.Cuenta_Bancaria_de_mandato__c);
                        if (!validacion) {
                            if (!System.Test.isRunningTest()) {
                                opportunity.addError('El Nº de cuenta o no es válido, por favor revíselo');
                            }
                        }
                    }
                } else {
                    opportunity.addError('El Nº de cuenta no tiene el IBAN correctamente informado, por favor revíselo');
                }

            }
        }
    }
	
    
    protected override void beforeUpdate() {
        Map<Id, Opportunity> olds = (Map<Id, Opportunity>) Trigger.oldMap;
        Map<Id, Opportunity> news = (Map<Id, Opportunity>) Trigger.newMap;
        
        for(Opportunity o : news.values()) {
            if(olds.get(o.Id).StageName != o.StageName)
                o.LastStageName__c = olds.get(o.Id).StageName;
        }
        
        List <Participante__c> parts = [SELECT Porcentaje_de_participacion__c, Opportunity__c FROM Participante__c WHERE Opportunity__c = :(List<Opportunity>) Trigger.New];
        Map<Id, List<Participante__c>> participantesMap = new Map<Id, List<Participante__c>>();
        for(Participante__c p : parts) {
            if(!participantesMap.containsKey(p.Opportunity__c)) participantesMap.put(p.Opportunity__c, new List<Participante__c>());
            participantesMap.get(p.Opportunity__c).add(p);
        }
        
        for (Opportunity opportunity : (List<Opportunity>) Trigger.New) {
            //JNM 18/07/2019. Introducimos validación para que el porcentaje de asignación de participantes sea del 100%
            decimal sumaPart = 0.0;

            //Buscamos los participantes de la promoción
            List<Participante__c> participantes = participantesMap.get(opportunity.Id);
            if(participantes != null && !participantes.isEmpty()){
                //Recorremos los participantes y recogemos el valor del porcentaje de asignación
                for (Participante__c p : participantes) {
                    sumaPart = sumaPart + p.Porcentaje_de_participacion__c;
                }
                
                if(!participantes.isEmpty() && olds.get(opportunity.Id).StageName != opportunity.StageName)
                    if(sumaPart < 100 || sumaPart > 100)
                        opportunity.addError('El porcentaje de asignación de los participantes debe ser del 100%');

                //Actualizamos el valor de la suma en el campo que tiene el recuento
                opportunity.Asignacion_participantes__c = sumaPart;
            }
        }
    }

    public static void afterUpdate(list<Opportunity> lNewOpp, map<Id, Opportunity> mOldOpp) {
        system.debug('OPORTUNIDAD -- Entra en after update ');
        /*actualizarEstado((Map<id, Opportunity>) Trigger.NewMap, (Map<id, Opportunity>) Trigger.OldMap);*/
        
        recalculoComisiones(lNewOpp, mOldOpp);

        // SI EL ESTADO ES RESERVA PENDIENTE DE COBRO LLAMAR A AML
        /*Map<Id, Opportunity> opps = (Map<Id, Opportunity>) Trigger.NewMap;
        Map<Id, Opportunity> oldOpps = (Map<Id, Opportunity>) Trigger.OldMap;
        if(!Test.isRunningTest()) {
            for(Id oppId : opps.keySet()) {
                Opportunity opp = opps.get(oppId);
                Opportunity oldOpp = oldOpps.get(oppId);
                if (opp.StageName != oldOpp.StageName && opp.StageName == 'Reserva Pdte. Cobro') {
                    sendAmlRequest(opp.Id);
                }
            }
        }*/
    }

    /********************* Métodos auxiliares *****************/

    /*private void actualizarEstado(Map<id, Opportunity> newMap, Map<id, Opportunity> oldMap) {
        system.debug('Entre metodo actualizar estados');
        Set<id> setOportunidades = new Set<id>();
        Set<id> setProductosOportunidad = new Set<id>();

        //Obtener los IDs de las oportunidades modificadas
        for (id opp : newMap.keySet())
            setOportunidades.add(opp);
        

        //Obtener los productos de oportunidad de las oportunidades modificadas
        Map<id, OpportunityLineItem> productosOportunidad = new Map<id, OpportunityLineItem>([
                SELECT id,name, Product2Id
                FROM OpportunityLineItem
                WHERE OpportunityId IN :setOportunidades
        ]);

        //Obtener los Ids de los inmuebles asociados
        for (id popp : productosOportunidad.keySet())
            setProductosOportunidad.add(productosOportunidad.get(popp).Product2Id);
        

        //Obtener los inmuebles relacionados con las oportunidades modificadas
        Map<id, Product2> mapInmuebles = new Map<id, Product2>([SELECT id, estado__c FROM Product2 WHERE id IN :setProductosOportunidad]);
        List<Product2> inmueblesToUpdate = new List<Product2>();
        //Recorrer oportunidades
        for (id opp : newMap.keySet()) {
            if (newMap.get(opp).StageName == 'Cancelada' && newMap.get(opp).StageName != oldMap.get(opp).StageName) {
                for (id inm : mapInmuebles.keySet()) {
                    Product2 inmueble = new Product2();
                    inmueble.id = inm;
                    inmueble.Estado__c = 'Libre';
                    inmueblesToUpdate.add(inmueble);

                    /*
                    if (mapInmuebles.get(inm).Estado__c == 'Apalabrado') {
                        System.debug('Estado inmueble --> Apalabrado -- Libre');
                        Product2 inmueble = new Product2();

                        inmueble.id = inm;
                        inmueble.Estado__c = 'Libre';

                        mapInmueblesUpdate.put(inm, inmueble);

                    } else if (mapInmuebles.get(inm).Estado__c == 'Bloqueado') {
                        System.debug('Estado inmueble --> Bloqueado -- Cancelado');
                        Product2 inmueble = new Product2();

                        inmueble.id = inm;
                        inmueble.Estado__c = 'Cancelado';

                        mapInmueblesUpdate.put(inm, inmueble);
                    }
                    */

               /* }

            }

        }//Fin for oportunidades

        update inmueblesToUpdate;
    }*/

    /*@Future(callout=true)
    private static void sendAmlRequest(Id oppId) {
        AmlCheckOportunidadWSV1 amlClient = new AmlCheckOportunidadWSV1();
        amlClient.authentication();
        amlClient.createProposal(oppId);
    }*/
    
    //Creado BCF 04-02-2022
    public static void recalculoComisiones(List<Opportunity> lNewOpp, Map<Id, Opportunity> oldMap){
        
        Set<Opportunity> sOportunidades = new Set<Opportunity>();
        Map<Id, Opportunity> mOportunidades = new Map<Id, Opportunity>();
        Set<OpportunityLineItem> sProductosOportunidad = new Set<OpportunityLineItem>();

        //Obtener los IDs de las oportunidades modificadas con fechas anteoriores al mes y año actual
        for (Opportunity opp : lNewOpp){
            
            if(opp.StageName == 'Cancelada' && opp.StageName != oldMap.get(opp.Id).StageName && 
               ((opp.Fecha_firma_Contrato_Reserva__c != null && opp.Fecha_firma_Contrato_Reserva__c.month() < Date.today().month() && opp.Fecha_firma_Contrato_Reserva__c.year() == Date.today().year()) ||
                (opp.Fecha_firma_Contrato_Reserva__c != null && opp.Fecha_firma_Contrato_Reserva__c.year() < Date.today().year()) || (opp.Fecha_firma_Contrato_Compraventa__c != null && opp.Fecha_firma_Contrato_Compraventa__c.year() < Date.today().year()) ||
                (opp.Fecha_firma_Contrato_Compraventa__c != null && opp.Fecha_firma_Contrato_Compraventa__c.month() < Date.today().month() && opp.Fecha_firma_Contrato_Compraventa__c.year() == Date.today().year()) || 
                (opp.FechaEscrituracionReal__c != null && opp.FechaEscrituracionReal__c.month() < Date.today().month() && opp.FechaEscrituracionReal__c.year() == Date.today().year()) ||
                (opp.FechaEscrituracionReal__c != null && opp.FechaEscrituracionReal__c.year() < Date.today().year()) || (opp.FechaPosventa__c != null && opp.FechaPosventa__c.year() < Date.today().year()) ||
                (opp.FechaPosventa__c != null && opp.FechaPosventa__c.month() < Date.today().month() && opp.FechaPosventa__c.year() == Date.today().year()) )){
                    
                sOportunidades.add(opp);
                mOportunidades.put(opp.Id, opp);
            }
        }
        
        if(sOportunidades != null && !sOportunidades.isEmpty()){
            
            //Puede haber 2 vendedores con el mismo producto
            Map<Id, OpportunityLineItem> mProductosOportunidad = new Map<Id, OpportunityLineItem>([SELECT Id, name, Product2Id, OpportunityId, UnitPrice
                                                                                                   FROM OpportunityLineItem
                                                                                                   WHERE OpportunityId IN :sOportunidades]);
    
            List<RelacionVendedorProductoOportunidad__c> lRelacionVendedor = ([SELECT id, Vendedor__c, ProductoOportunidad__c, PorcentajeComision__c
                                                                               FROM RelacionVendedorProductoOportunidad__c
                                                                               WHERE ProductoOportunidad__c IN :mProductosOportunidad.keySet()]); //sProductosOportunidad
            
            Map<Id,List<OpportunityLineItem>> mProductosVendedor = new Map<id, List<OpportunityLineItem>>(); //Vendedor, lista productos Opp
            
            for(RelacionVendedorProductoOportunidad__c relacion : lRelacionVendedor){
                if(mProductosVendedor.containsKey(relacion.Vendedor__c)){
                    List<OpportunityLineItem> lProductoOpp = mProductosVendedor.get(relacion.Vendedor__c);
                    lProductoOpp.add(mProductosOportunidad.get(relacion.ProductoOportunidad__c));
                    mProductosVendedor.put(relacion.Vendedor__c, lProductoOpp);

                }else{
                    List<OpportunityLineItem> lProductoOpp = new List<OpportunityLineItem>();
                    lProductoOpp.add(mProductosOportunidad.get(relacion.ProductoOportunidad__c));
                    mProductosVendedor.put(relacion.Vendedor__c, lProductoOpp);
                }
            }
            
            String mesActual = Date.today().month().format();
            String yearActual = Date.today().year().format();
            
            List<DetalleComision__c> lDetalles = ([SELECT Vendedor__c, ProductoOportunidad__c, Promocion__c, ImporteContrato__c, ImporteReserva__c,  ImporteEscrituracion__c, ImportePosventa__c, Comision__c, Mes__c
                                                   FROM DetalleComision__c
                                                   WHERE ProductoOportunidad__c IN :mProductosOportunidad.keySet() AND ((Mes__c != :mesActual AND Year__C = :yearActual) OR Year__c != :yearActual)]);
            
            Set<Id> SVendedores = new Set<Id>();
            for(DetalleComision__c det : lDetalles){
                if(!SVendedores.contains(det.Vendedor__c))
                	SVendedores.add(det.Vendedor__c);
            }
                     
            Map<DetalleComision__c, OpportunityLineItem> mProductosDetalle = new Map<DetalleComision__c, OpportunityLineItem>();// Mapa detalle, producto
            
            //Puede haber 2 vendedores con el mismo producto
            for(DetalleComision__c det : lDetalles){
                if(mProductosVendedor.containsKey(det.Vendedor__c)){
                    for(OpportunityLineItem prod : mProductosVendedor.get(det.Vendedor__c)){
                        if(prod.Id == det.ProductoOportunidad__c){
                            mProductosDetalle.put(det, prod);
                        }
                    }
                }
            }
            
            for(DetalleComision__c det : lDetalles){
                if(!mProductosDetalle.containsKey(det)){
                    mProductosDetalle.put(det, mProductosOportunidad.get(det.ProductoOportunidad__c));
                }
            }
           
            //Mapa vendedor lista de detalles
            Map<Id, List<DetalleComision__c>> mVendedorDetalle = new Map<Id, List<DetalleComision__c>>();
            
            for(DetalleComision__c det : lDetalles){
                if(mVendedorDetalle.containsKey(det.Vendedor__c)){
                    List<DetalleComision__c> lDetalleComision = mVendedorDetalle.get(det.Vendedor__c);
                    lDetalleComision.add(det);
                    mVendedorDetalle.put(det.Vendedor__c, lDetalleComision);

                }else{
                    List<DetalleComision__c> lDetalleComision = new List<DetalleComision__c>();
                    lDetalleComision.add(det);
                    mVendedorDetalle.put(det.Vendedor__c, lDetalleComision);
                }
            }
            
            //comisiones
            List<Comision__c> lComisiones = ([SELECT Id, Mes__c, Year__c, Vendedor__c 
                                              FROM Comision__c 
                                              WHERE Mes__c = :Date.today().month().format() AND Year__c = :Date.today().year().format() AND Vendedor__c IN :SVendedores]);
            
            //Mapa Vendedor, Comision Actual
            Map<Id, Comision__c> mVendedorComisionActual = new Map<Id, Comision__c>(); 
            
            for(Comision__c com : lComisiones){
                if(!mVendedorComisionActual.containsKey(com.Vendedor__c)){
                    mVendedorComisionActual.put(com.Vendedor__c, com);
                }
            }
            
            Set<DetalleComision__c> sDetallesNuevos = new Set<DetalleComision__c>(); //Sumar importes de todos los productos x vendedor sin producto
            
            for(Id vendedor : mVendedorDetalle.KeySet()){
                double total = 0; //Inicializar precio total de la suma de los productos de un mismo vendedor
                
                DetalleComision__c nuevo = new DetalleComision__c();
                nuevo.Vendedor__c = vendedor;
                nuevo.Mes__c = Date.today().month().format();
                nuevo.Year__c = Date.today().year().format();
                nuevo.Tipo__c = 'Extra';
                nuevo.Comision__c = mVendedorComisionActual.get(vendedor).Id;
                
                for(DetalleComision__c det : mVendedorDetalle.get(vendedor)){
                        
                    total += det.ImporteReserva__c;
                    total += det.ImporteContrato__c;
                    total += det.ImporteEscrituracion__c;
                    total += det.ImportePosventa__c;
                        
                    nuevo.Concepto__c = 'Cancelación de la oportunidad ' + mOportunidades.get(mProductosOportunidad.get(det.ProductoOportunidad__c).OpportunityId).Name; //Mirar nombre de opp
                    nuevo.Importe__c = -total;
                    nuevo.Promocion__c = det.Promocion__c; 
                    
                }
                sDetallesNuevos.add(nuevo);
            }
            
            List<DetalleComision__c> lUpdateDetalles = new List<DetalleComision__c>();
        	lUpdateDetalles.addAll(sDetallesNuevos);
            insert lUpdateDetalles;
            
        }
    }

}