force-app/main/default/objects/Contact/fields/N_Documento__c.field-meta.xml
<CustomField>
    <fullName>N_Documento__c</fullName>
    <label>Nº Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nacionalidad</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Contactos (Nacionalidad)</relationshipLabel>
    <relationshipName>Contactos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Contactos (País)</relationshipLabel>
    <relationshipName>Contactos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hombre</fullName>
            </value>
            <value>
                <fullName>Mujer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Tipo_de_documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_documento__c</fullName>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_documento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>Nombre de País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paises</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO2__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO2__c</fullName>
    <label>Código ISO 2</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3__c</fullName>
    <label>Código ISO 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pais__c/fields/Codigo_ISO3_num__c.field-meta.xml
<CustomField>
    <fullName>Codigo_ISO3_num__c</fullName>
    <label>Código ISO 3 num</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_de_documento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Nº Contribuyente</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <masterLabel>Tipo de documento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestContactTrigger.cls
@isTest
public class TestContactTrigger {

    @isTest
    static void testAltaContacto() {
        Contact contact = new Contact();
        contact.FirstName='pruebaContacto';
        contact.LastName='apellidos';
        contact.Tipo_de_documento__c='NIE';
        contact.N_Documento__c='X8819773D';
        contact.Email='corrreo@correeo.es';
        contact.Sexo__c='Hombre';

        Pais__c pais =new Pais__c();
            pais.Name='España';
            pais.Codigo_ISO2__c='ES';
            pais.Codigo_ISO3__c='ESP';
            pais.Codigo_ISO3_num__c=724;
            insert pais;
      contact.Nacionalidad__c=pais.ID;
    
     Test.startTest(); 
      insert contact;
     Test.stopTest();

    }

}